### PR TITLE
YALB-1552: [admin-theme] Update specific checkbox styles for admin-theme areas

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Adds styling for specific checkbox instances where contrast is an issue (depends on where a checkbox is placed and varies with module use)

### Functional testing steps:
- [x] Login: https://pr-410-yalesites-platform.pantheonsite.io
- [x] Navigate to manage Event content CTA: https://pr-410-yalesites-platform.pantheonsite.io/admin/structure/types/manage/event/fields/node.event.field_event_cta
- [x] Verify the checkbox has a dark background 
Screenshot-20230905155333-1855x1292

---

- [x] Navigate to manage Event content login required : https://pr-410-yalesites-platform.pantheonsite.io/admin/structure/types/manage/event/fields/node.event.field_login_required 
- [x] Verify the checkbox has a dark background 
Screenshot-20230905155358-1681x1294

---
- [x] Navigate to https://pr-410-yalesites-platform.pantheonsite.io/admin/structure/views/view/content
- [x] Verify you see the following

https://github.com/yalesites-org/yalesites-project/assets/366413/cdeb3d07-11c6-4a2b-b94c-acbbfc4f3a7e

### CODE REVIEW

**Review by codechefmarc — APPROVED** [review]
Looks good! Approved!

**Review by dblanken-yale — APPROVED** [review]
Love it!  This will help me so much when dealing with the exports as I go into that last menu to add the exporting functionality.  Thanks for implementing this!

**Comment by joetower** [comment]
@codechefmarc  @dblanken-yale I pushed up another fix to make things more clear. 

Please take a look and confirm you see the following, wherever toggle checkboxes are used: 

https://pr-410-yalesites-platform.pantheonsite.io/admin/structure/types/manage/event/fields/node.event.field_event_cta

https://github.com/yalesites-org/yalesites-project/assets/366413/7fd3462f-36d8-4c36-a0cc-a965b1a781df


---

### Messages
I added an outline to all system messages.

Screenshot-20230906130305-355x1264

Screenshot-20230906130238-2541x722

**Comment by codechefmarc** [comment]
Just a few more small ones:

1) Alert settings form still has a background black for the toggle. If I remove it, the checkbox looks fine as per your new changes:
Screenshot 2023-09-06 at 12 12 21 PM
2) Radio buttons against black background - non selected items are "invisible" until you hover over them. I suggest adding a 1px outline / border to the radio control. Here are two examples. The first being in layout builder, manage allowed blocks modal here: https://pr-410-yalesites-platform.pantheonsite.io/admin/structure/types/manage/page/display (then click on "Blocks available for the One column layout, then Manage allowed blocks)
 
Screenshot 2023-09-06 at 12 15 31 PM

The second is under config split settings (see breadcrumb):
Screenshot 2023-09-06 at 12 21 27 PM

**Comment by joetower** [comment]
@codechefmarc Ah! Thanks. 

- [ ] I fixed the alert checkbox background. https://pr-410-yalesites-platform.pantheonsite.io/admin/yalesites/alert

Screenshot-20230906145718-630x520

- [ ] And fixed those legend and radio elements on https://pr-410-yalesites-platform.pantheonsite.io/admin/structure/types/manage/page/display

Screenshot-20230906144241-2458x1110


---

Some other fixes from Jim's list this morning: 

- [ ] Secondary action buttons now have `darkest-gray` background-color for contrast : https://pr-410-yalesites-platform.pantheonsite.io/admin/modules/uninstall (scroll to very bottom of page)

Screenshot-20230906142921-734x262

---

- [ ] `legend` elements look like the screenshot below: https://pr-410-yalesites-platform.pantheonsite.io/admin/yalesites/settings

Screenshot-20230906141619-2434x458

---

- [ ] media grid library bg color: https://pr-410-yalesites-platform.pantheonsite.io/admin/content/media-grid

Screenshot-20230906145444-2115x1072

**Comment by codechefmarc** [comment]
@joetower - looks great! Thanks for the quick turnaround!

**Pull request merged**
