### PR TITLE
YALB-680: External source for content in lists

### PR DESCRIPTION
**Pull request by nJim**
### Description of work
- Adds new field to allow external links on Events
- Wires the new field to the `url` variable if it exists, otherwise it defaults to the regular `url` value

### Functional testing steps:
- [ ] Navigate to: https://pr-552-yalesites-platform.pantheonsite.io/events-page-for-testing-external-links
- [ ] Verify you see one Event marked as external (with arrow icon)

https://github.com/yalesites-org/yalesites-project/assets/366413/1ffbfdbb-0d6b-4198-8162-3faa33b82814

### CODE REVIEW

**Comment by joetower** [comment]
@nJim @dblanken-yale I have a page setup with my Atomic changes here: https://pr-552-yalesites-platform.pantheonsite.io/events-page-for-testing-external-links

This is using my new same-named-branch for Atomic: https://github.com/yalesites-org/atomic/pull/200

This PR's multidev doesn't have all the work from `develop`, though (in the component library), so David's link treatments aren't in place. When I tested this locally, these new external links were getting marked as external, but they were not opening in a new window. 

Should we rely on testing this locally? I wonder if we could create a branch with the changes from `develop` called `YALB-680-external` in the component library repo and then rebuild this workflow? 🤔 That should work, right?

Locally I see this: 


https://github.com/yalesites-org/yalesites-project/assets/366413/4ba9c77e-6f63-4134-a6d0-745b6beaea15

**Comment by joetower** [comment]
@nJim  @dblanken-yale Okay, I regenerated this multidev with a DO NOT MERGE PR from CL: https://github.com/yalesites-org/component-library-twig/pull/333

Now https://pr-552-yalesites-platform.pantheonsite.io/events-page-for-testing-external-links should look better 👍 

Thank you!

**Comment by joetower** [comment]
@nJim I _think_ this is ready for review? I added some PR testing notes above and created the Atomic side of the branch here: https://github.com/yalesites-org/atomic/pull/200

**Comment by miketullo95** [comment]
going through this, would it be possible to include the external icon in search results as well? see screenshot below
Screenshot 2024-02-08 at 12 43 22 PM

**Comment by dblanken-yale** [comment]
@joetower Looks like in the search it's still showing as a local URL; providing you do the same in atomic as you did with the others the link treatment will apply.  :D

**Comment by codechefmarc** [comment]
This all worked for me - I would agree about the search page showing the correct external URL.

**Comment by joetower** [comment]
@dblanken-yale @miketullo95 @codechefmarc  Great call, ready for another look: https://pr-552-yalesites-platform.pantheonsite.io/search?keywords=plex

Screenshot 2024-02-08 at 5 18 40 PM

**Review by miketullo95 — APPROVED** [review]
per stand up, this is approved! :)

**Pull request merged**
