### PR TITLE
YSP-301: Card collections without images

### PR DESCRIPTION
**Pull request by laura-johnson**
### Description of work
- Adds text_card view mode for content
- Adds config for text_card on all content types
- Adds text_card to the views tool

### Functional testing steps:
- [ ] All variations of the text card have been added to a test page for demo and review. Please make sure the [rendered content in Drupal](https://pr-600-yalesites-platform.pantheonsite.io/text-card-demo) matches the [styles in the Yale Design System](https://yalesites-org.github.io/component-library-twig/?path=/story/organisms-card-collection--post-card-collection).
- [ ] Edit any page layout to see these new features in action
- [ ] Add a new 'view' and note that a new 'Text Card' option exists. The previous 'Card' display has been renamed 'Visual Card'. These exist for all content type.
- [ ] The new text card display has an icon
- [ ] Verify that adding a Text Card for any content type results in a card identical to Visual Card but with no image.

I set up a demo here: https://pr-600-yalesites-platform.pantheonsite.io/text-card-demo

Here is the related Atomic PR with templates: https://github.com/yalesites-org/atomic/pull/210

Screenshot of the new controls:
Screenshot 2024-09-20 at 10 41 07 AM

Screenshot of all text card options:
pr-600-yalesites-platform pantheonsite io_text-card-demo

### CODE REVIEW

**Review by codechefmarc — APPROVED** [review]
This looks good to me! Tested a few different modes wit the views tool and compared to custom cards as well. I'd like @kara-franco to review as well as she was the original reporter.

**Comment by kara-franco** [comment]
Amazing!! Approved on my end both for a11y and completion of ticket!

**Review by nJim — CHANGES_REQUESTED** [review]
Great work. Everything is working as described in the ticket. Now that we're stress testing this concept, I see at least one change that may require design or UX to weigh-in on. I will follow up on Teams.

1. The list of pages results in grid that is difficult to parse. This can also happen with posts and events if they lack a lot of the details. These cards can appear like a strange array of text. Do we need to employ some border like we do with the custom card collections? Or maybe a new design treatment for this text-centric display?
Screen Shot 2024-03-22 at 11 00 00 AM

2. A smaller fix is that the new icon is bigger than the other. In can actually flow outside of the picker control. We should reach out to Mike T when he returns from vacation as it may be time to update all of these icons for consistency. 
Screen Shot 2024-03-22 at 10 49 31 AM

**Comment by nJim** [comment]
We will discuss the frontend needs in today's standup part 2.

**Comment by nJim** [comment]
@kara-franco Will help identify treatments for content without an image.

**Review by nJim — APPROVED** [review]

**Comment by dblanken-yale** [comment]
Closing for now.

**Pull request closed without merging**
