### PR TITLE
YALB-527: Image Cropping

### PR DESCRIPTION
**Pull request by ModulesUnraveled**
### Description of work
- Creates a "Banner (16:5)" crop type
- Creates "Banner (16:5)" image styles and responsive image style
- Creates "Banner (16:5)" media view mode, and configure it to use the above
- Updates the Banner component to use the above media view mode
- Tweaks some of the preview view modes of paragraphs

### Functional testing steps:
- [ ] [Log in](https://pr-29-yalesites-platform.pantheonsite.io/user/login) and then [create a page](https://pr-29-yalesites-platform.pantheonsite.io/node/add/page), and give it a title
- [ ] Go to the "Banner" tab
- [ ] Fill in the text fields
- [ ] Click "Add Media"
	- [ ] Upload a photo and give it some alt text
	- [ ] Right below the alt text field, expand the "Crop image" section
		- [ ] In here, move the crop indicator to wherever you want. Just note what's inside the indicator to validate it on the frontend.
	- [ ] Click "Save"
- [ ] Save the Banner, and save the page
- [ ] Verify the banner is shown, and that your cropped selection is used in the banner at all screen sizes
- [ ] Inspect the image, and verify the images in the `srcset` are using the `16_5_<width>` image styles.

### Notes
- [ ] Edit the page, and edit the banner
	- [ ] Note that you can't change anything about the image at the moment... I'd like to be able to adjust the crop here easily.
	- [ ] Currently, you have to go to /admin/content/media and edit the media item to be able to adjust the crop

### CODE REVIEW

**Review by miketullo95 — APPROVED** [review]
this worked great! I do agree, being able to edit the page after you have done the initial cropping would be nice.

**Review by kara-franco — APPROVED** [review]
Very nice! I agree with the notes, it will be easier to be able to edit/adjust the crop to an existing banner image. 

Potential future improvements: 

- [ ] Provide more user feedback when the image is cropped. Currently the 'Reset Crop' button background color changes. An additional message next to the button or some visual change in the interface will help users understand that the image is now cropped. 

Screen Shot 2022-05-11 at 1 38 02 PM

- [ ] Add keyboard focus (tabindex=0 + JS)to the cropping tool so that a user can arrow down or up to move the cropping tool.

**Comment by ahitson** [comment]
Agree with all of these notes. But I like where this is going!

**Review by ahitson — APPROVED** [review]

**Comment by callinmullaney** [comment]
I also came across this module (https://www.drupal.org/project/media_library_media_modify) that sounded interesting. I havent used it before but modifying and storing the data on the reference field instead of the media entity may be a useful feature when coupled with cropping.

**Comment by ModulesUnraveled** [comment]
Notes are all captured here: https://yaleits.atlassian.net/browse/YALB-557

Merging this as-is.

Thanks everyone!

**Pull request merged**
