### PR TITLE
YSP-399: Localist: Embedding widgets

### PR DESCRIPTION
**Pull request by codechefmarc**
### Description of work
- Adds the ability to embed Localist widgets inside Drupal

### Functional testing steps:
- [x] Login to the multidev at https://pr-630-yalesites-platform.pantheonsite.io
- [x] Visit this page to view a list of already embedded widgets: https://pr-630-yalesites-platform.pantheonsite.io/testing-localist-widgets
- [x] Verify that the widgets load (styling will be done in a different ticket)

Testing Localist Widgets _ YaleSites

- [x] Add a new page, then enter layout builder
- [x] Add a block of type "Embed"
- [x] When the modal opens, fill out the administrative label and click "Add media"
- [x] At the top, click "Learn about supported formats and options"
- [x] Verify there is a new option for Localist
- [x] Open the example and copy the embed code
- [x] Close the modal
- [x] Paste the embed code into the "Embed Code or URL" and then click "Add"
- [x] Add a title and then click "Save"
- [x] Click "Insert selected"
- [x] Verify that the icon for this embed is the Localist icon

Screenshot 2024-04-11 at 6 21 16 PM

- [x] Click "Add block"
- [x] Save layout builder
- [x] Verify that the widget added shows a listing of events.

## To create a widget of your own on Localist

- [ ] Visit https://yale.enterprise.localist.com/help/widget to create a new widget (note, you should not need to be logged in to do this)
- [ ] Fill out the fields to create the widget - Note the only groups that have events at the moment are Yale Health and Asian Network at Yale.
- [ ] At the bottom of the form, click "Generate Embed Code"

Screenshot 2024-04-11 at 6 09 52 PM

- [ ] Copy the code and then follow the instructions above to insert the embed code

### CODE REVIEW

**Comment by codechefmarc** [comment]
@joetower - tagging you here because I'm seeing that once we've embedded these into Drupal, it's getting some extra styling that doesn't show up when we do the preview on Localist. I'll also mention as part of YSP-393. Thank you!

**Review by dblanken-yale — APPROVED** [review]
This is great!  Nice work!  Tested locally as well and the image copies.

**Comment by codechefmarc** [comment]
@dblanken-yale - I wonder the alpha mask is doing strange things - I tested this locally and it works fine when you add the media, but if you go to edit the media (via the sidebar) I see it fully dark. Also, I see it fully dark when looking at the changes in the repo here.

Screenshot 2024-04-17 at 4 24 13 PM

**Comment by dblanken-yale** [comment]
Ack!  That is strange. I’ll need to take another look at mine as well.  I’ll look first thing this morning to see if we can fix that up.

Thank goodness you found that one!

**Pull request merged**
