### PR TITLE
YALB-537: Layout Paragraphs - Polish frontend editing/saving experience

### PR DESCRIPTION
**Pull request by ModulesUnraveled**
### Description of work
- Applies a patch (that I created) to the layout_paragraphs module to improve the editing experience

### Functional testing steps:
- [x] log in to the site, and create a page with a title, and a component if you want. Save the page.
- [x] On the frontend, click the "Edit content" button that appears when you hover the content area
- [x] Verify the "Save" and "Close" buttons are in the same place the "Edit" one was (at the top, not the bottom)

## Notes:
I submitted the change to the module here https://www.drupal.org/project/layout_paragraphs/issues/3280171. Any reviews, etc. would be great!

### CODE REVIEW

**Review by nJim — APPROVED** [review]
Solution works and kudos on staying organized while also giving back. Your documentation on Drupal.org is perfect.

I worry that patches like this can become unsustainable if they do not get merged into the main project. Future changes can cause the patch to fail, and recreating the patch is sometimes just as hard as doing the work over again. So while for now this is a fine approach, I want us to approach with some caution. If we have multiple patches then we may be taking on too much tech debt.

I've reached out to Justin at Aten to see if they have a roadmap and where we can align efforts. I asked if there is someone willing to meet to talk about how we can ensure everyone is moving in the right direction. Will keep you posted.

**Comment by ModulesUnraveled** [comment]
Yeah, I was a little bummed to not have any response or feedback at all after almost a week, but, you know... it's open source. So, it is what it is.

I was thinking about whether talking to Justin directly would be a good idea. Basically, to say "We're investing time and money into the Layout Paragraphs module. How can we make sure we're in alignment and able to help facilitate its improvement

**Comment by kara-franco** [comment]
Hiya! Is there a multidev that I can use to review the updates? I second all that Mickey mentioned in the issue write-up (I can't believe I missed that we need to add spacebar keyboard support, doh!).

**Review by kara-franco — APPROVED** [review]
Awesome!! Such a better user experience. Besides the tab order issue and the need for adding spacebar behavior to the button, all looks good!!

**Review by miketullo95 — APPROVED** [review]

**Comment by ModulesUnraveled** [comment]
@kara-franco Bumping this. We talked about whether or not to merge this as-is, or if we think we should/need to address the outstanding issues first.

**Comment by kara-franco** [comment]
> @kara-franco Bumping this. We talked about whether or not to merge this as-is, or if we think we should/need to address the outstanding issues first.

Let's merge as-is and write up a ticket with Mickey's feedback (I can write up the ticket!).

**Comment by ModulesUnraveled** [comment]
Merge conflicts are too tedious to weed through here, so I'm going to create a new PR based off of the latest develop, and recreate these four lines of code there.

**Pull request closed without merging**
