### PR TITLE
YALB-1006: Create views builder widget

### PR DESCRIPTION
**Pull request by marcb4k**
### Description of work
- Adds views heading field
- Reworks layout of widget to match mockup (see attached)
- Refactors some code from the default formatter into the manager for reusability
- Adds count of results to the preview so content authors know how many results before saving

### Additional context notes
- This ticket will not cover theming, that will be a separate ticket.
- The mockup shows an "Options" section that handles how many items and paging. As per a Teams conversation with Yale, it was agreed that since Views core handles paging in a certain way, we should mimic that same behavior. The second screenshot shows this reworked options area where the "Number of items to display" is a drop down, and when "Display all items" is selected, the limiter field will be hidden. Otherwise, the limit field will be shown and the label (and eventually help text) will change.
- Another [forthcoming PR in Atomic](https://github.com/yalesites-org/atomic/pull/98) in Atomic will add the appropriate `dom_id` class to allow Ajax paging to work.

### Functional testing steps:
- [x] Create 4-5 nodes of type news event
- [x] For each, change the "Publish Date" in the sidebar under "Publish Information" accordion to a date that is different for each
- [x] Make sure the title field includes the date in some way (this is because the publish date is not yet used in the templates)
- [x] Publish and save each news node
- [x] Create a new page and add a paragraph of type View
- [x] Verify that the View paragraph layout matches the rough mockup (icons and styling of headings to come later)
- [x] Put some text into the "View Heading"
- [x] Set "I want to show" to "Posts", choose either "news card grid" or "news list"
- [x] Set the "Sorting by" to either option
- [x] Save the paragraph
- [x] Verify that the paragraph preview shows the correct information for the settings specified and that the "Total results with these settings" has a value. If that value is 0, change some of the settings and resave the paragraph and see if the count of results show up.
- [x] Publish the page, and save the page.
- [x] Verify that the results are correct as per the settings
- [x] Edit the page and change some settings - specifically test out the "Number of items to display" select list and accompanying limit numeric value box as well as sort order.
- [x] Verify that the "Number of items to display" box selection changes the visibility and the title of the "Items" limit box.
- [x] Save the paragraph
- [x] Verify the preview is updated and, after save of the node, verify that the results change depending on the settings
- [x] You may repeat with events and or pages

Mockup:
Views-Basic-Interface-Mockup

Agreed upon changes for the "Options" section:
Screenshot 2023-02-27 at 5 01 04 PM

### CODE REVIEW

**Comment by rigoucr** [comment]
hey @marcb4k  Awesome Job, Everything worked for me as expected,  but I found a small detail , when I switch the `Number of items to display` option  to `Display all` , it is throwing a AJAX error into the Browser console and also into the  dblog 

https://user-images.githubusercontent.com/2217827/223874948-266f2d31-a8b9-42c6-923b-3a45eb566cbb.mov
Screenshot 2023-03-08 at 5 20 30 PM

**Review by rigoucr — APPROVED** [review]
Found  Some dblog errors related to this

**Review by rigoucr — CHANGES_REQUESTED** [review]
Sorry I pressed the wrong option, but I left a comment there @marcb4k

**Comment by marcb4k** [comment]
@rigoucr - Good catch on that console error. Fixed and requesting another review. Thanks!

**Review by rigoucr — APPROVED** [review]
:shipit:

**Pull request merged**
