### PR TITLE
 YALB-1501: Bug: Missing admin styles - Alternate Admin Theme Approach

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- **This approach would negate the changes here: https://github.com/yalesites-org/yalesites-project/pull/377 and I would close that PR**.
- Changes the theme configuration to use the `dark` variation (dark-mode). 
- **This change results in significantly less overrides and overall would help to sustain and stabilize our customizations**.
- The big CSS variable which factors into the admin page background colors is `var(--gin-bg-layer)` which is used for the toolbar and it is used as the main content area background-color ( specifically on these, ```.gin-layer-wrapper, .block-system-main-block > form, .views-exposed-form.views-exposed-form, .views-edit-view, .views-preview-wrapper, #views-entity-list, .module-filter-update-status-form .table-filter, .admin.my-workbench```) 
  - Because the `--gin-bg-layer` (`--dark-theme-gray: #4E5959;`) is a dark color, using the `gin--dark-mode` sets all content within to use `var(--gin-color-text)` which does not need to change from `(--wool)`. 
  - I did override the background color for the above noted selectors to use an even darker background color (` --darkest-gray: #1f1f1f;` ) to avoid insufficient contrast when I checked Wave's contrast checker. 
  - This allows us to not override specific text elements on top of a lighter background color, as in the previous design and approach in the initial admin darker theme redesign. 
- Refines CSS variables, removing some we no longer need.

### Functional testing steps:
- [x] Login to the multidev: https://pr-388-yalesites-platform.pantheonsite.io/
- [ ] You can compare theme differences between this multidev and this one: https://pr-377-yalesites-platform.pantheonsite.io/

---

- [x] Browse various admin pages and verify there are no legibility issues
- [x] Some examples to check:
  - [x] https://pr-388-yalesites-platform.pantheonsite.io/admin/reports
  - [x] https://pr-388-yalesites-platform.pantheonsite.io/admin/reports/updates
  - [x] https://pr-388-yalesites-platform.pantheonsite.io/admin/reports/dblog
  - [x] https://pr-388-yalesites-platform.pantheonsite.io/admin/reports/editoria11y
  - [x] https://pr-388-yalesites-platform.pantheonsite.io/admin/reports/upgrade-status
  - [ ] https://pr-388-yalesites-platform.pantheonsite.io/admin/appearance/settings/ys_admin_theme
  - [x] https://pr-388-yalesites-platform.pantheonsite.io/admin/content
  - [x] https://pr-388-yalesites-platform.pantheonsite.io/admin/help
  - [x] https://pr-388-yalesites-platform.pantheonsite.io/admin/content/media-grid
  - [x] https://pr-388-yalesites-platform.pantheonsite.io/media/add
  - [x] https://pr-388-yalesites-platform.pantheonsite.io//admin/structure/views
  - [x] https://pr-388-yalesites-platform.pantheonsite.io//admin/structure/views/view/block_content
- [x] Add or edit some content  https://pr-388-yalesites-platform.pantheonsite.io/admin/content
- [x] Confirm layout builder styles are legible and adding content is legible.

---

- [x] Navigate to: https://pr-388-yalesites-platform.pantheonsite.io/admin/structure/views/view/manage_pages 
- [x] Interact with elements on the page and make sure there are no legibility issues

---

- [x] Navigate to https://pr-388-yalesites-platform.pantheonsite.io/admin/content/manage-pages?title=dfgdfgdfg&status=All
- [x] Interact with elements on the page and make sure there are no legibility issues

---

- [x] Navigate to https://pr-388-yalesites-platform.pantheonsite.io/admin/structure/views/add
- [ ] Interact with elements on the page and make sure there are no legibility issues
---

- [x] Navigate to https://pr-388-yalesites-platform.pantheonsite.io/admin/config/content/layout-builder-restrictions
- [ ] Interact with elements on the page and make sure there are no legibility issues

---

- [x] Navigate to https://pr-388-yalesites-platform.pantheonsite.io/admin/structure/types/manage/page/display
- [ ] Interact with elements on the page and make sure there are no legibility issues

---

- [x] Navigate to https://pr-388-yalesites-platform.pantheonsite.io/admin/modules/uninstall
- [x] Interact with elements on the page and make sure there are no legibility issues

---

- [x] Navigate to https://pr-388-yalesites-platform.pantheonsite.io/admin/modules/uninstall and act as if you're going to uninstall a module (/admin/modules/uninstall/confirm)
- [x] Interact with elements on the page and make sure there are no legibility issues

---

- [x] Navigate to https://pr-388-yalesites-platform.pantheonsite.io/admin/config/search/search-api/index/node_index/clear
- [x] Interact with elements on the page and make sure there are no legibility issues

---

- [x] Navigate to https://pr-388-yalesites-platform.pantheonsite.io/node/add/event
- [x] Interact with elements on the page and make sure there are no legibility issues

---

- [x] Navigate to https://pr-388-yalesites-platform.pantheonsite.io/admin/structure/media/manage/image/fields/media.image.field_media_image
- [ ] Interact with elements on the page and make sure there are no legibility issues

---

- [x] Navigate to https://pr-388-yalesites-platform.pantheonsite.io/admin/yalesites/settings
- [x] Interact with elements on the page and make sure there are no legibility issues

---
 
- [ ] Navigate to https://pr-388-yalesites-platform.pantheonsite.io/new-testing
- [ ] Interact with the table and make sure `:hover` interaction doesn't change table element colors

---
### contrast

Screenshot-20230816143435-2555x1237
Screenshot-20230816143852-2550x1147

### CODE REVIEW

**Review by codechefmarc — CHANGES_REQUESTED** [review]
All looked good to me with the exception of checkboxes that aren't checked don't get the outline. If they have focus or are checked they get an outline / rounded borders:

Screenshot 2023-08-16 at 4 41 42 PM

Screenshot 2023-08-16 at 4 41 47 PM

**Review by dblanken-yale — CHANGES_REQUESTED** [review]
It's looking great so far as I go through, although I did see an issue in the upgrade status where the Relax percentage is unreadable at 94%.  I'm going to keep going, but wanted to document this as well.

Screenshot 2023-08-17 at 8 55 02 AM

**Comment by dblanken-yale** [comment]
https://pr-388-yalesites-platform.pantheonsite.io/posts/2023-06-16-table-test-page

This did not exist; is this what you wanted us to test?  The not found?

**Comment by dblanken-yale** [comment]
I left those that had the issues @codechefmarc and I found unchecked so we have reference to jump to to check updates.  It's looking really good, and if this is much less code than the other (going to look at that next), then this sounds good.

**Comment by dblanken-yale** [comment]
Less overriding would be my pick, personally.  👍

**Comment by joetower** [comment]
@codechefmarc Thank you so much! This should look better now https://pr-388-yalesites-platform.pantheonsite.io/admin/structure/views/add I wasn't able to add a border/outline around them when inactive (these checkbox/booleans share the same markup as those on content management pages like `/admin/content` which made those checkboxes look bad)

---

@dblanken-yale Also, thank you, so much!

That percentage should be legible now: https://pr-388-yalesites-platform.pantheonsite.io/admin/reports/upgrade-status

Also, yes, I just updated that item in the testing criteria (sorry about that). This is the new page: https://pr-388-yalesites-platform.pantheonsite.io/new-testing. This is mainly to verify the hover states on table tr's aren't active - nothing changes on hover.

**Review by codechefmarc — APPROVED** [review]
@joetower - Much better, thank you for the radio button fix! I checked in the modals and odd places I found issues last time as well and all looked good to me. Approved!

**Comment by codechefmarc** [comment]
@joetower - found another one at `/admin/modules`

Screenshot 2023-08-17 at 8 50 54 PM

Also, same page, but I've seen this in some other places too, if you hover over the top part of that page, the details/summary - when you hover, it will allow you to read the details summary.

**Comment by joetower** [comment]
@codechefmarc When you have a moment, could you please confirm that the screenshot you posted is not reflected on the multidev here: https://pr-388-yalesites-platform.pantheonsite.io/admin/modules

What you were noting was a local issue, right?

**Comment by codechefmarc** [comment]
@joetower - yup, that was local and we fixed it. Turned out to be a config that I didn't import. The multidev looks good!

**Comment by joetower** [comment]
@miketullo95 Yes, that is the biggest difference I'm presenting here. This branch is a totally new approach to mostly achieving your original mockup, but using Gin's variables as they are.

The previous admin theme had a lot of overrides which, over time would become more problematic. When this 1501 ticket came along with more theming issues, I decided to take another look at using Gin's dark-theme as a base, instead of the light theme. This branch is a new approach using Gin's dark theme and minimally overriding what it wants to do.

I outlined specifics in the PR description above, but the core difference here is that Gin has a variable called `gin-bg-layer`. This color, whatever you may define it as, is used as a background-color behind the toolbar (admin toolbars) and the main page content background (what we were overriding to be `wool`). Another variable `gin-text-color` is used by other modules we're using. To add a light color behind the admin interface would result in us overriding a lot of variables again and put us in the same situation.

We could instead look at using Gin's `light` theme again, but with less overrides. What are your thoughts? The core problem this branch tries to solve is to make more sustainable overrides to the Gin admin theme so that we aren't continually finding issues as the result of overriding a lot of specific selectors.

**Comment by miketullo95** [comment]
@joetower Ah, this makes sense. Thank you for explaining it and the decision is definitely the correct one. My only hiccup I think is just my personal preference around this more high-contrast approach compared to the lighter grey bg with wool. Is that something that can be tweaked using this new methodology?

In regards to light mode, I think dark mode is the right direction per OPACs request. 

@kara-franco do you have any thoughts?

**Comment by joetower** [comment]
@miketullo95 You're welcome! 

When you say high-contrast, is there a specific area you'd like to explore altering? The edit screen form area?

I did make the background color of the site darker than the admin bars to increase the contrast of the light text place upon it, which was done after I ran an admin page through an a11y contrast checker. We could explore other colors, depending on which area you're interested in altering. It may result in less of a passing contrast ratio. We'd need to explore it more.

**Comment by miketullo95** [comment]
Yeah so I think the area that is tripping me up is the form background. It's the form background and the lack of "separation" between the form and the main area background. I'm not sure if these are the official names so I just doodled this haha.

Screen Shot 2023-08-22 at 11 53 22 AM

is changing the form area color a step in the previous direction of overwriting things? Or would it be as simple as changing it to a slightly lighter color (keeping contrast rules)? I think also other UX/AX people should weigh in on this topic as well.

**Comment by dblanken-yale** [comment]
@joetower I actually like that as well.  Much easier focus on the important parts imo.  Nice work!

**Comment by kara-franco** [comment]
The gray is much better! Contrast is tricky, many people who have cognitive disabilities or low vision find sharp contrast (black/white) jarring and difficult to read. Can we darken the header in the Content view? That needs more visual distinction.

**Comment by joetower** [comment]
@kara-franco When you say: 
>  Can we darken the header in the Content view? That needs more visual distinction.

Which section are you referring to? Could you please post a screenshot?

**Comment by joetower** [comment]
Looks like we could do this. I don't think it will cause issues in other sections. 
Screenshot-20230822131749-2525x988

**Comment by miketullo95** [comment]
one small thing - the theme settings button has a contrast issue 
MicrosoftTeams-image (5)

**Comment by joetower** [comment]
@miketullo95 Thank you! I did fix that but the newer branch isn't building. 

I'll rebuild and let you know when that change is in place. Thank you!

**Comment by kara-franco** [comment]
I spoke with Nick and he had some good feedback about the dark theme: 
Softening the contrast would be good, perhaps experimenting with a slightly less bright white color for the heading text? Additionally, the text spacing can be a bigger concern in dark mode, the font should be at least 12pt. 

I'm almost done combing through looking for any color contrast issues. I'll post once I complete.

**Comment by joetower** [comment]
@kara-franco Sounds good. 

I will mention that if we change text-color in one section we need to change it in all, since the majority of text color uses one variable `gin-color-text` (which is set to `wool` / `#fbfbf6`).

**Comment by kara-franco** [comment]
Alrighty, this is the list of color tweaks, not bad at all! 

- [ ] Save Configuration needs tweaking, darker text should do the trick. 

Screenshot 2023-08-22 at 5 16 19 PM

- [ ] User interface components, such as inputs, labels and required asterisks need to pass 3:1. Change required asterisk to #E09494.  
Screenshot 2023-08-22 at 5 18 41 PM

- [ ] Placeholder text and input field border: must meet 3:1 contrast, use #A8A8A8 * * Note all input fields should have 3:1 * *

Screenshot 2023-08-22 at 5 21 13 PM

- [ ] Accordion- interactive area needs more definition > it's not clear that the tab opens a panel (the previous iteration had solid bounds to where to click) 

Screenshot 2023-08-22 at 5 25 15 PM

Screenshot 2023-08-22 at 5 27 25 PM

- [ ] Media Library- remove button needs to be lighter

Screenshot 2023-08-22 at 5 35 05 PM

**Comment by joetower** [comment]
@kara-franco Thank you! 

Could you tell me what page you were seeing that Media Library "Remove" button on? I'm not seeing it here: https://pr-388-yalesites-platform.pantheonsite.io/admin/content/media-grid

Is it on a specific component?

**Comment by joetower** [comment]
@kara-franco Also, would this be an acceptable solution for the accordions? Or should we explore overriding the background-color and the text color?

https://github.com/yalesites-org/yalesites-project/assets/366413/0198ca1e-1e9e-4c05-b92a-f5e1b59ab7d6

Thank you!

**Comment by miketullo95** [comment]
@joetower just noticed this, did the 2nd admin bar get unpinned during this?

**Comment by miketullo95** [comment]
two small things I noticed with accordions: 
Screen Shot 2023-08-24 at 9 39 41 AM
1.  looks like there is a gradient texture being left over from the light mode
2. could we add a few px padding between these two buttons? (edit and 3 dots)

**Comment by joetower** [comment]
@miketullo95 Those two items should now be fixed: https://pr-388-yalesites-platform.pantheonsite.io/node/10/layout

Screenshot-20230824094018-1265x572

Please let me know if you see anything else. Thanks!

**Comment by miketullo95** [comment]
@joetower embed help screen header colors 
Screen Shot 2023-08-25 at 11 47 37 AM
also talking about embeds, these icons are provided by us right? These should be inverted 
Screen Shot 2023-08-25 at 11 48 45 AM
Alert icons have an odd thing going on. First 1s it has the correct color for the stroke but then it becomes black 
Screen Shot 2023-08-25 at 11 57 10 AM
The title bar should have the same dark color as the footer bar on the right side panel for most actions 
Screen Shot 2023-08-25 at 11 59 27 AM
toggle on/off doesn't have a distinction 
Screen Shot 2023-08-25 at 12 01 55 PM

I think these are mostly it for me, once these go through it should be approved on my end 👍

**Comment by joetower** [comment]
@miketullo95 Those items should be fixed: https://pr-388-yalesites-platform.pantheonsite.io/welcome/customize-confidence

### Embed component 
I add a background color to the png images and fixed the header colors
 
Screenshot-20230828141529-1424x1075
Screenshot-20230828142246-2109x1351


----

### Alert focus states

https://github.com/yalesites-org/yalesites-project/assets/366413/6132afd3-ad69-48cf-b8ea-97d776840f3e

---
### Sidebar ui titlebars
Screenshot-20230828144613-2015x1188

---

### Display option toggle state


https://github.com/yalesites-org/yalesites-project/assets/366413/ec92a6e5-40f4-43e4-a4e3-20d0a23604f4

---

Please take a look and test some more. 

Thanks again for all the awesome testing!

**Comment by miketullo95** [comment]
Things are looking great! 

- [ ] Could the focus state (alert settings) outline be white for high contrast? Or will this effect other things

- [ ] Can we change the background of the collapsable sidebar settings in node setup be the lighter grey?

Screen Shot 2023-08-29 at 10 33 26 AM

- [ ] Remove dark background from CAS user roles selections
    - [ ] Looks like it could be the same variable in Site Settings for "enable search form"

Screen Shot 2023-08-29 at 10 42 29 AM
Screen Shot 2023-08-29 at 10 46 09 AM

**Comment by joetower** [comment]
@miketullo95 I pushed up changes to these requests: 

> Could the focus state (alert settings) outline be white for high contrast? Or will this effect other things
- this is an custom form with its own CSS/selectors, so we can control it easier. This should be fixed now. 

Screenshot-20230829102654-1119x657

---

> Remove dark background from CAS user roles selections
> Looks like it could be the same variable in Site Settings for "enable search form"
- This should be fixed

---
On this one: 
> Can we change the background of the collapsable sidebar settings in node setup be the lighter grey?

This request is more difficult and puts us in the potentially scary override situation again. Please see the first video below: if we change the color used in the background of the claro details wrapper it creates other contrast issues with the toggles. Because elements are reused in some places with the same markup but atop different elements, it creates a bit of a whack-a-mole situation, without creating heavy-handed overrides (targeting specific selectors), it's difficult to address specific instances. Are you okay leaving these as-is? I also tried changing some specific elements, please see second video below.

### Changing the background only
https://github.com/yalesites-org/yalesites-project/assets/366413/eeecad93-1137-4932-90ae-e6c3df6a3fed

### Targeting specific elements produces weird color nesting (the checkbox/toggles need the darkest color background in these instances so that they have enough contrast)

https://github.com/yalesites-org/yalesites-project/assets/366413/6d67cb8b-a407-486c-ad53-d878318ae7fe

**Comment by miketullo95** [comment]
> On this one:
> 
> > Can we change the background of the collapsable sidebar settings in node setup be the lighter grey?
> 
> This request is more difficult and puts us in the potentially scary override situation again. Please see the first video below: if we change the color used in the background of the claro details wrapper it creates other contrast issues with the toggles. Because elements are reused in some places with the same markup but atop different elements, it creates a bit of a whack-a-mole situation, without creating heavy-handed overrides (targeting specific selectors), it's difficult to address specific instances. Are you okay leaving these as-is? I also tried changing some specific elements, please see second video below.
> 
> ### Changing the background only
>  sidebar-colors.mp4 
> ### Targeting specific elements produces weird color nesting (the checkbox/toggles need the darkest color background in these instances so that they have enough contrast)
>  sidebar-colors-part-two.mp4

No worries on this one! We can drop this idea, definitely do not want to go down this can of worms again. Im going to go on one final look-through after standup today and this should get the approval from me. 

Amazing work on this behemoth of a ticket 👍

**Comment by joetower** [comment]
@miketullo95 Thank you for all the thorough testing! 

Yes, please test, test more and keep me posted.

**Comment by joetower** [comment]
@miketullo95 Also, could you please test this ticket https://yaleits.atlassian.net/browse/YALB-1479 on this environment? Please let me know if you still see this issue present, while testing.

**Comment by miketullo95** [comment]
@joetower would changing the form input background color reveal contrast issues? I think the biggest suggestion we are getting is to lighten the inputs. Would we be able to match the form input background with the wysiwyg background color? Similar to my screenshot, but specifically #2D2D30. 

Screen Shot 2023-08-30 at 10 36 39 AM

**Comment by joetower** [comment]
@miketullo95 That is too much lighter, it passed Wave contrast so :+1: 

I matched what ckeditor is using which is `#3b3b3f`.  https://pr-388-yalesites-platform.pantheonsite.io/node/add/profile

Screenshot-20230830142733-2522x1204

Please take a look and let me know what you think. Thanks!

**Comment by joetower** [comment]
@kara-franco Thank you and that sounds great to me!
And thank you @miketullo95 !

**Pull request merged**
