### PR TITLE
fix(YSP-528): V1.3.0: Media Library add tag column in view

### PR DESCRIPTION
**Pull request by dblanken-yale**
## [YSP-528: V1.3.0: Media Library add tag column in view](https://yaleits.atlassian.net/browse/YSP-528)

While users can add tags, there wasn't a usage for them yet in the system.  This was a way to still convey that entering this can be useful by giving them a chance to filter via the media table by tags and see what tags are assigned to a media.

This adds both a tags filter using Drupal's autocomplete, and a tags column to display tags associated with media.

### Description of work
- Adds tag filter for media table view
- Adds tag column for media table view

### Functional testing steps:
- [ ] Visit the media table view
- [ ] Verify that you can search by tag
- [ ] Verify that you can see a column displaying tags

Note: You might need to add some media or add tags to see this functionality.

### CODE REVIEW

**Comment by miketullo95** [comment]
@dblanken-yale i dont seem to see the tag column, could that be a permission issue? 
Screenshot 2024-05-14 at 1 39 22 PM

**Comment by miketullo95** [comment]
@dblanken-yale i see it now? for some reason... idk ¯\_(ツ)_/¯ this looks great! lol

**Review by miketullo95 — APPROVED** [review]
👍

**Review by kara-franco — APPROVED** [review]
I see the column for Tags now

**Review by codechefmarc — CHANGES_REQUESTED** [review]
Looks and works great! One thing I'd change is the link to the taxonomy term. Since this links to the front-end for any content/media tagged with that tag and we don't have that styled or working yet.

Screenshot 2024-05-14 at 5 54 38 PM

**Comment by dblanken-yale** [comment]
@codechefmarc Ah!  I was so focused on getting them on there I didn't even see that!  Good find!  I'll see what I can do to make them unlikable?  Looks like that's what we did with the content types.  Whew, thanks for checking that!

**Comment by dblanken-yale** [comment]
Rebuilding now with the change @codechefmarc

**Review by codechefmarc — APPROVED** [review]

**Pull request merged**
