### PR TITLE
YSP-509: Add Code Style to WYSIWYGttons to basic editor

### PR DESCRIPTION
**Pull request by laura-johnson**
### Description of work
- Adds the ‘Code’ and ‘Code Block’ buttons to the CKEditor toolbar for the ‘Basic HTML’ text formatter with supporting styles
- Adds a demo of the code block in Storybook in the text molecule component.
- Adds highlight.js to the codeblock to highlight the code.

### Functional testing steps:
- [ ] Edit a text block in layout builder that uses the Basic HTML format, add a code snippet or block of code. For the block of code the default is plain text, there is a pull-down arrow on the right of that button that you can use to select from a number of code styles
- [ ] Verify they look as expected (current style shown below)
- [ ] Go to the text molecule in Storybook, verify you see a styled code block at the bottom

highlight-codeblock

Depends on: https://github.com/yalesites-org/component-library-twig/pull/367

### CODE REVIEW

**Review by codechefmarc — APPROVED** [review]
Works great! Approved!

**Review by miketullo95 — APPROVED** [review]
looks great!

**Comment by laura-johnson** [comment]
There is a demo here of code blocks with the highlightjs library added:

https://pr-655-yalesites-platform.pantheonsite.io/code-blocks-test

This will need another code review because I was not entirely sure how adding an external JS library should work in the theme. Happy to update it if necessary!

**Review by joetower — APPROVED** [review]
@laura-johnson This looks good to me 👍

**Comment by dblanken-yale** [comment]
I'm assuming this is a "Drupalism", but once you start a code block, you can't edit underneath it in the WYSYWIG.  At least, on Safari you can't--you get stuck in the code block.  It's working great otherwise and looks good!  Nice work!

**Pull request merged**
