### PR TITLE
fix: YALB(1963): Hotfix: Text Style Variation not set on existing blocks

### PR DESCRIPTION
**Pull request by dblanken-yale**
## Pull requests
- https://github.com/yalesites-org/yalesites-project/pull/544

### CODE REVIEW

**Comment by dblanken-yale** [comment]
Doh, it overwrote my instructions.  haha

Basically, I thought a good test would be to attempt to bring down that URL in question in the Jira ticket and verify that before the update hook, text_style_variation is not set, and after running the hook update, it is set.

To run the update hook: `lando drush -d php-eval '\Drupal::moduleHandler()->loadInclude("ys_core", "install"); echo ys_core_update_9003();'`

**Comment by dblanken-yale** [comment]
I added both @codechefmarc and @nJim to just double check that I am, indeed, targeting the latest revisions since `loadRevision` has been deprecated.  Using `$block_content_storage->load` seems to work in my tests, but I can't find [specific documentation](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21EntityBase.php/function/EntityBase%3A%3Aload/10) that states it always brings back the latest revision?  Didn't know if you knew off the top of your head at all?  I assume it is since it should return the entity.

Also brings up that our first update hook is referencing `loadRevision` still.  Didn't know if we wanted to include that change in this as well or make it a separate ticket since it's not really needed for this hotfix.

**Review by codechefmarc — APPROVED** [review]
This worked for me. It took me a bit longer to test because of one node from dev (https://dev-yalesites-platform.pantheonsite.io/welcome) that has a text block right at the top under the two buttons was not changing! All of the rest of them were. So, I halfway suspect it has something to do with that field getting partially set and so your code isn't touching that one block. But, this one (https://dev-yalesites-platform.pantheonsite.io/testing-all-of-the-things) worked great - all of the text blocks got updated there no problem.

**Comment by dblanken-yale** [comment]
@codechefmarc Thanks a lot for looking.  I'll check out that outlier to see what could be up.  I want to make sure we get them all.  So it still made you select the default?

**Comment by dblanken-yale** [comment]
It makes me think it's not targeting correctly.  I attempted to look for that UUID and I am not seeing it at all. hmmm

**Comment by dblanken-yale** [comment]
So strange.  It is set after the update; I found the block id (329) and was able to see it updated in `block_content__field_style_variation` referencing revision 620 in the db, which is referenced also in the `block_content` table.

If I manually set it in the page, it sticks.  Nothing changes, and the revision table is pointing to the same values!  So strange.

**Comment by dblanken-yale** [comment]
@codechefmarc Mind trying it one more time?  I think I finally got it right.  It should take even the case you found.  Let me know if it works for you.  So far it has for me locally as well as the site that reported this.

**Review by codechefmarc — APPROVED** [review]
Yup, that did it! I pulled down this branch locally, then ran `nom run build-with-assets` which grabbed the version from `dev` that had the non-set text variation and then it ran the update hook and now it's fixed locally. Approved!

**Pull request merged**
