### PR TITLE
YALB-1681 - Support light and dark admin themes

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Removes previous color overrides
- Preserves layout-builder pencil icon and position improvements
- Sets default theme setting to `Auto` from `Dark` to use user's system settings by default.

### Functional testing steps:
- [x] Login to the multidev: https://pr-524-yalesites-platform.pantheonsite.io
- [x] Confirm Gin is set to Auto color theme
Screenshot 2024-01-09 at 10 52 08 AM

- [x] Edit content from the frontend and from the backend
- [x] Verify the gin defaults for this color theme look good
- [x] Verify that, then logged in, the secondary toolbar is still stickied along with the admin toolbar when scrolling down the page (see video below for example). 
- [x] Verify that, when editing a layout builder block, the edit pencil icon is still left-aligned and large (see video below for example)

https://github.com/yalesites-org/yalesites-project/assets/366413/9823528d-338c-4325-a094-950575db1bae

---

- [x] Change the theme to use Dark mode (or Light if Dark is your system-set preference) instead of Auto
Screenshot 2024-01-09 at 10 52 00 AM

- [x] Edit content from the frontend and from the backend
- [x] Verify the gin defaults for this color theme look good

### CODE REVIEW

**Comment by miketullo95** [comment]
@joetower this is so exciting! capturing things that I found:

- [ ] could we get the 2nd toolbar background color to be the same as the top toolbar?
- [ ] missing thicker section outline
Screenshot 2024-01-09 at 3 14 05 PM
- [ ] field group heading background/text in dark mode contrast issue
Screenshot 2024-01-09 at 3 15 29 PM
- [ ] toggle active state not showing in dark mode
Screenshot 2024-01-09 at 3 26 33 PM
- [ ] icons (view block, footer settings, header settings) in both dark/light mode visually not showing properly
Screenshot 2024-01-09 at 3 17 35 PM
Screenshot 2024-01-09 at 3 25 39 PM
- [ ] linkit field background issue, both dark and light
Screenshot 2024-01-09 at 3 19 11 PM
- [ ] theme setting hover items - I think I prefer what the button theme does compared to the color palette. 
https://github.com/yalesites-org/yalesites-project/assets/98550395/d57e7f28-3b38-4c2b-8e71-86e12e5a0da5
- [ ] alternating background colors for quick links 
Screenshot 2024-01-09 at 3 28 58 PM

**Review by codechefmarc — CHANGES_REQUESTED** [review]
Looking really good overall! I've got a few places where there are issues:

Layout builder, when editing a block with WYSIWYG in sidebar in dark mode:
Screenshot 2024-01-10 at 12 19 31 PM

Text contrast issue when editing on regular node edit form, WYSIWYG in dark mode:
Screenshot 2024-01-10 at 12 24 23 PM

Image cropping text contrast after uploading a new image and entering the crop settings, in dark mode:
Screenshot 2024-01-10 at 12 27 01 PM

**Comment by dblanken-yale** [comment]
Screenshot 2024-01-10 at 3 37 02 PM

Think we'll need to target: `ul.chosen-results li.active-result` and `&.highlighted` for Chosen.  I feel as if the selection is ok?  Might need more feedback on that one.

Screenshot 2024-01-10 at 3 39 51 PM

**Comment by dblanken-yale** [comment]
Wow this is looking great.  Nice work @joetower

**Comment by sskalisky-4k** [comment]
A couple more for you, @joetower 

YALB-1681-theme-settings-still-dark-in-light-mode
Theme settings menu is still in Dark Mode when overall theme is set to Light Mode

YALB-1681-header-border-missing-focus-nav-light-mode
Mike already noted the light/dark Footer Settings borders, but the Focus Nav is missing an outline in Light Mode.

I'm sure our a11y experts will have more insight here, but it feels like we're juuuuuussssttt under AA contrast ratios in various spots, at least in the light theme. Things like the admin toolbar menu links are flagged for being 4.41 instead of 4.5:1, the dashboard links (blue on pale blue background) are at 4.25, etc. This might be caused by the accent color, which I cannot change while testing, as it requires a site administrator account.

**Comment by joetower** [comment]
@miketullo95 @dblanken-yale @codechefmarc @sskalisky-4k 

Thank you all for your feedback and testing. Could you all please give this another look? I _think_ I have addressed all of the feedback so far. 

There is one lingering issue with ckeditor that I'm working to resolve. In the meantime everything else can be tested.

**Comment by codechefmarc** [comment]
Hi Joe, looks like you fixed a few of the ones I reported, but there are still some issues:
Adding a new text block, in dark mode, the text contrast in the WYSIWYG is too light.

Screenshot 2024-01-16 at 11 14 00 AM

Also looks like the image crop one I posted above is still too dark to read the initial label.

**Comment by sskalisky-4k** [comment]
- When in Dark Mode, the "Add block" and "Add section" buttons/button text shift to lighter blues than in Light Mode, lowering the contrast. This can be seen in Mike's screenshot above, where he notes the borders around Sections are missing.
- Dark Mode: Block name links in the Block Picker are the same low-contrast (1.99) blue as above
- Dark Mode: Marc noted the Text Block contrast issue above, but I wanted to note that this happens in other Blocks/spots, like the Image Caption area of the Image Block, Callouts, and spots like character content length recommendations in these types of Blocks.

YALB-1681-dark-mode-light-text

- Also, FYI, for some of these, when editing an _existing_ Block (which swings out in the sidebar area), the text looks fine. E.g. new Text Block versus editing an existing Text Block. 
- Dark Mode: Hide/show Row Weights text is dark text on dark bg

**Comment by miketullo95** [comment]
@joetower here are my review notes 
- [ ] Section grey + thick outline missing
    Expected 
    Screenshot 2024-01-16 at 3 04 48 PM
    Testing
   Screenshot 2024-01-16 at 3 05 22 PM
- [ ] clicking edit on a block and going into "move" shows this panel with css issues
Screenshot 2024-01-16 at 3 06 26 PM
- [ ] navigation "parent link" drop down text color
Screenshot 2024-01-16 at 3 08 16 PM
- [ ] theme settings save button text color
Screenshot 2024-01-16 at 3 11 55 PM
- [ ] active state on header settings need to be more apparent. I like how the views tool does it (accent color as stroke and name of option). Off topic, do we want to redo these icons? making theme look more like the views block icons could be nice, as they look great on both light and dark mode. 
Screenshot 2024-01-16 at 3 13 38 PM
- [ ] Footer settings stroke/active state missing
Screenshot 2024-01-16 at 3 16 45 PM

**Comment by dblanken-yale** [comment]
@joetower Awesome.  I just saw that in the logs for the multidev; it might not be related to your work at all, but thought I'd point it out so we can be aware.  :D

**Comment by joetower** [comment]
@miketullo95 I think all of your last round of changes have been fixed. Could you please give them another look? 

Screenshot 2024-01-16 at 5 25 00 PM

Screenshot 2024-01-16 at 5 16 46 PM

Screenshot 2024-01-16 at 5 16 32 PM

---

@sskalisky-4k Your last items should also be fixed.  The light blue shifts because the gin theme changes the light-blue accent color value based on light/dark theme. It lightens it because it expects it to only be used on a dark background. Layout-builder is the issue here because we're using the gin variables on top of our white background site. I updated the text color in these button instances only. 

Screenshot 2024-01-16 at 4 23 28 PM

A similar issue was the cause for these labels, too. The easiest solution was to change the label background color and let the light-blue be itself. 

Screenshot 2024-01-16 at 4 23 23 PM

For this note: 
> Dark Mode: Marc noted the Text Block contrast issue above, but I wanted to note that this happens in other Blocks/spots, like the Image Caption area of the Image Block, Callouts, and spots like character content length recommendations in these types of Blocks.

Can you let me know if this is still an issue? If so, can you point me to a URL example? I'm having a hard time assessing where this scenario is presenting itself, based on your screenshot. 👍

**Comment by joetower** [comment]
@codechefmarc I missed the image crop one, apologies! 

This should be fixed now: 


https://github.com/yalesites-org/yalesites-project/assets/366413/f5f25dc0-d244-4edb-a62e-452e06170128

**Comment by sskalisky-4k** [comment]
<p>@joetower Sorry about the confusion, but in good news, I can confirm that the character count limits in the various Blocks now look great in Dark Mode!</p>

<p>On my end, I still see the Hide/Show Row Weights in Tabs, Accordions, Cards, etc., as dark on dark text.</p>

YALB-1681-dark-mode-hide-show

**Comment by joetower** [comment]
@sskalisky-4k Awesome, thank you! That should now be resolved if you could please take another look. 

Screenshot 2024-01-17 at 10 08 18 AM

**Comment by sskalisky-4k** [comment]
@joetower Row weights links are now visible!

**Review by kara-franco — CHANGES_REQUESTED** [review]
Absolutely beautiful work, it's so impressive! The look and feel is so much simpler and the code is simpler too, wee. 

I'm noting just a few contrast issues, should be quick tweaks 🤞

- [x] Views tag dropdown tag option text needs to be darker 
Screenshot 2024-01-18 at 6 53 42 PM

- [x] Anchor link in WYSIWYG needs to have the light blue link treatment.
Screenshot 2024-01-18 at 6 51 36 PM

- [x] Apply to selected items button needs to lighten. 
Screenshot 2024-01-18 at 6 49 15 PM

- [x] Configure link needs to be darkened on hover. 
Screenshot 2024-01-18 at 6 47 05 PM

**Comment by sskalisky-4k** [comment]
<p>A non-urgent other tiny find: when viewing Source in Dark Mode it still presents text on a light background.</p>
YALB-1681-source-background-color
<p>Also, FYI, in case any of the settings carry over, as a Site administrator, I ran into the issue again where I was unable to attach media in a Block. Last time it was just the Spotlight, in this sandbox it is any Block with media.</p>
<p>Amazing job chasing down all the little outliers, @joetower!</p>

**Comment by joetower** [comment]
@kara-franco Thank you! This should be ready for a retest. 

You should see the following: 
Screenshot 2024-01-23 at 3 25 09 PM

Screenshot 2024-01-23 at 3 25 25 PM

Screenshot 2024-01-23 at 4 21 18 PM

https://github.com/yalesites-org/yalesites-project/assets/366413/6ef19043-8240-448a-a740-2005c2d5b7ff

**Comment by joetower** [comment]
@sskalisky-4k Thank you! 

I'm not sure I want to touch this, unless there are strong opinions on overriding what ckeditor is doing for the source code background and color. I actually think it may be easier to visually differentiate the source code from the content entry modes. And I'm not seeing contrast issues. Do you have strong opinions about it matching?

**Comment by sskalisky-4k** [comment]
@joetower I think it's totally fine if the source code doesn't change, only mentioned it for completionists' sake in case there was an intention to swap there as well!

**Comment by joetower** [comment]
@miketullo95 Good catch! That should be fixed now. 

Please take another look. 
Screenshot 2024-01-24 at 2 59 08 PM


---

Also, I made a global change to ckeditor. The editor will now always have a white background with black text regardless of light/dark theme. This was changed because there was an inline style injected somewhere by ckeditor which made some text black. This issue was difficult to track down and resolve, so it's probably in our best interest to set a standard for ckeditor's background regardless of theme. You should now see this: 


Screenshot 2024-01-24 at 3 10 39 PM

 
Screenshot 2024-01-24 at 3 13 46 PM

Could I please get a few set of eyes on testing these changes? @sskalisky-4k or @codechefmarc ?

**Comment by miketullo95** [comment]
@joetower could we get the wysiwyg extend the length of the sidebar config screen? This happens on current sandboxes now
Screenshot 2024-01-25 at 9 36 01 AM

**Comment by joetower** [comment]
@miketullo95 This is ready for another look 
Screenshot 2024-01-25 at 6 10 51 PM

**Review by codechefmarc — APPROVED** [review]
@joetower - To the specific changes you wanted me to test, the CKEditor background color, all tests passed for me. I tested modal, sidebar, and node edit form and all worked well with light and dark modes with the background staying white and text staying dark. I didn't test any other admin theme changes, but if you want me to, let me know. Thanks!

**Review by nJim — APPROVED** [review]

**Review by dblanken-yale — APPROVED** [review]
-1,128 lines: such a lovely thing to see.  Nice work!  It is looking great!

**Pull request merged**
