### PR TITLE
YSP-335: New block: In-Line Message

### PR DESCRIPTION
**Pull request by joetower**
## [YSP-335: New block: In-Line Message](https://yaleits.atlassian.net/browse/YSP-335)
Description of work

- Adds new component for In-Line Message
- Wires new in-line message component

### Functional testing steps:
- [ ] Navigate to: https://pr-680-yalesites-platform.pantheonsite.io/marcs-testing-page
- [ ] Verify you see two in-line message at the top of the page
- [ ] Login and experiment with setting different global themes and in-line message component theme combinations

https://github.com/yalesites-org/yalesites-project/assets/366413/6ecbffbf-5b6f-4f7b-90f0-f45dc891efa2

### CODE REVIEW

**Review by miketullo95 — APPROVED** [review]
This looks great!

**Review by codechefmarc — COMMENTED** [review]
This looks great for the regular Drupal block! I did some testing for how it will be used for the conference page alert on events that are conferences from Localist. Here is my result:

Screenshot 2024-06-27 at 5 04 17 PM

And the code:

```
{% include "@molecules/inline-message/yds-inline-message.twig" with {
     inline_message__id: 'event-' ~ nid,
     inline_message__type: 'general',
     inline_message__content: 'This is a part of a Conference <a href="' ~ localist_url ~ '">Visit conference page</a>',
     inline_message__theme: 'one'
  } %}
```
The other alert had a field for a link and it was placed on the far right (probably flex?) so I was curious if we wanted to support that or just keep it this way and we can do inline links if necessary?

**Comment by joetower** [comment]
@dblanken-yale Ah, I matched the design which has the icon top-aligned with the first line of text - whether that's a heading or text. We could vertically center it, instead, if there is a heading and text entered. 🤔

**Comment by joetower** [comment]
@codechefmarc We could add a link. I originally modeled this component off the alert and kept a link in place, but then thought that since the design didn't showcase a link, perhaps these in-line messages shouldn't have them 🤔 .

**Comment by codechefmarc** [comment]
> @codechefmarc We could add a link. I originally modeled this component off the alert and kept a link in place, but then thought that since the design didn't showcase a link, perhaps these in-line messages shouldn't have them 🤔 .

Yup - for the conference thing, we'll need a link there, perhaps throw it to the group on Teams and see what others think? I'm fine either way.

**Comment by joetower** [comment]
@codechefmarc Added optional link here: https://pr-680-yalesites-platform.pantheonsite.io/marcs-testing-page

**Comment by codechefmarc** [comment]
Love it! That works for me. Once this is all merged in on the Component Library side, let me know and I'll quickly add this new component to the Localist conference PR. Thanks!

**Pull request merged**
