### PR TITLE
Release v1.6.0

### PR DESCRIPTION
**Pull request by yalesites**
## Pull requests
- https://github.com/yalesites-org/yalesites-project/pull/722
- https://github.com/yalesites-org/yalesites-project/pull/730
- https://github.com/yalesites-org/yalesites-project/pull/731
- https://github.com/yalesites-org/yalesites-project/pull/739
- https://github.com/yalesites-org/yalesites-project/pull/740

### CODE REVIEW

**Comment by yalesites** [comment]
Environments ready for review:
- https://v160-ys-unitedway-yale-edu.pantheonsite.io
- https://v160-ys-campushealth-yale-edu.pantheonsite.io
- https://v160-yalesites-sebastianna.pantheonsite.io
- https://v160-yalesites-mv482.pantheonsite.io
- https://v160-ys-visitorcenter-yale-edu.pantheonsite.io
- https://v160-yalesites-platform.pantheonsite.io
- https://v160-yalesites-yale-edu.pantheonsite.io

**Comment by dblanken-yale** [comment]
AI Chat bot test here: https://v160-yalesites-yale-edu.pantheonsite.io/askyale-test

**Comment by dblanken-yale** [comment]
Testing:
- [ ] AI chat bot images have changed
- [ ] Pull Quote is now a soft limit on quote content

**Pull request merged**
