### PR TITLE
Testing Only - Do Not Merge - YALB-1325: Bug: Accessibility issues with Search

### PR DESCRIPTION
**Pull request by codechefmarc**
### Description of work
- Ensures unique ID's for all search form elements for accessibility
- Note: This PR is for testing only with the multidev, do not merge.
- Actual work is located in [Component Library PR-258](https://github.com/yalesites-org/component-library-twig/pull/258)

### Functional testing steps:
- [ ] Test the multidev with SiteImprove and verify that the search form no longer contains duplicate IDs
- [ ] Inspect the DOM and search for the following ID's and verify that the ID's are now unique (with `-desktop` and `-mobile` suffixes to the ID's)
     - [ ] `#header-search-form`
     - [ ] `#edit-keywords--header-search-form`
     - [ ] `#edit-submit-search--header-search-form`
     - [ ] `#edit-actions--header-search-form`

### CODE REVIEW

**Comment by kara-franco** [comment]
Excellent! The duplicate ID issue is resolved. There is still an empty label on the search that we need to clear up (for the both the -mobile and -desktop labels). 
Screenshot 2023-06-28 at 8 30 22 AM
We can either but a visually hidden `<span>` in the label or use a `<title>` element on the SVG and remove the aria-hidden (whichever is easier!).

**Comment by codechefmarc** [comment]
@kara-franco - OK, I added a visually hidden span inside the label, let me know if that works: https://pr-326-yalesites-platform.pantheonsite.io/

Thanks!

**Comment by kara-franco** [comment]
Perfect! All good and a11y approved!

**Comment by codechefmarc** [comment]
Closing without merging - work was completed in component library.

**Pull request closed without merging**
