### PR TITLE
YALB-837: Add instructions to paragraph forms

### PR DESCRIPTION
**Pull request by nJim**
### Description of work
- Add instructions to paragraphs using the 'description' field
- Uses a form alter hook to print this text on the top of the paragraph form

### Functional testing steps:
- [ ] [Login to the multidev with CAS](https://pr-193-yalesites-platform.pantheonsite.io/)
- [ ] [Create a page](https://pr-193-yalesites-platform.pantheonsite.io/node/add/page)
- [ ] Add some paragraphs and verify that the instructions appear at the top of the paragraph form.
  - [ ] Text is an example of a simple for with instructions
  - [ ] Wrapped Image is an example of a form with field groups and instructions above them
  - [ ] Webform is an example with out instructions (yet)
- [ ] Safe the page and verify that these instructions do not appear on the content itself. They only display when editing the paragraph.
Screen Shot 2023-01-12 at 10 56 55 AM

### CODE REVIEW

**Comment by miketullo95** [comment]
- [ ] Could we move the section description to the top like other components?

Other than that, every paragraph instruction looks great!

**Review by marcb4k — APPROVED** [review]
Code looks good to me - Mike pointed out the "Section" help text shows at the bottom, not at the top, but other than that, code is approved.

**Comment by nJim** [comment]
@miketullo95 Got it. It's a funny game we play in drupal using the 'weight' field. Heaviest weights fall to the bottom and lightest float to the top. I set the instructions at -100 to put them at the top, but Layout Paragraphs had their widget at -200. So now our instructions are at -300 so they win.

It's a silly approach, but it's a pretty unbeatable pattern when trying to get unrelated code from different authors to play together. I think this hits the mark now.
Screen Shot 2023-01-13 at 10 36 23 AM

**Review by miketullo95 — APPROVED** [review]
Woohoo! looks great 👍

**Pull request merged**
