### PR TITLE
Update develop from master

### PR DESCRIPTION
**Pull request by vinmassaro**
### Description of work
- `master` has seen a number of hotfixes applied to it that have not been applied to `develop`. This PR will bring the branches in sync.

### CODE REVIEW

**Review by dblanken-yale — APPROVED** [review]
Those changes look good and I was able to test both views and the breadcrumb search and all is working as intended.  I'm going to let @codechefmarc review as well since I know he had quite a hand in the views in case I missed anything, but I think this is ready and will be ready to add the view fix once it's merged.

@codechefmarc Feel free to use my test Page to look at the views.  I already set some Posts up with tags that are being included/excluded.  (Business [excluded] and Arts & Humanities [included])

**Comment by dblanken-yale** [comment]
Added @nJim so he will know when this goes through.  He was having some issues with a release candidate, and I thought this going through might help him out.

@vinmassaro Mind if I resolve the conflict with ViewsBasicManager since it was my PR that caused it?  :D

**Comment by dblanken-yale** [comment]
Resolved the conflict on ViewsBasicManager.php.  That should be good to go. (above)

**Comment by dblanken-yale** [comment]
Also, not sure if @codechefmarc is going to update his review, but in stand up he said he tested it and approved.  I know he's been busy with profiles, so wanted to let you know here.

**Review by codechefmarc — APPROVED** [review]
Approved - essentially knowing that the `ViewsBasicManager` will get updated with @dblanken-yale later PR to do the `is_array` check, I'm good with this.

**Comment by dblanken-yale** [comment]
Yep that merge conflict was that merge for `ViewsBasicManager`, so it should be good to go!

**Pull request merged**
