### PR TITLE
YSP-490, 501, 502, 503, 514: Add Tiles, Facts and Figures, Quote Callout, and Link Grid Blocks

### PR DESCRIPTION
**Pull request by nJim**
### Description of work
- Defines new block types for the layout builder: Tiles, Facts and Figures, Quote Callout, and List Grid.
- Includes fields, paragraphs, and settings [defined in the data model](https://yaleedu.sharepoint.com/:x:/r/sites/YaleSitesUpgradeProgram/_layouts/15/Doc.aspx?sourcedoc=%7B2B574C06-BAC3-41E2-924A-F4562054F849%7D&file=Proposed%20Content%20Model.xlsx&action=default&mobileredirect=true&wdOrigin=TEAMS-ELECTRON.teams.files&wdExp=TEAMS-CONTROL&wdhostclicktime=1644421397192) for these blocks: 
- Wires the Tiles component in Drupal, adds `center` option
- Wires the Quote Callout component in Drupal, renames the component from Standalone Quote
- Wires the Facts and Figures component in Drupal, adds column options
- Wires the Link Grid component in Drupal
- Atomic: https://github.com/yalesites-org/atomic/pull/232
- Component Library: https://github.com/yalesites-org/component-library-twig/pull/363

### Functional Review Steps
- [x] Navigate to the [New Component test page](https://pr-638-yalesites-platform.pantheonsite.io/new-components-page)

- [x] Note: I added these new components to our JS file which detects matching selector next to one another and only applies margin to the first and last item in a group of consecutive matching selectors. Because these components are all full-width components, if placed after one another, their margins should probably collapse. If anyone feels this shouldn't be the behavior let's discuss. I made my best guess over how consecutive instances should render.

https://github.com/yalesites-org/yalesites-project/assets/366413/1bf769e4-89ec-475b-847d-9e8e68683794

---
 
- [x] Review the Tiles component - the first component on the page after intro text
- [x] Verify it renders as it should - compared to the component in Storybook
- [x] Login and add a new title item, experiment with the dial options
- [x] Add another instance of a Tiles component and place it on the page

---

- [x] Review the Quote Callout component - the next component after Tiles
- [ ] Verify it renders as it should - compared to the component in Storybook
- [x] Edit the component and experiment with the dial options
- [x] Add another instance of a Quote Callout and place it on the page

---

- [x] Review the Facts and Figures component - next one after the three quote callouts
- [x] Verify it renders as it should - compared to the component in Storybook
- [x] Edit the component and experiment with the dial options

---

- [x] Review the Link Grid component - the next component after Facts and Figures
- [x] Verify it renders as it should - compared to the component in Storybook
- [x] Edit the component and experiment with the dial options

---
- [x] Note the last Quote Callout on the page is separate from the other group of new components. It gets the `first-and-last` position data-attribute value, which gives it top and bottom margin.

### CODE REVIEW

**Review by codechefmarc — CHANGES_REQUESTED** [review]
Some changes and questions, but overall it looks really good!

1. When editing the tile component, there is a "TBD" I assume for eventual help text?

Screenshot 2024-05-14 at 5 20 21 PM

2. When adding a tile that has longer than 120 characters, it spills over the tile. Perhaps we need to adjust to put a hard limit on that field. Or cut it off via theming? Or scroll?

Screenshot 2024-05-14 at 5 23 42 PM

On Tablet:

Screenshot 2024-05-14 at 5 45 16 PM


3. There is no Quote Callout or Facts and Figures preview images when adding a new one via Layout Builder. I seem to recall that Mike T. possibly saying he is working on those?

Screenshot 2024-05-14 at 5 35 00 PM

4. I don't see an option in Drupal to turn on/off the icon for the facts and figures as is shown in Storybook.

**Comment by miketullo95** [comment]
@nJim I just noticed the quote callout style is not showing up (`bar`, `quote`)
Screenshot 2024-05-28 at 3 42 04 PM
Screenshot 2024-05-28 at 3 42 34 PM

**Comment by miketullo95** [comment]
Putting notes in from our University Printer meeting earlier today:

**Link Grid**
- Add an optional title field, similar to custom cards or accordions
- Add the optional heading for each column as shown in storybook (https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/molecules-link-group--link-group&args=heading:Test+Hello) 

**Quote Callout**

- this may be more relevant to the component repo (i will crosspost), but could bump up the size of the image

**Comment by joetower** [comment]
@miketullo95 I pushed some updates: 

- Added the SVGs and descriptions to all the new components
- Increased the Quote Callout image to a max-width of `248px` instead of `224px`. Is that enough of an increase? https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/molecules-quotes-quote-callout--quote-callout&args=quoteImage:with-image

Oh and I forgot to mention it before, but the Link Grid is this component: https://deploy-preview-363--dev-component-library-twig.netlify.app/?path=/story/molecules-link-grid--link-grid and not the Link Group component you linked.

The Link Group component is only used for the footer menu links.

**Comment by miketullo95** [comment]
@joetower this looks great! i actually made some changes based off the quote callout info which is super helpful. If you could replace the picker SVG that would be awesome. 

Quote Callout

my only other question before approving would be the ability to add an optional component title field to link grid (similar to accordions). The university printer gave feedback that it may be nice to have the ability to give heading context to a large amount of links. And doing that without adding a text block above it with just a header would be convenient.

**Comment by joetower** [comment]
@miketullo95 I updated the quote callout SVG and added an optional heading field to the Link Grid component. 

Screenshot 2024-06-03 at 11 59 58

Screenshot 2024-06-03 at 11 58 57

**Review by miketullo95 — APPROVED** [review]
This is great! thank you @joetower 😄

**Comment by joetower** [comment]
@codechefmarc I pushed a fix to remove the aspect-ratios from all the tile-items. Now, each tile-item can grow with its content, but the entire row of items will have the same height, visually speaking. 

This should be ready for you to give it another look 👍

**Comment by joetower** [comment]
@codechefmarc Thank you! 

Yes, that's correct about the Icons. We aren't implementing them, yet. It will come at a later date.

**Pull request merged**
