### PR TITLE
JAKALA: Secondary Link for Spotlight blocks

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Description of work
- Adds support for adding an optional Secondary Link to Spotlight components.

### Functional testing steps:
- [ ] Create a new Page node
- [ ] Add a "Spotlight - Landscape" block on the "Edit Layout and Content" screen.
- [ ] Note that there is now an additional fieldset labeled "Secondary Link" on the block's edit form. 
- [ ] Fill out the fields for both the Primary Link and Secondary Link, as well as any required fields. 
- [ ] Repeat these testing steps for "Spotlight - Portrait"

### Related Pull Requests
- https://github.com/yalesites-org/component-library-twig/pull/411

### CODE REVIEW

**Comment by nplowman** [comment]
We sent this back to our dev team for some style fixes. We'll provide an update here when this is ready for a second review.

**Comment by nplowman** [comment]
@dblanken-yale @kara-franco We made some adjustments to the styling issues Kara reported on the link placement, when there are two links. (We are now placing them stacked in close proximity, rather than having the second link at the bottom of the card.)
If you are happy with how the new styling looks, I think we can consider this PR ready for final review and merging. 
Screenshot 2024-08-29 at 9 47 05 AM

**Comment by dblanken-yale** [comment]
I think this looks great!  @kara-franco or @atiddei, if you both still agree, do you mind giving it an approval and we can get this into develop?

**Review by kara-franco — APPROVED** [review]

**Pull request merged**
