### PR TITLE
YSP-436: Reference cards: Backend and content tools

### PR DESCRIPTION
**Pull request by laura-johnson**
## [YSP-436: Reference cards: Backend and content tools](https://yaleits.atlassian.net/browse/YSP-436)

**Relates to**

### Description of work
- Adds the BE of the Reference card component
- Includes a Single view mode as well as a block type and fields as per the [data model](https://yaleedu.sharepoint.com/:x:/r/sites/YaleSitesUpgradeProgram/_layouts/15/Doc.aspx?sourcedoc=%7B2B574C06-BAC3-41E2-924A-F4562054F849%7D&file=Proposed%20Content%20Model.xlsx&action=default&mobileredirect=true&wdOrigin=TEAMS-ELECTRON.teams.files&wdExp=TEAMS-CONTROL&wdhostclicktime=1644421397192)
- There is a related [Atomic PR](https://github.com/yalesites-org/atomic/pull/217) that contains the templates that connect it to the FE component

### Functional testing steps:
- [x] In any of the content types, add a block of type Reference Card. 
- [x] Verify you can select a Post, Event, or Profile
- [x] Verify that for any of the above types, you can select either Featured or Non-Featured styles
- [x] Verify that the designs match what we have in [Figma](https://www.figma.com/file/4Lx9A5sxO08DxUNbewalrR/Yale-Sites---ideation?type=design&node-id=1092-2&mode=design&t=Ke63eZgOMJYErxfX-0)

### CODE REVIEW

**Comment by laura-johnson** [comment]
@miketullo95 I need a graphic for the layout builder browser for this block. Can you provide one? Details [here](https://yaleits.atlassian.net/browse/YSP-436).

**Comment by miketullo95** [comment]
@laura-johnson here is the svg for the reference card icon 
Reference Card

**Comment by laura-johnson** [comment]
Thanks @miketullo95 !

**Comment by dblanken-yale** [comment]
This is looking great.  I did notice something I didn't see on the front end ticket, so I thought I'd point it out here, but looks like we may have a heading jump that Editoria11y is detecting.

I wonder if we can somehow utilize @joetower 's [ticket](https://github.com/yalesites-org/yalesites-project/pull/620) to use the `page-title-hidden` attribute to help determine the heading level?  What do you think, Joe?

Screenshot 2024-04-05 at 3 20 42 PM

Other than that, it is great!

**Comment by dblanken-yale** [comment]
@miketullo95 and I did find one small issue--it looks like the content reference isn't set up to allow Pages to be referenced.

8fc6cff3-4219-4e88-a6cd-bb5d82b8cbd5

**Comment by miketullo95** [comment]
@laura-johnson I was also wondering if the content field could utilize the linkit module (similar to how our button block URL field works). It gives a little more context to what the user is selecting in that field 

Also, could we add some help text under the content field? 
"Start typing to find content and select a suggestion."

**Comment by laura-johnson** [comment]
@dblanken-yale The requirements currently for this say that it should only reference Event, Post, or Profile...

@miketullo95 I haven't used Linkit to make an entity reference. I'll check and see if that's possible (I believe with File it outputs a URL to the file).

**Review by nJim — APPROVED** [review]

**Comment by nJim** [comment]
Approved via Teams.

**Pull request merged**
