### PR TITLE
YALB-1197: Media: Allow embed of SoundCloud content (BE)

### PR DESCRIPTION
**Pull request by dblanken-yale**
## [YALB-1197: Media: Allow embed of SoundCloud content (BE)](https://yaleits.atlassian.net/browse/YALB-1197)

To be tested in tandem with [Atomic PR 131](https://github.com/yalesites-org/atomic/pull/131)

### Description of work
- Add new EmbedSource for SoundCloud
- Add static variables to detect iframe patterns for SoundCloud content
- Add a SoundCloud png file to help users see that the embed is a SoundCloud one

### Functional testing steps:
- [x] Visit a page
- [x] Click `Layout Builder`
- [x] Scroll toward the bottom and click `Add Block`
- [x] Find the `Embed` block and click it
- [x] Create an administrative label for it
- [x] Click `Add media`
- [x] Click `Learn about supported formats and options`
- [x] Follow the directions there to then visit SoundCloud in a separate browser to verify the instructions can be followed (or use the example by copying and pasting it after expanding)
- [x] Exit the modal by clicking the `X` in the upper right corner
- [x] In the `Embed Code or URL` text area, paste the embed code you copied
- [x] Click `Add`
- [ ] Verify you see a SoundCloud image appear
- [x] Add a unique title
- [x] Click `Save`
- [x] Click `Insert selected` toward the bottom of the page
- [x] Click `Add block`
- [x] Click `Save`
- [x] Scroll down to the SoundCloud resource that should show on the page
- [x] Click on it to start the sound byte
- [x] Verify you can hear the audio
- [x] Click it again to pause

### CODE REVIEW

**Comment by dblanken-yale** [comment]
Thanks for changing that; I wasn't sure which was ok to take.  I did notice on the PR site that the logo isn't showing when going in to edit.  Did I do something incorrect there?

**Comment by dblanken-yale** [comment]
@nJim Since I thought you had said you were going to talk about embed size, I added on to @kara-franco 's [page](https://pr-269-yalesites-platform.pantheonsite.io/my-new-page) to show the alternate embed option that it looked like SoundCloud had as well.

**Review by codechefmarc — CHANGES_REQUESTED** [review]
Tested this one out locally so I could get the develop branch of the component library. It all works great except I'm not seeing the Soundcloud logo show up, see screenshot. I tried on Pantheon multidev and locally and the logo doesn't appear.

Screenshot 2023-06-12 at 1 50 49 PM

**Comment by dblanken-yale** [comment]
Hmmm, maybe my understanding of how those files get copied is flawed.  I placed the file into what looked like [the icons directory](https://github.com/yalesites-org/yalesites-project/tree/YALB-1197-media-allow-embed-of-soundcloud-content-be/web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons) in the hopes that the [ys_embed.install](https://github.com/yalesites-org/yalesites-project/blob/YALB-1197-media-allow-embed-of-soundcloud-content-be/web/profiles/custom/yalesites_profile/modules/custom/ys_embed/ys_embed.install) would copy them to the media-icons/generic folder as it looks like it's doing with the rest of the images.

Let me look into it more and do a fresh install locally to verify what's happening.

**Comment by dblanken-yale** [comment]
@codechefmarc Ya, starting with a fresh install and `npm run setup` copied the file and it displayed correctly locally.  I wonder if it might not be running the install for the module on PR updates as I made the PR well before the image was present.  When you tested locally was it a fresh setup or did you switch branches and do a build-with-install?

**Comment by codechefmarc** [comment]
@dblanken-yale - OK, I did a clean install from `npm run setup` and that worked great - I'm able to see the icon showing up now.

**Comment by dblanken-yale** [comment]
@codechefmarc @nJim Do either of you mind taking a look at the update hook?  I was able to run it locally successfully, but wanted to make sure I did it right.  I used the above install as a reference, so hope it's ok.

Will it run the update hook in the PR update?  Or do I need to run a drush command to have it try?

[feat(YALB-1197): add update hook to copy png](https://github.com/yalesites-org/yalesites-project/pull/269/commits/0d30f0efc8ea6cdde36d0c79b8663a5a2cac2a70)

**Comment by dblanken-yale** [comment]
That didn't look to work either.  My hope was that `public://media-icons/generic` would resolve to the right place, but it doesn't look like it is.  I'll give using the full path I see a try tomorrow: `public://styles/media_library/public/media-icons/generic` in the hopes it resolves to copy.

**Review by codechefmarc — APPROVED** [review]
Just tested this locally and all worked great with that update hook. Great job! Approved!

**Review by nJim — APPROVED** [review]
Ship it.

**Pull request merged**
