### PR TITLE
JAKALA: Spotlight cards enhancement

### PR DESCRIPTION
**Pull request by marjina-constantin**
## JAKALA: Spotlight cards enhancement

Previously, "Spotlight Cards" supported only one Call-to-Action (CTA) link. This pull request enhances the functionality by allowing a second CTA link to be added and rendered on the cards.

### Description of work
- Adds "Secondary Link" field to **Spotlight - Portrait** and **Spotlight - Landscape** blocks

### Functional testing steps:
- [ ]  Add **Spotlight - Portrait** or **Spotlight - Landscape** block to a page
- [ ] Populate the "Secondary Link" field
- [ ] Make sure that the new field is rendered and follows the existing site design.

Related PRs:
- https://github.com/yalesites-org/atomic/pull/257
- https://github.com/yalesites-org/component-library-twig/pull/396

### CODE REVIEW

**Comment by vinmassaro** [comment]
@marjina-constantin thanks, that got things a little closer but it turns out forked repos don't have access to secrets when using the Github Actions pull_request trigger. I've merged another PR to switch to pull_request_target trigger, so can you try closing and updating, and reopening one more time? Thanks for your patience as we work through this.

**Comment by nplowman** [comment]
@vinmassaro We just merged in the latest changes from develop, and the build steps seem to be completing now. 
I'm not seeing the link to the Pantheon multidev getting posted to the PR comments like I see with other pull requests. 
But I think we're getting closer?

**Comment by vinmassaro** [comment]
@nplowman it looks like it did create a multidev here: pr-729-yalesites-platform.pantheonsite.io/

The comment failed because the CI changes we made were attempting to post it to your repo. Will have to look further into that.

**Comment by nplowman** [comment]
@vinmassaro It seems like the URLs for the multidev environments have a predictable pattern that includes the PR number, so as long as the multidev environment is still getting provisioned, I don't think that is an immediate blocker. We should be able to figure out the URL without the link.

**Comment by nplowman** [comment]
I'm going to close this pull request in favor of #736

**Pull request closed without merging**
