### PR TITLE
YALB-1257: Bug: Admin menu link color | YALB-1263 - Layout Builder spacing between components

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Applies css to fix the admin menu label z-index issue

#### Testing:  [YALB-1257: Bug: Admin menu link color](https://yaleits.atlassian.net/browse/YALB-1257) 
- [x] Login and navigate to an admin page like https://pr-294-yalesites-platform.pantheonsite.io/admin/yalesites
  - [x] Verify the icons and nav label render properly with the background color _behind_ both elements
- [x] Navigate to a frontend admin edit page, like /components or https://pr-294-yalesites-platform.pantheonsite.io/standard-page-one
  - [x] Verify the icons and nav label render properly with the background color _behind_ both elements

https://github.com/yalesites-org/yalesites-project/assets/366413/912e88b0-d8f1-4af9-8663-adeeaa0b6d36

- [ ] Browse other admin pages and make sure the expanded menu items always have a visible label
---

#### Testing: [YALB-1263 - Layout Builder spacing between components](https://yaleits.atlassian.net/browse/YALB-1263)
- [x] Visit: https://pr-294-yalesites-platform.pantheonsite.io/components
- [x] Verify there is no space between the header and the CTA Banner

 Screenshot-20230601152713-2468x1233
 
 - [x] Scroll all the way to the bottom and verify the bottom callouts have no space between them and the footer
 
Screenshot-20230601153649-2394x889

- [ ] As you scroll down the page, note that the following components have a larger amount of space between it and the component above and below it (when not the first or last component on the page). These include the following components: 
- CTA banner & Grand Hero
- Callouts
- Quick Links

- Note: when we create the Quote Spotlight component, these same rules need to apply.

https://github.com/yalesites-org/yalesites-project/assets/366413/7a5e7b39-b8c5-4342-b213-e91debea5b0a

---
- [x] Visit: https://pr-294-yalesites-platform.pantheonsite.io/top-goal-site
- [x] Verify there is no space between the header and the grand hero at the top 
- [x] Verify there is no space between the bottom quick links and the footer 

Screenshot-20230601171000-2443x1287

Screenshot-20230601171005-1525x1089
---
- [x] Visit: https://pr-294-yalesites-platform.pantheonsite.io/standard-page-one
- [x] Verify the banner at the top has no space between it and the header
- [x] Verify the banner at the bottom has no space between it and the footer.

### CODE REVIEW

**Review by codechefmarc — APPROVED** [review]
Works great! Approved!

**Comment by ahitson** [comment]
Spacing under banners looks good when they are the first on the page. BUT! There is a current bug where things are too far from the headers (breadcrumbs and H1s getting pushed down), so I want to make sure we don't lose that when we fix the other item.

It looks like The Callouts and Banners could use more spacing from the surrounding (non-footer) content when they are in the center or at the bottom of the page.

**Comment by joetower** [comment]
@ahitson This is ready for you to take another look, please. 

If you look at https://pr-294-yalesites-platform.pantheonsite.io/components

Note that the new spacing rules, which I've named `--spacing-component-banner`, apply to: 
- Callouts
- Banners
- Quick Links

We _will_ apply it to Quote Spotlight when we create the component. 

Please take a look, thanks!

**Comment by joetower** [comment]
@codechefmarc When you have time, could you please give this new branch PR a look? https://github.com/yalesites-org/component-library-twig/pull/255. Please review it here (I added the new testing criteria to the PR) and look at the code in the component-library-twig.  

Based on Ashley's feedback, I made some changes in the component library repository, which necessitated creating a new branch and getting it in this Pantheon build. 

Thank you!

**Comment by ahitson** [comment]
This looks good!

**Comment by ahitson** [comment]
- Header has spacing issues, mentioned [in this ticket](https://yaleits.atlassian.net/browse/YALB-1220?atlOrigin=eyJpIjoiNjZlMjlhNjM1ZDk0NDJkYTg0MTQzYzNmOGE4ZTUxMWUiLCJwIjoiaiJ9)
- Did we lose the huge footer spacing for other elements? This is also another [ticket in the backlog](https://yaleits.atlassian.net/browse/YALB-1217?atlOrigin=eyJpIjoiNTk1YWZlNzAyMDkyNDljZTk1ZjMxMmU5YmUzMDA0ZjciLCJwIjoiaiJ9), but I have a memory of addressing this once already. Should be the largest spacing available, possibly more.
- Is there a way to have 2 text blocks stacked together have the same spacing as 2 paragraphs within the same text block?

Screen Shot 2023-06-23 at 12 10 49 PM

**Comment by joetower** [comment]
@ahitson Thank you!

I pushed up a fix: 
- The footer should now have space between it and non-banner-like components. 
https://pr-294-yalesites-platform.pantheonsite.io/jims-test-page
Screenshot-20230623152320-1415x1015



---

For this item: 
> Is there a way to have 2 text blocks stacked together have the same spacing as 2 paragraphs within the same text block?

We have logic for this in the design system, but I need to give this some more thought as to how to apply the same solution to the layout builder implementation in Drupal. Layout builder added several extra divs around each component, which is why the spacing rules aren't applying as they do in Storybook. 

Are you okay with addressing this in a separate ticket? 

---

Please take a look at the footer and let me know if you approve of where this ticket is at right now.  Thank you for noting the separate bug ticket for the header spacing :+1: , that will be a great ticket to work on after this one. 

Thank you!

**Comment by joetower** [comment]
@codechefmarc Yes, that is what I meant by "themes", sorry, I should have stated "global and component color themes". Thank you!

**Comment by ahitson** [comment]
The spacing before the footer looks good on the text page, but it looks like it's back between the CTA and the footer - https://pr-294-yalesites-platform.pantheonsite.io/components

**Comment by joetower** [comment]
@ahitson Ah, can you give the page a refresh, please? 

It should be fixed now. For some reason, this page had more than one `layout-onecol` entry (code that wraps all components entered on the page - I wasn't aware more than one could be added), and it wasn't picking up the `bottom-margin: 0`. Anyway, this should be fixed now. 

https://pr-294-yalesites-platform.pantheonsite.io/components

Also, great news :partying_face:  :cake: :balloon: :birthday: 

Marc and I met and were able to resolve this issue, which I thought we may need to address later: 

> Is there a way to have 2 text blocks stacked together have the same spacing as 2 paragraphs within the same text block?

If you give the site a re-test, the previous spacing should now be gone. It behaves the exact same as it does in Storybook. 

https://pr-294-yalesites-platform.pantheonsite.io/jims-test-page

**Comment by joetower** [comment]
@ahitson apologies, can you please hold off testing this until I message you again?

I need to do some more testing. I'll add a follow up comment when this is actually ready.

**Comment by joetower** [comment]
@ahitson This is now ready for you to retest, please. 

This page example illustrates many of our spacing variations: 
- https://pr-294-yalesites-platform.pantheonsite.io/components

Screenshot 2023-06-27 at 11-05-39 Components-sm

---


These two have other variations: 

- https://pr-294-yalesites-platform.pantheonsite.io/standard-page-one
- https://pr-294-yalesites-platform.pantheonsite.io/top-goal-site

Screenshot 2023-06-27 at 11-06-01 Top goal for the site

Screenshot 2023-06-27 at 11-08-29 Standard page one

---

Please test different combinations and login and add more, if you'd like. 

Thank you!

**Comment by ahitson** [comment]
Looks like the text between paragraphs situation got a little worse...
Screen Shot 2023-06-27 at 9 22 32 AM

**Comment by joetower** [comment]
@ahitson The screenshot you shared matches the Design System: https://deploy-preview-255--dev-component-library-twig.netlify.app/?path=/story/molecules-wrapped-image--wrapped-image

What should we look at changing?

**Comment by joetower** [comment]
@ahitson I pushed up all the fixes we discussed. 

Please take another look and let me know if this looks good to go. Thank you so much!

- https://pr-294-yalesites-platform.pantheonsite.io/components
- https://pr-294-yalesites-platform.pantheonsite.io/standard-page-one
- https://pr-294-yalesites-platform.pantheonsite.io/top-goal-site

**Comment by ahitson** [comment]
So much closer, but the page is showing 3 different sizes between paragraphs. It's unfortunate because now everything looks good when stacked for mobile sizes. Took screenshots of the differences:
Screen Shot 2023-06-27 at 11 31 02 AM
Screen Shot 2023-06-27 at 11 31 11 AM
Screen Shot 2023-06-27 at 11 31 48 AM

**Comment by joetower** [comment]
@ahitson Okay, this should be ready again. Thanks again! :partying_face:

**Comment by joetower** [comment]
@ahitson The wrapped-image breakpoint adjustments have been made. This is ready for another look, please. 
https://pr-294-yalesites-platform.pantheonsite.io/components

**Comment by ahitson** [comment]
Fix is good. There is still a little bit more space between some paragraphs compared to others, but I am going to make a separate refinement ticket with that info.

**Review by ahitson — APPROVED** [review]

**Comment by joetower** [comment]
@codechefmarc or @nJim Could one of you please give my latest changes here a look? 

If things look good code-wise and functionally, please approve this PR along with these, and we can get this work shipped. 

- https://github.com/yalesites-org/atomic/pull/133
- https://github.com/yalesites-org/component-library-twig/pull/255

Thank you!

**Review by codechefmarc — APPROVED** [review]
Mostly bowing to Ashley's review here, but I did take a look and it looks good to me so I will approve this. While I understand the work as a whole, the details of each component aren't something I am able to grok at the moment, but I trust Ashley's input here.

**Pull request merged**
