### PR TITLE
IYY-263: Show CAS'd content in search results

### PR DESCRIPTION
**Pull request by codechefmarc**
### Description of work
- Adds a new Search API index that searches CAS content by indexing the content as viewed by an authenticated user
- Adds a new view for showing CAS content
- Updates the header settings form to add a new option to show CAS titles only when searching. Default is off.
- Removes the `/search` path from the existing Search view
- Replaced with a custom route and controller to handle the `/search` path and only shows CAS content if set in the header settings form.
- Note: This requires Atomic [PR-284](https://github.com/yalesites-org/atomic/pull/284) as that is where the logic is to disable the rendering of the teaser and content preview of CAS nodes.
- A second FED part of this ticket will add a lock icon next to the CAS-only titles.

### Security Implications 
- All CAS content (rendered HTML default display) is still indexed in a new index (Node and CAS Index, machine name `secure_index`) but only the titles show (via TWIG).
- This is important because people can still search for all content inside a CAS page and get results for CAS-only content, but only see titles. We added a safety via the header settings form so sites will need to opt into this new feature but we want to be sure Yale ITS approves of this change before merge.

### Functional testing steps:
- [ ] Login to the site and add a few pages/posts/events/profiles with some content you can use to test searching. Content can go into layout builder and/or the teaser text.
- [ ] Use the search form and verify you can find your content.
- [ ] Edit one of the pages and change it to CAS Login Required and save the page.

Screenshot 2024-11-19 at 4 56 56 PM

- [ ] Perform the search again and verify that the CAS-only content does not show up in the results.

Screenshot 2024-11-19 at 4 54 43 PM

- [ ] Visit the Header Settings form at `/admin/yalesites/header`
- [ ] Verify there is a new setting under "Site Search" for "Enable CAS search". Note, this only shows up when "Enable search form" is enabled.

Screenshot 2024-11-19 at 4 58 49 PM

- [ ] Enable CAS search and then perform the same search again and verify that search results now include CAS-only nodes, but that those results only show a title

Screenshot 2024-11-19 at 5 00 09 PM

- [ ] Verify that clicking on the CAS-only title will prompt you to login

### CODE REVIEW

**Comment by miketullo95** [comment]
@codechefmarc this looks great! I tested with all the content types -  while logged in it looks like the search results are working properly. While in incognito it looks like it works too, i tested with a variety of nodes with 'mike' in the title and noticed some oddities between searching "Mike" and "mike" here - https://pr-800-yalesites-platform.pantheonsite.io/search?keywords=Mike. 

Looks like capital M gets the correct amount of results, but lowercase doesn't? Idk if this is relevant to this ticket, but while testing it i noticed this 🤷

**Comment by dblanken-yale** [comment]
@miketullo95 Strange, I'm seeing 5 in each result now.  Are you still seeing this?

**Comment by miketullo95** [comment]
> @miketullo95 Strange, I'm seeing 5 in each result now. Are you still seeing this?

yep, very strange, maybe just caching lol

**Review by dblanken-yale — APPROVED** [review]
Works how we talked.  I did want to learn more about this though--so the reason we're able to overload it is by overloading the /search route?  Just verifying that I'm understanding since it sounded like search was special possibly.  heh

**Review by miketullo95 — APPROVED** [review]
this looks great! 👍

**Comment by codechefmarc** [comment]
> Works how we talked. I did want to learn more about this though--so the reason we're able to overload it is by overloading the /search route? Just verifying that I'm understanding since it sounded like search was special possibly. heh

Yup, I turned off the `/search` path on the original search view, and added a custom controller with route to handle the `/search` path. Then, I check on the header config to determine which search view (and therefore index) should be used.

I'll give this a once-over for the lock icon (haven't seen it yet) and then once done, @dblanken-yale - how do you want to handle merging of IYY PR's? Will we do that or will you? Thanks!

**Comment by dblanken-yale** [comment]
@codechefmarc Unless @miketullo95 has any issues with it, I trust you guys.  😁 You can go into develop once approvals are in order.  If you ever don't feel comfortable, let me know and I can do it.

Thanks for the explanation; pretty cool!

**Comment by miketullo95** [comment]
> @codechefmarc Unless @miketullo95 has any issues with it, I trust you guys. 😁 You can go into develop once approvals are in order. If you ever don't feel comfortable, let me know and I can do it.
> 
> Thanks for the explanation; pretty cool!

agreed! 👍

**Pull request merged**
