### PR TITLE
fix(yalb-alignment): increase wrapped image width

### PR DESCRIPTION
**Pull request by joetower**
### Tickets
- [YALB-1055 - Alignment: Text to Left Edge and Text to Right Edge](https://yaleits.atlassian.net/browse/YALB-1055)
  - Components now have a left alignment with a limited inner width so text doesn't run too long while aligning along the left-hand rail. 
- [YALB-1056 - Alignment: Menus ](https://yaleits.atlassian.net/browse/YALB-1056)
  - the primary menu top item text should now properly align with the site name, and do so whether left or right aligned
- [YALB-1065 - Alignment: Wire changes to Drupal](https://yaleits.atlassian.net/browse/YALB-1065)
- [YALB-1023 - Feedback: Consistant grid across components](https://yaleits.atlassian.net/browse/YALB-1023)
  - We reviewed the wrapped image and text spotlight components during a working group session. From this meeting we agreed to remove the text spotlight option for `focus-content` so as not to compete, so-to-say, with the wrapped image component.
  
### Description of work
Bundles all alignment work into this branch, spread over three repositories (including this one): 
- https://github.com/yalesites-org/component-library-twig/pull/213
- https://github.com/yalesites-org/atomic/pull/102

#### Components that needed updates:
- Custom cards - change to site-width
- Quicklinks subtle version - left align and remain at `content` width when used on `pages`, on `news/events` it will render `content` width and `center` aligned. 
- Quicklinks promotional version - full width `site` width inner
- Mega Menu - expanded menu outside of boundaries
- Images/quotes/media - `content` width and `left` aligned
- Quotes - now have limited left-aligned width, with agreed upon spacing
- Wrapped Image - content width and left aligned
- Text Spotlight (text with image) - `site` width and focus `equal` and `image` only

### Functional testing steps:
- [ ] Review example components on a News article here: https://pr-235-yalesites-platform.pantheonsite.io/news/2023-01-12-longform-article
- [ ] On the news article, verify that only the Quicklinks `full` variation renders wider than `content` width.
- [ ] Review example components on a Page here: https://pr-235-yalesites-platform.pantheonsite.io/standard-page-one
- [ ] Verify the only components which render wider than `site` width are `banner`, `grand hero`, `quicklinks promotional/full` and `callout` components. Note that all component `inner` sections allow the text within each component to be left aligned. Only the background elements extend beyond.
- [ ] Make sure each page components aligns with the alignment documentation here: https://yaleedu.sharepoint.com/:w:/r/sites/YaleSitesUpgradeProgram/_layouts/15/doc2.aspx?action=editNew&sourcedoc=%7B182c4a7d-f583-4c01-84ea-79411d3f7ed3%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&wdhostclicktime=1679328572492&web=1&cid=08b56ff2-c80d-4abd-8b4f-12b31a933908

---

### Help wanted
@nJim 
- For the `text with image` component, I removed the `content: 'Content Focus'` option, but it is still appearing in Drupal. See here: https://github.com/yalesites-org/yalesites-project/pull/235/files#diff-a6693039cfb1016cdd359a414ad0a347655669621d540b94007514d61d8d6e26L45
- Is there anything special we need to do to remove the option?

https://user-images.githubusercontent.com/366413/228938381-0cc5eac9-3453-4fef-a28a-4d985a4700dc.mp4

### CODE REVIEW

**Comment by ahitson** [comment]
News: 
- the gallery items are doing some weird shrinking within a box behavior.
- the quote should have the same padding as on content pages.
- The callout is white, can we fix that?

Banners page:
- The divider above and below the content spotlight are different widths and colors

**Comment by ahitson** [comment]
My only concern would be OPAC seeing the white CTA, so if they are going to review it before that happens, let's make it dark grey.

Since the border on the spotlight is to separate it from other page content, it should be the same as the dividers on the site. The ones between news and event lists are separating content in a series, so it stays as the lighter version.

**Comment by joetower** [comment]
@ahitson I fixed the border width and color so that it, like the `divider` component, uses the theme-configured values. 

Unfortunately, the `callout` issue is one that we can't easily fix right now. The News content type is referencing a `callout-item` directly, instead of the `callout` -- which has the background-color information. Marc is aware of the issue, and we'll fix it when the content is moved into layout builder. Should we just remove the component from any example pages for the time being?

**Comment by ahitson** [comment]
Removing it for now is a great solution.

Still seeing the different dividers on the spotlight, though.

Screen Shot 2023-04-03 at 12 55 10 PM

**Comment by joetower** [comment]
@ahitson Sorry, I spoke too soon on that border. When I push up changes to any of the three repositories for this branched work, I need to rebuild the Drupal multidev. 

When the `Build, deploy and test / deploy_to_pantheon (pull_request)` test is complete, this should be resolved. I'll keep you posted.

**Review by ahitson — APPROVED** [review]

**Pull request merged**
