### PR TITLE
YSP-495: Site-wide branding for University groups

### PR DESCRIPTION
**Pull request by dblanken-yale**
## [YSP-495: Site-wide branding for University groups](https://yaleits.atlassian.net/browse/YSP-495)

Note: Work has been done on all three repos to accomplish this.

[Yalesites Project](https://github.com/yalesites-org/yalesites-project/pull/711)
[Atomic](https://github.com/yalesites-org/atomic/pull/255)
[Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/391)

This allows you to specify in the heading form the sitewide branding and link direction for the site.  The defaults for this are a text of "Yale University" and "https://www.yale.edu".

### Description of work
- Adds `site_wide_branding_name` and `site_wide_branding_link` to the header form (secret menu)

### Functional testing steps:
- [ ] Visit the header settings
- [ ] Expand the "Sitewide Branding" group
- [ ] Change the name
- [ ] Change the URL to point to somewhere else like google
- [ ] Save
- [ ] Verify that when visiting the site, you now see the name you entered in the upper left corner, and it links to the URL you specified.

### CODE REVIEW

**Review by kara-franco — APPROVED** [review]
Nice, there was a multidev this time and I successfully changed the name.

**Review by vinmassaro — APPROVED** [review]
Code looks good to me, just 2 questions:

1. Are we concerned about incorrect usage here? This would allow users to put anything they want in this field.
2. If not "Yale University", does it need a different font/color treatment the way a departmental wordmark would normally look different?

**Comment by dblanken-yale** [comment]
@vinmassaro Good questions.  For the first, it should only be available to Platform Admins (secret menu item), so my hope was it'd only be changed if it was requested.  Yes they could add anything in there, but was hoping this was a sharp knives situation.  Not sure about the second question.  @kara-franco Did we want anything else to be done with that other than the text/link change?

**Comment by dblanken-yale** [comment]
Screenshot 2024-08-01 at 4 50 44 PM

For site admins; just to verify.  It won't show.

**Pull request merged**
