### PR TITLE
Update develop from master

### PR DESCRIPTION
**Pull request by vinmassaro**

### CODE REVIEW

**Comment by dblanken-yale** [comment]
Would deprecation warnings display for users?  I am finding locally after entering a mailto I'm getting the following deprecation warning.  I saw you had a 8.2 upgrade merge request out there for that module, so maybe that would address this?  Still looking, but wanted to get that out there.

```
Deprecated function: Use of "self" in callables is deprecated in Drupal\typogrify\Typogrify::initialQuotes() (line 168 of /app/web/modules/contrib/typogrify/src/Typogrify.php)
#0 /app/web/core/includes/bootstrap.inc(164): _drupal_error_handler_real(8192, 'Use of "self" i...', '/app/web/module...', 168)
#1 [internal function]: _drupal_error_handler(8192, 'Use of "self" i...', '/app/web/module...', 168)
#2 /app/web/modules/contrib/typogrify/src/Typogrify.php(168): preg_replace_callback('/((<(p|h[1-6]|l...', 'self::quoteWrap...', '<p>this is a <a...')
#3 /app/web/modules/contrib/typogrify/src/Plugin/Filter/TypogrifyFilter.php(391): Drupal\typogrify\Typogrify::initialQuotes('<p>this is a <a...')
#4 /app/web/core/modules/filter/src/Element/ProcessedText.php(118): Drupal\typogrify\Plugin\Filter\TypogrifyFilter->process('<p>this is a <a...', 'en')
#5 [internal function]: Drupal\filter\Element\ProcessedText::preRenderText(Array)
#6 /app/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(111): call_user_func_array(Array, Array)
#7 /app/web/core/lib/Drupal/Core/Render/Renderer.php(797): Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'exception', 'Drupal\\Core\\Ren...')
#8 /app/web/core/lib/Drupal/Core/Render/Renderer.php(386): Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array)
#9 /app/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#10 /app/web/core/lib/Drupal/Core/Template/TwigExtension.php(474): Drupal\Core\Render\Renderer->render(Array)
#11 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(44): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#12 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_b860a070035bf9bc2a459af6d9b69ad4->doDisplay(Array, Array)
#13 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /app/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#15 /app/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#16 /app/web/core/themes/engines/twig/twig.engine(53): Twig\TemplateWrapper->render(Array)
#17 /app/web/core/lib/Drupal/Core/Theme/ThemeManager.php(372): twig_render_template('themes/contrib/...', Array)
#18 /app/web/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('field', Array)
#19 /app/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#20 /app/web/core/lib/Drupal/Core/Template/TwigExtension.php(474): Drupal\Core\Render\Renderer->render(Array)
#21 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(85): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#22 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_f33c845caaf50adbb5a0618144108170->doDisplay(Array, Array)
#23 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#24 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(39): Twig\Template->display(Array)
#25 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_0d3c6ae8b530640e826a8dbf2a40faf5->doDisplay(Array, Array)
#26 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#27 /app/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#28 /app/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#29 /app/web/core/themes/engines/twig/twig.engine(53): Twig\TemplateWrapper->render(Array)
#30 /app/web/core/lib/Drupal/Core/Theme/ThemeManager.php(372): twig_render_template('themes/contrib/...', Array)
#31 /app/web/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('paragraph', Array)
#32 /app/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#33 /app/web/core/lib/Drupal/Core/Template/TwigExtension.php(474): Drupal\Core\Render\Renderer->render(Array)
#34 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(363): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#35 /app/vendor/twig/twig/src/Template.php(171): __TwigTemplate_5c175083a09138f1bd9f93616a96c6cb___2130119529->block_media_grid__modal__content(Array, Array)
#36 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(249): Twig\Template->displayBlock('media_grid__mod...', Array, Array)
#37 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_2f6db6626d1a60e48c36105d16a1d02f->doDisplay(Array, Array)
#38 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#39 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(334): Twig\Template->display(Array, Array)
#40 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_5c175083a09138f1bd9f93616a96c6cb___2130119529->doDisplay(Array, Array)
#41 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#42 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(86): Twig\Template->display(Array)
#43 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_5c175083a09138f1bd9f93616a96c6cb->doDisplay(Array, Array)
#44 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#45 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(218): Twig\Template->display(Array)
#46 /app/vendor/twig/twig/src/Template.php(171): __TwigTemplate_1b894614fe0875e64812d4034999b5f3___344142953->block_media_grid__modal(Array, Array)
#47 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(113): Twig\Template->displayBlock('media_grid__mod...', Array, Array)
#48 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_5b2cd73353b95fcd8f0d95754b0122e4->doDisplay(Array, Array)
#49 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#50 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(198): Twig\Template->display(Array, Array)
#51 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_1b894614fe0875e64812d4034999b5f3___344142953->doDisplay(Array, Array)
#52 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#53 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(77): Twig\Template->display(Array)
#54 /app/vendor/twig/twig/src/Template.php(171): __TwigTemplate_1b894614fe0875e64812d4034999b5f3->block_content(Array, Array)
#55 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(84): Twig\Template->displayBlock('content', Array, Array)
#56 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_70df6b672c554c917d574b39d2fdb8c9->doDisplay(Array, Array)
#57 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#58 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(44): Twig\Template->display(Array, Array)
#59 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_1b894614fe0875e64812d4034999b5f3->doDisplay(Array, Array)
#60 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#61 /app/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#62 /app/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#63 /app/web/core/themes/engines/twig/twig.engine(53): Twig\TemplateWrapper->render(Array)
#64 /app/web/core/lib/Drupal/Core/Theme/ThemeManager.php(372): twig_render_template('themes/contrib/...', Array)
#65 /app/web/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('block', Array)
#66 /app/web/core/lib/Drupal/Core/Render/Renderer.php(458): Drupal\Core\Render\Renderer->doRender(Array)
#67 /app/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#68 /app/web/core/lib/Drupal/Core/Template/TwigExtension.php(474): Drupal\Core\Render\Renderer->render(Array)
#69 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(52): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#70 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_0f3a939e37d73d1ba876acadb746e254->doDisplay(Array, Array)
#71 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#72 /app/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#73 /app/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#74 /app/web/core/themes/engines/twig/twig.engine(53): Twig\TemplateWrapper->render(Array)
#75 /app/web/core/lib/Drupal/Core/Theme/ThemeManager.php(372): twig_render_template('core/themes/sta...', Array)
#76 /app/web/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('layout__onecol', Array)
#77 /app/web/core/lib/Drupal/Core/Render/Renderer.php(458): Drupal\Core\Render\Renderer->doRender(Array)
#78 /app/web/core/lib/Drupal/Core/Render/Renderer.php(458): Drupal\Core\Render\Renderer->doRender(Array)
#79 /app/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#80 /app/web/core/lib/Drupal/Core/Template/TwigExtension.php(474): Drupal\Core\Render\Renderer->render(Array)
#81 /app/vendor/twig/twig/src/Environment.php(361) : eval()'d code(50): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#82 /app/vendor/twig/twig/src/Template.php(394): __TwigTemplate_3377de7a75f0c16ee9cade9d48f7ae4f->doDisplay(Array, Array)
#83 /app/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#84 /app/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#85 /app/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#86 /app/web/core/themes/engines/twig/twig.engine(53): Twig\TemplateWrapper->render(Array)
#87 /app/web/core/lib/Drupal/Core/Theme/ThemeManager.php(372): twig_render_template('themes/contrib/...', Array)
#88 /app/web/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('node', Array)
#89 /app/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#90 /app/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(238): Drupal\Core\Render\Renderer->render(Array, false)
#91 /app/web/core/lib/Drupal/Core/Render/Renderer.php(592): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#92 /app/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(231): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#93 /app/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(128): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#94 /app/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#95 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#96 /app/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#97 /app/vendor/symfony/http-kernel/HttpKernel.php(186): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view')
#98 /app/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#99 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#100 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#101 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#102 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#103 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#104 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#105 /app/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#106 /app/web/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#107 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#108 {main}
```

**Comment by vinmassaro** [comment]
@dblanken-yale I see the deprecated warnings getting logged but not displayed on dev sites now. I do see them visible when working locally so I assume it's because of a local setting forcing it.

I did run Drupal Rector against the Typogrify module and [opened an issue](https://www.drupal.org/project/typogrify/issues/3398815) for PHP 8.2 support. I was hoping it would get a quick review but there hasn't been any action, so we may just have to run a patch until then.

**Comment by dblanken-yale** [comment]
Yep with your patch it's no longer giving deprecation warnings.  Great job!  Let's hope they get it merged! heh

So far I've not seen any other issues; I'll keep poking at it today and if I find anything I'll post it here.

**Review by codechefmarc — APPROVED** [review]
If I did an initial build locally based on an existing D9 site, it would fail. However, if I removed the `vendor` directory and the `composer.lock` file and re-ran `npm run build-with-assets` everything worked out perfectly. I browsed around a bit with admin and anonymous access and it all looked good to me.

**Review by nJim — APPROVED** [review]
Everything looks great. Build from scratch on my local and had another webchef (Hector) test too. Clean build for both of us. I also added the patch to typogrify to the profile and tried to move that forward on d.o.

**Pull request merged**
