### PR TITLE
YSP-143: Add description and tag fields to media

### PR DESCRIPTION
**Pull request by nJim**
### Description of work
- Adds description and tagging fields to media elements
- We discussed allowing images to have a custom name field. While this is a good suggestion, the current auto entity label module is not working for the image 'name' field. We can make this a separate ticket if we want to change this value in the future. For now, we will keep the existing functionality where image names are the same as the file upload name.

### Functional testing steps:
- [x] [Login to the site as an admin](https://pr-582-yalesites-platform.pantheonsite.io/cas)
- [x] Review the [add background video](https://pr-582-yalesites-platform.pantheonsite.io/media/add/background_video) interface.
  - [x] New 'Tags' field is present. It is optional, allows multiple values, and uses the chosen widget.
  - [x] The 'Name' field appears at the top of the form.
  - [x] Upload a mp4 video and verify that a 'description' field is now available (sample videos)[https://file-examples.com/index.php/sample-video-files/sample-mp4-files/].
- [x] Review the [add document](https://pr-582-yalesites-platform.pantheonsite.io/media/add/document) interface.
  - [x] New 'Tags' field is present. It is optional, allows multiple values, and uses the chosen widget.
  - [x] The 'Name' field appears at the top of the form.
  - [x] Upload a file and verify that a 'description' field is now available.
- [x] Review the [add image](https://pr-582-yalesites-platform.pantheonsite.io/media/add/image) interface.
  - [x] New 'Tags' field is present. It is optional, allows multiple values, and uses the chosen widget.
- [x] Review the [add video](https://pr-582-yalesites-platform.pantheonsite.io/media/add/video) interface.
  - [x] New 'Tags' field is present. It is optional, allows multiple values, and uses the chosen widget.

### CODE REVIEW

**Comment by dblanken-yale** [comment]
@nJim Nice work.  For the image, should there be a "Name" attribute or was this a copy/paste issue; seems that the alt text is fine, but I did not see the Name as another option.

Screenshot 2024-04-01 at 4 03 25 PM

Screenshot 2024-04-01 at 4 04 12 PM

I suspect it is.  Everything else looks good.  Since we're allowing tags on media, should we also modify the media table view to include them like we do in Content?

Has my approval but will wait to make sure on image before approving.

**Comment by nJim** [comment]
Talk with Kara and we will add the 'Name' field to the image upload and edit screen. Let's confirm that this is not required and will default to the file name.

**Comment by nJim** [comment]
We discussed allowing images to have a custom name field. While this is a good suggestion, the current auto entity label module is not working for the image 'name' field. We can make this a separate ticket if we want to change this value in the future. For now, we will keep the existing functionality where image names are the same as the file upload name. I will bring this up for review at our next meeting.

**Comment by miketullo95** [comment]
per our meeting, add the ability to add a tag when you upload an image. Right now it only shows up on editing an existing image.

**Pull request merged**
