### PR TITLE
YALB-534 and YALB-535: Backend represent components better

### PR DESCRIPTION
**Pull request by ModulesUnraveled**
## This PR covers the following tickets:
- [YALB-534: Represent columns on the back end](https://yaleits.atlassian.net/browse/YALB-534)
- [YALB-535: Represent components on the back end](https://yaleits.atlassian.net/browse/YALB-535)

### Description of work
- Updates the way components and layouts are represented on the backend per Ashley's feedback

### Functional testing steps:
- [ ] [Log in](https://pr-40-yalesites-platform.pantheonsite.io/) and [Create a page](https://pr-40-yalesites-platform.pantheonsite.io/node/add/page)
- [ ] Add a section with some components inside of it
- [ ] Add all of the other types of section
- [ ] Verify the components and layouts are displayed according to the tickets above.

### CODE REVIEW

**Comment by ahitson** [comment]
- Can we indent the primary and secondary content sections in more so that they have their own distinct boundaries? 
- An the segments within an item, like the callout, are being pushed together and doing something funky with the lines.
Frame 480

**Comment by ModulesUnraveled** [comment]
@ahitson I think I've fixed those things, you can take a look here: https://pr-40-yalesites-platform.pantheonsite.io/node/2/edit

**Review by ahitson — APPROVED** [review]
ooooooo! aaaaaahh!

**Review by kara-franco — APPROVED** [review]
Changes meet accessibility specs!  I love the use of indentation and color to differentiate the different page parts!

**Review by callinmullaney — APPROVED** [review]
@ModulesUnraveled Passes code/functional review and looks good to merge. I posed this suggestion to Ashley in our slack but that shouldn't block merging of what is already in place.
Screenshot from 2022-05-20 09-56-57

**Review by miketullo95 — APPROVED** [review]
this looks great! much improved authoring experience! 😄

**Pull request merged**
