### PR TITLE
YALB-1164 - OPAC: Update admin toolbar icons | 1461 - OPAC: Implement new admin colors and fonts

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Adds new icons for the admin toolbar
- Implements new colors and fonts throughout the admin theme and frontend layout-builder

#### Testing: [YALB-1164 - OPAC: Update admin toolbar icons](https://yaleits.atlassian.net/browse/YALB-1164) 
- [x] Visit a page such as: https://pr-358-yalesites-platform.pantheonsite.io/components
- [x] Verify you see the new icons
- [x] Interact with the `unpublish` and `publish` button - note the icons change color. I used very slightly tinted `green` and `red` color values as more saturated colors would cause contrast issues. 

https://github.com/yalesites-org/yalesites-project/assets/366413/f3316db8-5f15-403f-bb0e-d6f474b3a612

---

#### Testing: [YALB-1461 - OPAC: Implement new admin colors and fonts](https://yaleits.atlassian.net/browse/YALB-1461)
- [x] Visit a page such as: https://pr-358-yalesites-platform.pantheonsite.io/components
- [x] Edit the layout and interact with the layout-builder editing interface
- [x] Move a block like this: 

https://github.com/yalesites-org/yalesites-project/assets/366413/732bf916-18d2-45d2-aca1-d5f3126a1517

- [ ] Verify things are themed and that nothing is illegible due to color contrast
- [ ] Browse through various admin pages and make sure the theme doesn't cause color contrast issues
- [ ] Some examples:
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/yalesites/dashboard
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/reports/views-plugins
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/config/media
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/yalesites/footer
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/yalesites/settings
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/reports/status
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/content
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/people
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/modules/update
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/config
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/appearance
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/config/content/layout-builder-browser
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/reports/editoria11y
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/reports/editoria11y/issues
  - [ ] https://pr-358-yalesites-platform.pantheonsite.io/admin/admin/reports/editoria11y/pages

https://github.com/yalesites-org/yalesites-project/assets/366413/9c13b74c-6162-4241-9d6b-680cc8fbd692

### CODE REVIEW

**Comment by miketullo95** [comment]
Hello! This is look great! I noticed in alert settings there seems to be some text color issues going on. Screenshot below. 
Screen Shot 2023-07-20 at 1 15 00 PM
Will keep looking through to find more things

**Comment by joetower** [comment]
@miketullo95 I pushed a fix up for the text issue on blocks, as you pointed out, and some additional fixes for the content creation pages. 

I'm going to keep testing and fixing things locally, but please continue outlining anything else you notice. Thank you!

**Review by dblanken-yale — APPROVED** [review]
It looks good.  I'll let the others weigh in on contrast and the like, but I am not noticing any major issues.

**Comment by miketullo95** [comment]
Morning! Here are a few small things:
On the media library, the toggle between grid and table may have some contrast issues 
image
Media modal pagination 
image
Not sure if this falls under this effort, but when selecting from the linkit module there is some funky color stuff here 
image
button icon hover color in taxonomy manager
image
last one, again, might not be this effort specifically, but the yale icon seems to be cut-off now 
image

**Comment by miketullo95** [comment]
this looks great! last thing i noticed. In /layout we are getting the wool background on content areas which i think we just want white 
image

**Comment by joetower** [comment]
@miketullo95 Apologies, please hold off testing. I just saw one more item. I'll keep you posted. Thanks!

**Comment by joetower** [comment]
@miketullo95 Okay, this should be ready to test again. 

Please make sure to add/edit layout-builder content and make sure text renders as it should.

**Comment by miketullo95** [comment]
text highlight color should have more contrast:
Screen Shot 2023-07-25 at 11 18 54 AM

One small suggestion - could we change gin-bg-app: to something lighter like #707070? (this passes a11y). In page setup and admin pages the dark color could be jarring to some, so hopefully making it lighter would be easier on the eyes and give some more distinction between the background and the admin bars.

**Comment by joetower** [comment]
@miketullo95 Are you saying that you'd like it to look something like this? 

Screenshot-20230725103757-2552x1209


If this looks good I can double-check anywhere else (in our overrides) that may be using `gin-bg-app` and make that change.

**Comment by joetower** [comment]
@miketullo95 Okay, this should be ready for another look. Thank you for all your testing on this. It's a big change. :+1:

**Comment by miketullo95** [comment]
It seems like on nodes im getting the wool color again :( 
Screen Shot 2023-07-25 at 1 33 49 PM
on /edit I'm not tho 
Screen Shot 2023-07-25 at 1 34 42 PM

**Comment by joetower** [comment]
@miketullo95 Whoops! Looks like some overrides got removed. I added them back and things should be looking correct again. Apologies for that.

**Comment by miketullo95** [comment]
no worries, this looks great! amazing work

**Review by miketullo95 — APPROVED** [review]

**Pull request merged**
