### PR TITLE
YSP-580: Old profiles without settings default to portrait

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Description of work
- Adds a script to update profiles missing settings before v1.4.0 release date to old settings via `php-script`

### Functional testing steps:
- [ ] Create a profile (or I think Alyssa's profile might be included in this)
- [ ] Go into the database if possible and delete the settings for `image_orientation`, `image_style`, and `image_alignment`
- [ ] `cat scripts/phpeval/profile-meta-block-update.php | terminus drush $site.$env -- php-script -`
- [ ] Ensure the profile now shows in `landscape`, `inline`, and `right`. (See jira ticket for before and after)

### CODE REVIEW

**Comment by dblanken-yale** [comment]
The other alternative is to somehow get this into a one-liner we can send through terminus php-eval, but it's a bit of code.

**Comment by dblanken-yale** [comment]
Also for more context, the reason for the try/catch is that the site I tested this on that had a lot of profiles had one that somehow had no title data, causing it to not save.  This still lets us know this while allowing the rest to run.

**Comment by dblanken-yale** [comment]
Removing this multidev for reuse.  Should we need this multidev again, please remember to rebuild it.

**Comment by dblanken-yale** [comment]
@vinmassaro Have you had a chance to try that on the site that gave the go-ahead?  Let me know if you want to hop on a zoom to do it together.  I was leaving this one open till we knew it was successful.

**Review by miketullo95 — APPROVED** [review]
hey - cleaning up my reviews. This looks great! waiting on final dev approval

**Pull request closed without merging**
