### PR TITLE
YSP-374: Deleting focus header image results in sitewide error

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Description of work
- Guards against loading of deleted focus header image on render
- Add a way to clear when multiple values of an image are stored where one doesn't exist

### Functional testing steps:
- [ ] [Log in](https://pr-590-yalesites-platform.pantheonsite.io/cas)
- [ ] [Set the site header settings](https://pr-590-yalesites-platform.pantheonsite.io/admin/yalesites/header) to use focus header, making sure to upload a new image as the focus header image
- [ ] Delete that newly uploaded image in [the media library](https://pr-590-yalesites-platform.pantheonsite.io/admin/content/media), knowing it's being used as the focus header image
- [ ] Verify that you can [visit the front page](https://pr-590-yalesites-platform.pantheonsite.io) and other pages without errors
- [ ] Verify that when you [revisit the site heading settings](https://pr-590-yalesites-platform.pantheonsite.io/admin/yalesites/header) you must select a new focus header image

#### For multiple media values fix
- [ ] Go into the header settings, ensure a new image was added/saved
- [ ] Go back into the header settings, remove the image from there, then add a new image and save
- [ ] Go to media library and delete the original image
- [ ] Ensure that when visiting the front page the new image still shows as the focus header

### CODE REVIEW

**Comment by miketullo95** [comment]
just tried this and got the error 
Screenshot 2024-02-28 at 10 50 28 AM

**Review by kara-franco — APPROVED** [review]
Nice, I went through the steps and it works for me!

**Comment by dblanken-yale** [comment]
Going to move this from off of v110 to off of develop so it can be in next release.

**Comment by dblanken-yale** [comment]
@codechefmarc Are you able to remember the steps you used to recreate what you and I saw on Friday?  I couldn't get it to happen locally and now that I've changed the image, it works as expected.  I even changed it back to the specific image because I thought maybe it was a bug somewhere else, but it's working as well!

**Comment by codechefmarc** [comment]
@dblanken-yale - I just tried it myself on the multidev and it's working as expected now. I don't know what was different last week! I did also test deleting the media after it has been set as the header image and no errors.

**Comment by codechefmarc** [comment]
Gah, and I figured it out - if a header image WAS set, then deleted, then a new one set, it doesn't work. And I know why based on the footer images work. The form adds to an array of header images so the config is actually [34, 56] (examples, not real values) so it won't load it because it needs it to be an int of one value, not multiple. I know how to fix based on my work from the other PR, so I'll go in there and see what I can do.

**Comment by dblanken-yale** [comment]
@codechefmarc Ah that does make sense.  Good thing you're working on that one as well!  hahaha. Yep I'll push this one through then and you can incorporate that fix into yours.

**Comment by codechefmarc** [comment]
@dblanken-yale - Can you test on the multidev and let me know if the new changes fix it? Thank you!

**Comment by dblanken-yale** [comment]
@codechefmarc Ok teaching moment.  haha. It does work, but my expectation would be the first load after an array is set it'd clear, meaning no image would show, but that's not the case.  Is it that when you save on the header form it actually does attempt to process that part of the code on the re-render of the form and so it clears it at that time vs on the first visit to the page?

**Comment by dblanken-yale** [comment]
@miketullo95 (et all) I've updated the instructions to help test what @codechefmarc was able to fix in this PR.  Do you mind also testing this?  Once we get approvals I think this will be ready for merge.

**Comment by codechefmarc** [comment]
> @codechefmarc Ok teaching moment. haha. It does work, but my expectation would be the first load after an array is set it'd clear, meaning no image would show, but that's not the case. Is it that when you save on the header form it actually does attempt to process that part of the code on the re-render of the form and so it clears it at that time vs on the first visit to the page?

True - if there was no front-page load after setting a replacement header image, then yes, it would wipe out the config (because it's an array) and you'd have to set it again. That said, my thought was that the only time it caused an issue was on the front-page load and so that's where I thought to put the clear if it doesn't exist / is an array. We can do this on the header form itself if you think that is better, but it's less likely that the header form is going to be loaded and more likely that the front page will be loaded.

In my testing, I was sort of viewing it from the eyes of a content editor (hopefully) checking their work on the front page, not seeing an image (because the media was deleted), then going in to add a focus header image, saving, and then viewing the front page again, so therefore it would work immediately. But if you think we should do this someplace else, that's fine with me. :)

**Comment by miketullo95** [comment]
@dblanken-yale - after uploading a new image im getting this error. If I go to the homepage I don't have the focus header and when going back to this setting page the image is not assigned to the focus image (but still uploaded to the media library)

Screenshot 2024-03-14 at 9 14 33 AM

**Comment by dblanken-yale** [comment]
@miketullo95 Thanks for looking.  I'm gong to take a look at that portion once more; I think I know where it is doing it.

**Comment by dblanken-yale** [comment]
@miketullo95 Sorry about that Mike; I was negating the check so you got that message on any save.  LOL

Give it a try now if you still have time.

**Comment by miketullo95** [comment]
@dblanken-yale this is great! love the new error messaging once you delete the image

**Review by miketullo95 — APPROVED** [review]

**Review by codechefmarc — APPROVED** [review]
Approved as it is all working for me. But, I didn't see the message about it being deleted? I see the code there and it looks like it would do it, but I didn't get the message...

**Comment by dblanken-yale** [comment]
@codechefmarc So strange; can you give it another try?  I see it after deleting from the media library:

Screenshot 2024-03-18 at 8 58 26 AM

Are you deleting from another location?

**Comment by codechefmarc** [comment]
@dblanken-yale I see it now. I think my message for the footer ones was showing on the front-end, whereas yours shows in the media library once I delete it. That works for me!

**Review by kara-franco — APPROVED** [review]
Excellent! Error displays to remind you to add new image and site does not crash!

No a11y issues found.

**Pull request merged**
