### PR TITLE
YALB-1485/YALB-1486/YALB-1488: Mega Footer

### PR DESCRIPTION
**Pull request by codechefmarc**
## Tickets
* [YALB-1485: Fat Footer Branding: BE](https://yaleits.atlassian.net/browse/YALB-1485)
* [YALB-1486: Fat Footer Branding: FE ](https://yaleits.atlassian.net/browse/YALB-1486)
* [YALB-1488: Fat Footer Branding: Wiring](https://yaleits.atlassian.net/browse/YALB-1488)

Coauthored by @joetower 

### Description of work
- Adds form and config for mega footer
- Ability to turn mega footer on/off - default to off
- Form includes: 4 logos with optional URL's, 1 school logo with optional URL (and fallback to site front page if not specified), WYSIWYG content area, 2 columns of links (4 links max) with optional headers
- Requires [Atomic PR-164](https://github.com/yalesites-org/atomic/pull/164)
- Requires [Component Library PR-283](https://github.com/yalesites-org/component-library-twig/pull/283)

### Functional testing steps:
- [x] Login to the site and visit the Footer Settings form at `/admin/yalesites/footer`
- [x] Verify that there is a new form that has the ability to turn on and off the mega footer and vertical tabs with the different sections for the footer.

Screenshot 2023-08-28 at 3 43 21 PM

- [ ] Enable the mega footer on at the top and fill out the various fields for logos, content, and links.
- [ ] For each change, save at the bottom of the form and check the front-end.
- [ ] Check and verify the following:
     - [ ] Footer logos with/without links
     - [x] Reordering of footer logos
     - [ ] School logo with/without link - if no link, image should fallback to link to the homepage of the site
     - [ ] Content markup - adding links, bold, and italic
     - [ ] Column links with/without headings
     - [ ] Column link without a title or without a URL (should not allow you to add links that don't have a title and URL)
     - [x] Reordering of column links
- [ ] Verify that the mega footer matches the designs here: https://www.figma.com/file/4Lx9A5sxO08DxUNbewalrR/Header-and-Footer-ideas?type=design&node-id=0-1&mode=design

### Accessibility

Note: Accessibility known bug - Broken ARIA reference for Footer variation radio buttons on form: https://www.drupal.org/project/drupal/issues/2839344

- [ ] Test accessibility of form and front-end

### CODE REVIEW

**Comment by codechefmarc** [comment]
@joetower - In testing accessibility for the form, I got a low contrast error, screenshot below, but it is the media library remove button. Is this something you can fix?

Screenshot 2023-08-28 at 4 03 36 PM

**Comment by codechefmarc** [comment]
@miketullo95 - Tagging you for review of the UX of the footer settings form. Let me know your thoughts! Thanks!

**Comment by joetower** [comment]
@codechefmarc I do see what you're seeing with the low contrast issues, but I don't understand what text/background it's referring to :thinking: . Maybe it's the remove button? I'm confused. If it is the remove button I feel as though it is as contrasty as it can be, given all the variables involved. I'll give this some though but maybe it's a false positive? We can have Kara review for accessibility, too. 

https://github.com/yalesites-org/yalesites-project/assets/366413/dca6d53b-8e6d-4843-83f1-10592a9b76e1

**Review by dblanken-yale — DISMISSED** [review]
While the images are saving, the links associated don't seem to be saving.  Are you all experiencing this?  I receive a successful save notification, but then the links are empty (or defaulted in the case of the logo)

**Comment by dblanken-yale** [comment]
Also I went in to add the footer links, and when I went back in to make changes, the URLs were gone there as well, but validation took over and told me.

**Comment by miketullo95** [comment]
This looks awesome! @codechefmarc 

Potential pie-in-the-sky question: Would it be too much scope to visually hide the mega footer options (everything besides social links) when the user has selected basic, then show the settings once the user selects mega?

UI To-dos: @joetower 
- [ ] Make area above "Footer logos" dark grey
- [ ] visually show the white stroke of the form area under the tab
Screen Shot 2023-08-29 at 11 08 06 AM

@nJim Do we want to make these variation selections visual icons/radio button styles now? or wait for the bigger effort around this?

**Comment by joetower** [comment]
@miketullo95 I pushed up fixes to address your comments. 
https://pr-406-yalesites-platform.pantheonsite.io/admin/yalesites/footer

You should now see the following: 
Screenshot-20230829123453-2460x1001

**Comment by codechefmarc** [comment]
@dblanken-yale fixed the issue with external links. So now you can add external, internal via autocomplete, or internal via a manually typed path.

**Comment by codechefmarc** [comment]
@miketullo95 - I think show/hide based on radio button selection should be relatively straightforward. I'll poke at it and if it's easy, I'll make that change. If not, we can certainly add a new ticket to address later.

**Comment by codechefmarc** [comment]
@miketullo95 - OK, check the form now. I've switched it so that if you select "Basic", it only shows social links and they are open by default. If you select "Mega" then it shows all of them, but they are currently all collapsed (as there is a lot of info to show and it would be overwhelming). That said, if you want any of them to to default open, I can do that too, just let me know which ones.

Screenshot 2023-08-29 at 2 05 50 PM

Screenshot 2023-08-29 at 2 05 55 PM

**Comment by miketullo95** [comment]
@codechefmarc Hello! This is a great direction! I had a quick chat with Jim yesterday and while hiding the unnecessary settings is a good start, I think still showing them, but visually and functionally disabling them may be better. This ensures the user that if they change from mega to simple their content won't be deleted and if they toggle mega back, it will be waiting right there for them. I mocked up my ideal UI below.
footer

**todos:**
- [ ] Change to a disabled mode instead of hiding 
    - [ ] disabled sections are light grey (#6F6F6F) color with icon.
- [ ] Change the order of groups to Social Links, Footer logos, Footer content, Footer link (this lets social links be first and won't be jarring when you toggle
- [ ] Change radio buttons to icon buttons (provided below)
- [ ] Add dynamic help text (same as alert settings page) for basic footer and mega footer

**Help Text:**
Basic: "The basic footer of your website contains only social media icons and Yale branding."
Mega: "The mega footer of your website can be customized to suit your organizational needs. You can upload icons for various organizational identities and other platforms that your organization uses. You can also add a customizable text area with general information, contact information, or a physical address. Additionally, you can add up to 8 links in a two-column format."


Icons attached
basic footer
mega footer
footer-disabled

**Comment by codechefmarc** [comment]
@miketullo95 - Got this working for you on the multidev, let me know what you think!

@joetower - In doing the work that Mike Tullo asked for, I sort of replicated the CSS you did for Views Basic with the icons and such. It works, but, there are some hardcoded values and such because I couldn't figure out how to get the tokens CSS included. It said it was included, but didn't work for the root variables. If you have some time tomorrow (Thursday), would you have time to jump on a call and show me how that piece works? Thanks!

**Comment by codechefmarc** [comment]
@miketullo95 - OK, your changes have been made on the multidev, ready for re-review. Thank you!

**Review by miketullo95 — APPROVED** [review]
This looks great! Super happy how this turned out 👍

**Comment by codechefmarc** [comment]
@miketullo95 - great catch! The caching is now fixed on the multidev. Please review and if you approve, I'll push this work forward. Thanks!

**Comment by kara-franco** [comment]
One quick color contrast issue, on focus, this text does not pass 4.5:1.

Found under Configure Footer Settings

Screenshot 2023-09-08 at 2 04 53 PM

**Comment by codechefmarc** [comment]
@kara-franco - Can you tell me where you are seeing that button? I don't see it in the footer settings form? Thanks!

**Pull request merged**
