### PR TITLE
YALB-1510: Mega Menu: Present Level One links as Headings - BE

### PR DESCRIPTION
**Pull request by codechefmarc**
### Description of work
- Changes first level link inside mega menu to a heading with a CTA that links to that page
- CTA link text is configurable via menu / node edit form
- CTA link text defaults to "Explore all"
- Requires [PR-166 Atomic](https://github.com/yalesites-org/atomic/pull/166)
- Requires[ PR-284 Component Library](https://github.com/yalesites-org/component-library-twig/pull/284)

### Functional testing steps:
- [x] Login to site and visit any page
- [x] If not already done, make sure mega menu is enabled by clicking on "Theme Settings" at the top of the page, enabling the mega menu, and saving at the bottom of the theme settings form.

Screenshot 2023-08-29 at 3 50 21 PM

- [x] Click on a top level menu item that has an arrow
- [x] Verify that the top level link has a heading that is named the same as the top level link.
- [x] Verify that there is a CTA to the right of the heading that goes to the page for that top level link.

Screenshot 2023-08-29 at 3 50 57 PM

- [x] Click on the CTA to visit that top level page
- [x] Click "manage settings" at the top of the page
- [x] If not already expanded, expand the sidebar by clicking on the sidebar icon on the right side of the screen

Screenshot 2023-08-29 at 3 57 49 PM

- [x] Under "Menu settings" verify that there is a field called "Top level main menu link CTA"
- [x] Add some custom text into that field and save the node

Screenshot 2023-08-29 at 4 00 22 PM

- [x] View the page and open the mega menu
- [x] Verify that the CTA text for that menu item has changed

Screenshot 2023-08-29 at 4 00 54 PM

- [x] Visit the "Content" -> "Manage Main Menu" page

Screenshot 2023-08-29 at 4 01 36 PM

- [x] Edit a top level link
- [x] Verify that the same field, "Top level main menu link CTA", exists

Screenshot 2023-08-29 at 4 03 26 PM

- [x] Enable the basic menu (visit any page, click theme settings link at the top of the page)
- [x] Verify that the first level heading and CTA are gone and is now just a simple link

Screenshot 2023-08-29 at 4 05 03 PM

### CODE REVIEW

**Comment by dblanken-yale** [comment]
@codechefmarc I know you're going to probably change this to use a new field, so just ping me to review after you've got it changed and I'll be happy to, but wanted to let you know that this all worked great as it is currently.  😁

Sorry for such the delay in this.

**Comment by codechefmarc** [comment]
@dblanken-yale - OK, refactored to use menu item extras, please go ahead and test. All steps are the same, but the field name is now called "Mega Menu Top Level Link Text".

@miketullo95 - I changed the field label to "Mega Menu Top Level Link Text" and the help text to "Mega Menu level one links display this link text alongside the Menu link title. If empty, defaults to "Explore all"." as per Sebastianna's recommendations. If this doesn't work, let me know what you would like and I'm happy to change.

**Review by dblanken-yale — APPROVED** [review]
Wonderful job, guys!  Works as intended!  I'll defer to Mike for the rest, but loving the work on this.

**Review by miketullo95 — APPROVED** [review]
This looks great! the labels and help text are very clear to me!

**Pull request merged**
