### PR TITLE
YSP-680: PRESIDENT: Add dial to image banner to allow default and large image display

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Other work to be reviewed:
- [Atomic](https://github.com/yalesites-org/atomic/pull/270)
- [Component Library Twig](https://github.com/yalesites-org/component-library-twig/pull/423)

### Description of work
- Adds image banner size dial to image banner (large or small)
- Mimics the grand hero layout and styling to have consistent feel

### Functional testing steps:
- [x] Create an image banner block
- [x] Observe a new field, `Media Size` with options of "Tall" (default) and "Short"
- [x] Add a grand hero as a reference
  - [x] "Tall" mimics "Full", "Short" mimics "Reduced"
- [x] Ensure videos also look good

### CODE REVIEW

**Comment by miketullo95** [comment]
@dblanken-yale  trying to add an image banner above the page title and getting this error:

<br class="Apple-interchange-newline"><div class="sticky-shadow" style="z-index: 98; position: sticky; pointer-events: none; height: 40px; margin: calc(var(--gin-spacing-xxxl) * -1) auto var(--gin-spacing-l); box-shadow: none; top: calc(var(--gin-toolbar-y-offset) + var(--gin-spacing-xl)); width: calc(100% - min(10vw,96px) + var(--gin-spacing-l)); color: rgb(210, 211, 211); font-family: Mallory, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(27, 27, 29); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><div class="content-header clearfix" style="overflow: initial; margin-bottom: 0px; padding-top: 0px; padding-right: ; padding-bottom: ; padding-left: ; background-color: rgb(27, 27, 29); color: rgb(210, 211, 211); font-family: Mallory, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="layout-container" style="margin-right: min(5vw,var(--gin-spacing-xxl)); margin-left: min(5vw,var(--gin-spacing-xxl));"></div></div><div class="layout-container" style="margin-right: min(5vw,var(--gin-spacing-xxl)); margin-left: min(5vw,var(--gin-spacing-xxl)); color: rgb(210, 211, 211); font-family: Mallory, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(27, 27, 29); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><main class="page-content clearfix" role="main" style="display: block; margin-top: 0px; margin-bottom: 5rem;"><div class="visually-hidden" style="overflow: hidden; clip: rect(1px, 1px, 1px, 1px); width: 1px; height: 1px; overflow-wrap: normal; position: absolute !important; color: rgb(255, 255, 255);"><a id="main-content" tabindex="-1" style="background-color: transparent; color: var(--gin-color-primary); overflow-wrap: break-word; text-decoration-style: dotted;"></a></div><div class="region region-highlighted" style="margin-top: var(--gin-spacing-l);"></div><div class="help" style="margin-top: var(--gin-spacing-l);"></div><div class="region region-content" style="margin-top: var(--gin-spacing-l);"><div id="block-ys-admin-theme-main-page-content" class="block block-system block-system-main-block"><div class="layer-wrapper gin-layer-wrapper" style="margin-top: 0px; box-shadow: 0 6px 16px var(--gin-border-color-layer); border-radius: var(--gin-border-l); width: 1902px; padding: var(--gin-spacing-l); background: var(--gin-bg-layer); border: 1px solid var(--gin-border-color-layer); box-sizing: border-box;">
Type | php
-- | --
Tuesday, September 24, 2024 - 11:44
mt927
https://pr-770-yalesites-platform.pantheonsite.io/layout_builder/add/block/overrides/node.109/0/content/inline_block%3Aimage_banner?_wrapper_format=drupal_dialog
https://pr-770-yalesites-platform.pantheonsite.io/node/109/layout
TypeError: ys_themes_allowed_values_function(): Argument #3 ($entity) must be of type ?Drupal\Core\Entity\ContentEntityInterface, bool given, called in /code/web/core/modules/options/options.module on line 89 in ys_themes_allowed_values_function() (line 28 of /code/web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module).
Error
216.49.130.88

**Comment by dblanken-yale** [comment]
LOL @miketullo95  Grrr; I'll revert that--I was getting a deprecation on the order of those variables only to find out we need it that way hahaha.

Let me rebuild here and we'll get it working.

**Comment by dblanken-yale** [comment]
@miketullo95 It should be up now; give it a go whenever you can.  :D

**Comment by miketullo95** [comment]
@dblanken-yale this looks great! everything functions as expected. Here are my only notes/questions

1. Having no previous context, did we consider 'short' and 'tall' for the names of the dials for the size? these are the same names we use for other banners.
2. I know we did some magic to make the background video be secondary to the primary tab being images for other banners, could we recreate that here too?

**Comment by dblanken-yale** [comment]
@miketullo95 

1. Yes, I even thought of that but since I already had it wired up as such, I left it.  I can easily change that to be short and tall.
2. Yes, I think we can change this; so you mean when you add a media it defaults to images over video?  I think grand hero had video defaulted as well.  If so should I incorporate the this change as well if it's trivial?

**Comment by miketullo95** [comment]
> 2. Yes, I think we can change this; so you mean when you add a media it defaults to images over video?  I think grand hero had video defaulted as well.  If so should I incorporate the this change as well if it's trivial?

yeah exactly! this is how grand hero orders it; 1. Image 2. Background Video
Screenshot 2024-09-24 at 1 42 27 PM

**Comment by dblanken-yale** [comment]
@miketullo95 Building now with both changes.

**Comment by dblanken-yale** [comment]
Going to also try to get that referenced page in the Jira ticket so we can show the difference.

**Comment by dblanken-yale** [comment]
Hold on a bit; think I'm missing a change.

**Comment by dblanken-yale** [comment]
Ok think it's ready; also got the "Welcome" page up that was the issue referenced.

**Review by miketullo95 — APPROVED** [review]
This looks good to me! great work 👍

**Review by atiddei — APPROVED** [review]

**Review by chaohlu — APPROVED** [review]
Looks fine with me

**Pull request merged**
