### PR TITLE
JAKALA: Add Content Type filter to Search Page

### PR DESCRIPTION
**Pull request by marjina-constantin**
## JAKALA: Add Content Type filter to search page

The scope of this task is to add a new filter on the search page and style it based on the updated design.

### Description of work
- Create a new settings page in admin UI for global views configuration
- Add Content Type filter to search page

### Functional testing steps:
- [x] Ensure content is indexed on /admin/config/search/search-api/index/node_index
- [x] Navigate to /admin/yalesites/views-settings
- [x] Enable *Show the Content Type filter*
- [x] Select all Content Types options and save the form
- [x] Navigate to /search page
- [x] Confirm that the search form matches [Figma Designs](https://www.figma.com/design/7dxhigoRGh80M0EOZ3wONc/Design?node-id=1390-4126&t=n2OeRfpi2ItdVmBe-0)
- [x] Perform a search action based on some text
- [x] Filter the results using the newly added "Content type" filter
- [x] Confirm that newly added filter works as expected
- [x] Verify that form markup meets accessibility requirements

Related PRs:
- https://github.com/yalesites-org/atomic/pull/258
- https://github.com/yalesites-org/component-library-twig/pull/398

### CODE REVIEW

**Review by dblanken-yale — APPROVED** [review]
Codewise looks great.  Kara has some feedback from the group she's going to post here as well.  We did notice that the Figma designs did not 100% match what was in this PR, so that's why we have the question here, but otherwise looks great.

**Comment by nplowman** [comment]
@dblanken-yale I think the only difference that I was seeing, was that we were missing the "eyebrow" field to indicate what content type a result belongs to. I'll send this back to dev to add. I'll also check with Kara to see if there were any other differences she was noticing.

**Comment by dblanken-yale** [comment]
@nplowman Yep; I just didn't know if that was going to be in a different PR or if it should be a part of this work.  I think otherwise the search PR was pretty darn good.  I think we had feedback on the Spotlight one though.  :D

**Comment by nplowman** [comment]
@dblanken-yale @kara-franco The eyebrow with the content type has been added. I think this one is ready for final review and merging now.

**Comment by dblanken-yale** [comment]
Reset so we can test eyebrow with content type.  Once approved we'll mark again.

**Review by kara-franco — APPROVED** [review]

**Pull request merged**
