### PR TITLE
YALB-1416: Bug: Empty Headings in HTML | YALB-1312: Bug: Style views Event Time Period radio buttons | YALB-1215: Dials: Banner heading levels

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- **This branch includes https://github.com/yalesites-org/yalesites-project/pull/388 and should not be merged in before it.**
- YALB-1416 - Adds conditional check for heading value in drupal block - Atomic: https://github.com/yalesites-org/atomic/pull/167
- YALB-1312 - Adds styles to temporarily theme Event Time Period until we have icons to use. Adds input names to JS file for `checked` state change on click, to provide visual feedback. Changes in this branch. 
- YALB-1215 - Adds new field for `field_heading_level` adds the field to Banners (CTA and Hero) and wires it to `heading_level` in the Storybook components. Includes component library work here: https://github.com/yalesites-org/component-library-twig/pull/285

#### Testing:  [YALB-1215: Dials: Banner heading levels](https://yaleits.atlassian.net/browse/YALB-1215) 
- [x] View this page: https://pr-407-yalesites-platform.pantheonsite.io/your-story-beautifully-told
- [x] And this page: https://pr-407-yalesites-platform.pantheonsite.io/welcome
- [x] Confirm that both Banners have an `h2`. 
Screenshot-20230829164101-1488x1218

Screenshot-20230829164339-1438x1256

- [x] Login and edit https://pr-407-yalesites-platform.pantheonsite.io/node/83/layout
- [x] Change the `heading level` to `h1`
- [x] Save and view the page and verify the heading is now an `h1`

https://github.com/yalesites-org/yalesites-project/assets/366413/77ef6029-8c49-47e6-9887-e019c58a77f9

- [x] Do the same for the home page (https://pr-407-yalesites-platform.pantheonsite.io/welcome) and verify it also renders an `h1` if you change it: https://pr-407-yalesites-platform.pantheonsite.io/node/16/layout 

Screenshot-20230829164639-2068x1199

---

#### Testing:  [YALB-1416: Bug: Empty Headings in HTML](https://yaleits.atlassian.net/browse/YALB-1416) 
- [x] Navigate to: https://pr-407-yalesites-platform.pantheonsite.io/your-story-beautifully-told
- [x] Scroll to the bottom and verify the View of Posts **does not render** a heading element on the page

Screenshot-20230829165153-1989x1319

- [x] Edit the page and add a heading, save the page
- [x] View it again and confirm the heading renders as it should

Screenshot-20230829165404-1955x1276

- [x] You can test this by adding additional Views components, as you'd like

 ---

#### Testing: [YALB-1312: Bug: Style views Event Time Period radio buttons](https://yaleits.atlassian.net/browse/YALB-1312) 
- [x] Navigate to https://pr-407-yalesites-platform.pantheonsite.io/events 
- [x] Edit the page, edit the "Upcoming Events" component  (https://pr-407-yalesites-platform.pantheonsite.io/node/39/layout) and verify: 
  - [ ] The Time Period radios are _temporarily_ styled so that each radio element doesn't take up a lot of space
  

https://github.com/yalesites-org/yalesites-project/assets/366413/2becb8b9-36cc-4a06-994e-f1d1f577fed5

And if you add a new Views Events block: 

https://github.com/yalesites-org/yalesites-project/assets/366413/c4dc4e5c-800e-4d92-84c0-f0941539341b

### CODE REVIEW

**Review by dblanken-yale — APPROVED** [review]
This all looks so good.  I did have one question about the events.  I'm still seeing the radio button circle selectors on the events, but not in the other selectable radio button items.  Should we hide them as well--they look hidden on the other radios on that configuration?  If not, I think this is ready!  If it is, feel free to re-request review and I'll be happy to.

Great work!

Screenshot 2023-08-30 at 11 17 19 AM

**Review by codechefmarc — CHANGES_REQUESTED** [review]
YALB-1416: Approved

YALB-1312: Approved, but wanted to find out if this was going to get an icon ahead of getting merged? Looks good to merge now and we can always add the icon later.

YALB-1215: I'm seeing a "None" option and I checked and there is a different way we're handling those dial fields. Mainly using the `allowed_values_function` and `default_value_callback` in the configs themselves. It's not something you can set in the Drupal UI, but in code. I can help if you'd like, or you can reference these guys (specifically the `field_style_color` on the callout component: 

* `web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml`
* `web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.callout.field_style_color.yml`
* `/Users/marcberger/4K/Projects/YaleSites/yalesites-project/web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_style_color.yml`

**Comment by joetower** [comment]
@dblanken-yale Those radios for "Event Time Period" should look like the other Radios in the Views Basic form. 

Screenshot-20230830161538-1264x1162


---

@codechefmarc I tried rebuilding what we were working on - moving the `field_heading_level` allowed values to our `component_overrides` and it didn't work. If you'd like to look at it in this branch, awesome, otherwise we could create a follow up ticket. What do you think?

**Comment by joetower** [comment]
Well, once it finishes building. I hit comment too soon :laughing:

**Comment by nJim** [comment]
> YALB-1215: I'm seeing a "None" option and I checked
@codechefmarc @joetower I have a ticket this sprint to address this. If you like, feel free to make the field required and set a default value in the field UI. I don't know if this will be the final fix, but it cleans up any confusion right now.

**Comment by joetower** [comment]
@codechefmarc This is ready for another look, please. 

- For YALB-1215: I made the `field_heading_level` required for both banner types :+1: 
- For YALB-1312: I added icons for the Event Time Period
  - I added them in the way we discussed on the Footer Menu Block ticket. I noticed the other form inputs in this Views-Basic aren't using that same pattern. 
  - pattern example: 
   ```'#options' => [
        'future' => $this->t('Future Events' . '<img src="/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/icons/event-time-future.svg" alt="Future Events icon showing a calendar with a future-pointing arrow to the right.">'),```
 
 - Should we create a tech debt ticket to change those, or no? 
 
 If you add a new Views -> Event component you should see: 
 

https://github.com/yalesites-org/yalesites-project/assets/366413/30210c77-546d-480a-8c6e-3a82c7c44136

**Comment by codechefmarc** [comment]
@joetower - yup, that will work, but, in researching yesterday I found a better way to do this that will be easier for translators in that the image isn't inside the translated text:

```
'basic' => $this->t('Basic') . '<img src="/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/footer-basic.svg" alt="Basic footer icon showing a small Yale logo, and gray placeholders for copyright and social media icons.">',
```

And yes, I really like this idea much better than doing it in a background image, so we should create a tech debt ticket to change out all of them - it seemed it was much easier for you to style as well.

**Review by codechefmarc — APPROVED** [review]
Approved for the work listed here. However, I mentioned in Slack that I noticed the main nav isn’t rendering correctly on that multidev. I think that is related to work just merged in for the first level links as headings?
Capture-2023-09-06-111822

**Comment by dblanken-yale** [comment]
@codechefmarc I tested this on my PR and it's due to atomic's changes not being in release versions yet.  If you make a branch mirroring this one from develop and rebuild, it shows fine.  No worries there.

**Pull request merged**
