### PR TITLE
JAKALA: Theme Dial for Grand Hero

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Description of work
- This pull request adds a theme dial to the "Grand Hero" block type, allowing you to choose different background colors on Hero Banners. 
- These options were already available in Storybook via the Controls toolbar - we are just adding a new field in Drupal that allows you to apply these different options. 

### Functional testing steps:
- [ ] Create a new Page node
- [ ] Add a "Grand Hero" block on the Layout and Content screen.
- [ ] Note on the Edit Form that there is a new field called "Theme", with options "One", "Two", and "Three"
- [ ] Try choosing between the different theme options 

### Screenshot with Grand Hero examples
screencapture-pr-738-yalesites-platform-pantheonsite-io-hero-banner-test-2024-08-26-13_50_00

### CODE REVIEW

**Comment by nplowman** [comment]
@dblanken-yale @kara-franco I think this pull request is ready for final review and merging

**Comment by nplowman** [comment]
Noting that we will need to go back and make sure that Theme Options "Four" and "Five" to the theme dial after the Color Palette updates are merged. #745

**Review by kara-franco — CHANGES_REQUESTED** [review]
Nice job, the new variations look great. One item we found is that when using the other Theme's (non-ONHA themes), the colors are not coming through. Dave even tested after rebasing and the display issue was still present: 

- [ ] Non-ONHA colors not displaying
Screenshot 2024-09-09 at 2 35 32 PM

**Comment by nplowman** [comment]
@kara-franco It looks like the code that adds the support for Theme options "four" and "five" for the non-ONHA themes is on the Color Palette pull request, but it should be working once we have both of these pull requests merged.

I have a multidev environment that has all of the ONHA-related work merged together in one place, and you can see it working here if you'd like: https://pr-747-yalesites-platform.pantheonsite.io/ 
(We'll be using this environment for a demo next week, so just make sure to change the Color Palette back to ONHA  once you are done testing).

**Comment by nplowman** [comment]
@kara-franco @dblanken-yale It looks like the "four" and "five" options are working now with the latest merge from develop that Dave just did. I think that should unblock final review for this now.

**Review by atiddei — APPROVED** [review]

**Review by kara-franco — APPROVED** [review]

**Pull request merged**
