### PR TITLE
YALB-988: Override Gin colors and typography

### PR DESCRIPTION
**Pull request by mariannuar**
### Description of work
- Override gin colors and typography.
- Updates modal design to use theme primary color choices

### Functional testing steps:
- [ ] [Log in](https://pr-254-yalesites-platform.pantheonsite.io/user/login)
- [ ] Go to the `Content Administration` or any admin section
- [ ] Confirm everything looks as similar as possible to the [designs](https://www.figma.com/file/CrE2jOK5R1BYZJ0EzfGnHr/YaleSites-AX-UI-Designs?node-id=527-158&t=gXyWIiYjDoy8CpfD-4)
- [ ] Confirm everything looks as similar as possible to the design
- [ ] Test and make sure modals look as they should 
Screenshot-20230510104433-2550x1316

### Notes
- Just in case, I had to injected a css file in the atomic theme because when you are viewing or editing the layout of a node, the css styles added in the `ys_admin_theme` didn't override the gin colors and typography. I tried to find other places, like in the `ys_toolbar`, but it didn't work... Those styles are included in this [PR](https://github.com/yalesites-org/atomic/pull/117)

### CODE REVIEW

**Comment by joetower** [comment]
@ahitson Could you please give this a look? I'll Slack you a login URL for https://pr-254-yalesites-platform.pantheonsite.io/

**Comment by joetower** [comment]
@mariannuar This is looking great! 

I'm going to keep reviewing, but the one thing I noticed is that the `dark` theme doesn't seem to be staying in place for me when trying to select it here: https://pr-254-yalesites-platform.pantheonsite.io/admin/appearance/settings/gin. It looks like it applies correctly, but when I save, it's not staying in place.  



https://user-images.githubusercontent.com/366413/235756351-45c09ca0-8b4a-49de-966a-5947e2ba52a6.mp4

**Comment by joetower** [comment]
@mariannuar It also appears as though custom color selections aren't saving. :thinking: . 

https://user-images.githubusercontent.com/366413/235761034-172f3352-34ca-4226-8097-5fa75e23a3fb.mp4

**Review by joetower — CHANGES_REQUESTED** [review]
@mariannuar This is great work, thank you so much! 

I noticed (and commented about above) a couple of issues with not being able to save `dark` mode and the theme settings not saving your custom color selection. 

I'll leave a couple other comments on specific files.

**Comment by joetower** [comment]
@mariannuar One other thing I noticed is that we should increase the contrast of these elements on the page, when `dark` mode is selected.

**Comment by ahitson** [comment]
Three things (skipping dark mode for now while it gets adjusted):
1. Couple of places where the font is the old style. Like in the editor.
Screen Shot 2023-05-02 at 3 01 46 PM
Screen Shot 2023-05-02 at 3 01 36 PM
Screen Shot 2023-05-02 at 3 00 17 PM

2. There is one color that's sneaking into places that isn't in the palette. Thinking it should be wool instead. (you can also see it behind the button up top at the bottom of the modal)
Screen Shot 2023-05-02 at 3 00 46 PM
Screen Shot 2023-05-02 at 2 57 56 PM


3. The glow behind the primary button looks odd to me. It was like that in gin and thought it was weird there, too. Would like to just remove it.
Screen Shot 2023-05-02 at 2 56 37 PM

**Comment by joetower** [comment]
@ahitson This is ready for another look, please. 

https://pr-254-yalesites-platform.pantheonsite.io

I'll Slack you another link to login.

**Comment by joetower** [comment]
@ahitson Also, the changes I made include https://yaleits.atlassian.net/browse/YALB-987 modals, as well. :+1:

**Comment by ahitson** [comment]
- Layout builder seen when editing the page layout is using the old font.
- Text in modals of components needs updated font
- Title bar text colors are wrong, needs to be white text.
- The backgrounds behind the wool lists on manage pates, etc, are #f9fbfe which has a purple tint, but should be #FCFEFE with more of a blue tint.
Screen Shot 2023-05-10 at 9 35 11 AM
Screen Shot 2023-05-10 at 9 41 09 AM
Screen Shot 2023-05-10 at 9 43 04 AM
Screen Shot 2023-05-10 at 9 43 53 AM
Screen Shot 2023-05-10 at 9 48 06 AM

**Comment by joetower** [comment]
@ahitson This is ready for another look. Each of the items you mentioned should now be fixed. 

Also, after conversation with Jim in Slack, I have removed the custom admin dark mode styles for the time being.

**Review by nJim — APPROVED** [review]
Approving from a code and functional point of view. I will leave it to Ashley to decide if we've are staying true to her design vision.

**Review by joetower — APPROVED** [review]

**Pull request merged**
