### PR TITLE
YSP-458: Editorial Workflow: Display improvements to right panel

### PR DESCRIPTION
**Pull request by codechefmarc**
### Description of work
- Adds styling for the new moderation sidebar
- Adds styling for the moderation form when nodes are in a draft state

### Other repos needed for this PR:
- https://github.com/yalesites-org/atomic/pull/224
- https://github.com/yalesites-org/component-library-twig/pull/360

### Functional testing steps:
- [ ] Login to the multidev and visit the front-end of any node
- [ ] Click on the workflow menu in the top right

Screenshot 2024-04-23 at 3 07 12 PM

- [ ] After the sidebar menu opens, verify that there is a new font and new colors that match the Yale theme. Note, there was a mention in the ticket about "Match the reds to our Theme reds" - not sure exactly which those are as I didn't see any reds in the design system, but I did see a `--gin-color-danger` variable that was red and I used that for the "Delete content" button.

Screenshot 2024-04-23 at 3 07 51 PM

- [ ] Click on "Show revisions" 
- [ ] Verify that there is a border between each revision to help delineate them

Screenshot 2024-04-23 at 3 13 25 PM

- [ ] Create a new page, add a title, and click "Create New Draft".
- [ ] Save layout builder layout, no need to add blocks to test the next piece.
- [ ] At the top of the page, verify that the moderation toolbar has some new styling. Mainly that the box is now centered, and the button will match the front-end button theme of the site.

Screenshot 2024-04-23 at 3 19 36 PM

### CODE REVIEW

**Comment by miketullo95** [comment]
@codechefmarc this looks great! can we do some small label changes so the sidebar matches the admin toolbars. Can we change "Edit content" -> "Manage Setting" and "Layout" -> "Edit Layout and Content"? 

Other than that, this can be approved! 😄

**Review by dblanken-yale — APPROVED** [review]
I'll probably defer to @kara-franco but when I test dark mode, The Show revision buttons and the like seem to be failing at 4.478:1.  I didn't know if there was another gin color we use elsewhere that could pass it or not.  Otherwise this is looking great!
Screenshot 2024-05-02 at 4 42 05 PM
Screenshot 2024-05-02 at 4 42 19 PM

**Comment by codechefmarc** [comment]
@miketullo95 - No problem, I changed the button text to match the other buttons.

@dblanken-yale - I changed the background color of the buttons so the contrast now passes accessibility tests.

**Review by dblanken-yale — APPROVED** [review]
Perfecto!  Passes 🕺  Nice work.

**Pull request merged**
