### PR TITLE
YALB-447: Configure text formats

### PR DESCRIPTION
**Pull request by ModulesUnraveled**
### Description of work
- Configures text formats
- Updates wysiwyg filters and settings for all paragraph types

### Functional testing steps:
- [ ] [Log in to the site](https://pr-27-yalesites-platform.pantheonsite.io/user/login) (this is the same site that you'll use to review the Wysiwyg formats PR)
- [ ] [Create a page](https://pr-27-yalesites-platform.pantheonsite.io/node/add/page)
- [ ] Add one of each paragraph type (don't forget the hero behind the hero tab) and verify the text formats (and allowed wysiwyg buttons) all make sense.
- [ ] Note your thoughts and opinions etc.

### Design Review
- [ ] Verify the designs match the [Figma Designs](https://www.figma.com/file/OVfmCW5s1gI7xnrM8ibX2y/UI-Kit-Alpha-%5BYaleSites%5D)

### Accessibility Review
- [ ] Verify the experience meets Accessibility requirements

### CODE REVIEW

**Review by callinmullaney — CHANGES_REQUESTED** [review]
@ModulesUnraveled The `Teaser text` and hero banner text fields seem like they have too many formatting options. Do we want authors to be able to add headings/tables to these fields?

That being said, Sous has a similar setup that may be helpful to replicate or take inspiration from. Here is what that config does:
1. Full HTML: Pretty much the same options you have set for the Basic but it will only strip out things like `iframes` and `script` type html. This is likely only used for Text components that need a wide range of format options.
2. Basic: Same `Limit allow html...` as your current configuration but doesn't allow for things like blockquotes and tables. Used as the default format for any component that needs formatted text. Best used for formatted text areas that are coupled with other elements like `Text with Media` (we don't want them injecting tables into this component)
3. Restricted: Same limited options as your Heading. Used for headings but also teaser text fields and potentially other components that need limited formatting like card text or hero banner text.

**Comment by miketullo95** [comment]
looks great! I did notice that using the block quote style in the WYSIWYG editor has style effects in the back end, but does not transfer over to FE.

backend
Screen Shot 2022-05-06 at 3 49 06 PM
frontend
Screen Shot 2022-05-06 at 3 49 46 PM

**Review by kara-franco — APPROVED** [review]
In my brief review, I did not see any WYSIWYG issues (I've actually learned there is a keyboard shortcut for getting to the CKEditor Toolbar- I'll suggest we add the instructions in to the interface). 

- [ ] Suggest adding instructions on how to use toolbar with keyboard in UI.
Screen Shot 2022-05-06 at 5 31 02 PM

**Comment by ModulesUnraveled** [comment]
I have created tickets for the items above, merging to unblock future work.

**Pull request merged**
