### PR TITLE
YSP-559: Upgrade Node Packages

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Updates node to v20
- Updates tooling to use node 20
- Updates packages
- Utilize linkpurpose
- Fix mega footer link color
- Fix single card event date color

### Functional testing steps:
- [ ] Verify there are no glaring issues when navigating https://pr-679-yalesites-platform.pantheonsite.io/
- [ ] Locally you can test by removing all the `node_modules` directories from each repository - component library and atomic, and running `nvm use` and/or `npm install` to use node 20, then `npm install` on each to install the updated packages.
- [ ] For Card external link styling adds spacing with the right amount of characters, I clones their page for us to test against: 
  - [ ] [Test Page 1](https://pr-679-yalesites-platform.pantheonsite.io/instructional-tools)
    - [ ] Resize and notice that the arrow no longer hangs off the side and stays with "Browser"
  - [ ] [Test Page 2](https://pr-679-yalesites-platform.pantheonsite.io/people)
    - [ ] Resize and notice that the arrow now follows the last name and doesn't dangle.
- [ ] Ensure mega footer is selected for the site and add a link inside of the content (make categories of links also)
  - [ ] Verify that when looking at the link in the page, it has proper contrast for visited and non-visited
  - [ ] Ensure when resizing that links stack

### CODE REVIEW

**Review by codechefmarc — APPROVED** [review]
@joetower - I tested this locally - switched to the branch for all three repos, deleted `node_modules` folder, and then had to install the new node on my computer `nvm install 20.14.0` and then ran `nvm use` and then `npm install` for each repo.

All of that worked!

Then, I ran through a normal setup of the site like I usually do for local dev: `npm run build-with-assets` and then `npm run local:cl-dev`. The first part worked. The second part worked for the most part, but got hung up after the message `webpack 5.92.0 compiled successfully in 13644 ms` and didn't complete. No errors though.

After realizing the branch on Atomic got reset to a commit hash of some sort, I put that back to this branch (`YSP-559-update-npm-packages`) and re-ran `npm run local:cl-dev` and all worked great! A lot less deprecation messages now, though there still are some that are left.

**Review by dblanken-yale — APPROVED** [review]
I think I ran into a similar issue as @codechefmarc; I had a question for him so I could learn how he got it all working with just `npm run setup` without having to point to forked branches.  I was able to get it all working after a `npm run setup` and then `git-checkout` on those specific branches--no errors.  Since this does similar to what setup does, I think this will work and I trust Marc's review.  😁

Again, nice work getting all of these working.

**Comment by dblanken-yale** [comment]
Got it up to date with latest release and got ys_links working in this one for now till we migrate out.  Would appreciate another PR look.  We're going to wait for just a little to get this in since we need some ai_engine releases out before it can go in.  Hoping after Monday we can get it in.

**Comment by miketullo95** [comment]
@dblanken-yale is there any specific use cases we should focus on here?  maybe treat this as a kinda release and try all most common features?

**Comment by dblanken-yale** [comment]
Yes, since this affects all blocks, we'll want to make sure all is looking well in all of them.

**Comment by dblanken-yale** [comment]
This has been incorporated into the D10.3 evaluation.  Closing.

**Pull request closed without merging**
