### PR TITLE
YALB-1691: Bug: Min/max referenced items in reusable block

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Description of work
- Adds the ability to use multiple itemSelectors to target different pages needing validation
- Script now attaches to buttons only once

### Functional testing steps:
For the following blocks, test both local and global versions that they adhere to the min/maxes conveyed in their help text:
- [ ] Tabs
- [ ] Quick Links
- [ ] Media Grid
- [ ] Gallery

For this, double check the addition of it:
- [ ] Correctly, without any errors
- [ ] With the number of items below the min
- [ ] With the number of items above the max
- [ ] With a combination of adding/removing items to test where the errors lay
- [ ] By expanding/collapsing certain items so that different inputs are/aren't present in the form when the errors occur

### CODE REVIEW

**Comment by dblanken-yale** [comment]
Does anyone have more context on the gin_lb patch that was applied as part of this JS originally?  I looked back at the commit and it gave no more insight.  In any event, they've completely changed the implementation of this array that was patched, so no patch exists currently.  Items seem to be working well without it, so I was wondering what it was fixing for us.

* [My commit removing](https://github.com/yalesites-org/yalesites-project/pull/560/commits/e2e00880a5d517dae7957b35f361562bed374f92)
* [Original commit](https://github.com/yalesites-org/yalesites-project/commit/996a2317d5b6249da3c7c82d4f831e6de2f43e66)

**Comment by codechefmarc** [comment]
@dblanken-yale - I found Laura's original comment on the module issue page here: https://www.drupal.org/project/gin_lb/issues/3387157#comment-15380437 Looks like the test is a layout builder block referencing paragraphs with sub-items so Accordion, tabs, and callouts would be the ones to test. I can test those when I test this PR.

**Comment by dblanken-yale** [comment]
@codechefmarc That's what I thought it was, but I couldn't recreate the error.  My hope is that the new dev implementation fixed that?  But if we're pinning, it might be back.  I'm going to resolve the branch conflicts and try again here.

**Review by codechefmarc — CHANGES_REQUESTED** [review]
This is much better! I tested out each of the different scenarios with reusable and not. All of it worked great!

The only issue I ran into is unrelated to your work, but was probably one of the branches being out of date -I did notice the admin styling is wonky, but that's probably because the admin styling PR was just released?

Screenshot 2024-02-12 at 11 50 44 AM

**Comment by dblanken-yale** [comment]
@codechefmarc Yep, I bet that's it and I didn't create branches for atomic/CL, so they'd still be using the last released version.

**Comment by dblanken-yale** [comment]
Let me build those real quick so we can get the real feel.

**Comment by kara-franco** [comment]
I'm not able to access Layout Builder with the PR link: 

Screenshot 2024-02-13 at 12 15 07 PM

**Comment by dblanken-yale** [comment]
Built and ready to review again.  :D

**Comment by codechefmarc** [comment]
Ugh, hate to do this, but, it's still not working for me on the multidev (Admin labels are white on white). And now the secondary tab bar is also white on white now:

Screenshot 2024-02-14 at 4 34 39 PM

I tried locally using `develop` for both `atomic` and `component-library-twig` and that worked fine. But, locally, if I switched my `atomic` and `component-library-twig` to the new branch `YALB-1691-bug-min-max-referenced-items-in-reusable-block` it stopped working locally too. I would troubleshoot further, but I'm running low on hours for YaleSites and I'd like to take a look at the other PR's.

**Comment by dblanken-yale** [comment]
Ah!  You're in light mode!  I was in dark mode.  Let me see what could be doing it.

**Comment by miketullo95** [comment]
one dark mode related note, i'm not sure if this was brought up yet, but only on a node (not in /edit) the very top bar is the old style 
Screenshot 2024-02-15 at 9 39 47 AM

**Comment by miketullo95** [comment]
however, functionally, the min/max stuff is great. this is a huge improvement for AX

**Comment by dblanken-yale** [comment]
Yay finally updated to latest atomic and toolbar should show just fine.  Thanks again @joetower !

**Review by miketullo95 — APPROVED** [review]
👍

**Review by codechefmarc — APPROVED** [review]
There we go, tested again and all looks good now!

**Review by kara-franco — APPROVED** [review]
Tested again and it works great, nice work!

**Pull request merged**
