### PR TITLE
Layout Sections and Profiles

### PR DESCRIPTION
**Pull request by codechefmarc**
## Tickets
- [YALB-85: Profile: Build content type](https://yaleits.atlassian.net/browse/YALB-85)
- [YALB-1380: Bug: Title and Author not shown for Post](https://yaleits.atlassian.net/browse/YALB-1380)
- [YALB-1420: Bug: sections and column layout options showing in events](https://yaleits.atlassian.net/browse/YALB-1420)
- [YALB-1437: Create two-column layout section (BE)](https://yaleits.atlassian.net/browse/YALB-1437)
- [YALB-1438: Create Profile-Banner/Meta block (BE)](https://yaleits.atlassian.net/browse/YALB-1438)
- [YALB-1439: Create Event-Meta block (BE)](https://yaleits.atlassian.net/browse/YALB-1439)
- [YALB-1441: Create profile contacts block (BE)](https://yaleits.atlassian.net/browse/YALB-1441)
- [YALB-1459: Profile Sections](https://yaleits.atlassian.net/browse/YALB-1459)
- [YALB-1475: Bug: build-with-assets creates ViewBasicManager errors on site](https://yaleits.atlassian.net/browse/YALB-1475)

### Description of work
- Adds profile content type, associated fields, permissions, and layout section settings
- Adds meta blocks for pages, posts, events, and profiles
- Adds contact block for profiles
- Updates layout builder sections to use new meta blocks for existing pages, events, and posts
- New settings should also work on new pages, events, and posts

### Functional testing steps:
- [x] Login as a site administrator role - do not test with platform admin or user 1
## Pages
- [x] Enter layout builder on an existing page
- [x] Verify that there is a title block at the top and that it is not editable
- [x] Scroll to the bottom of the components and verify that there is an "Add section" button

Screenshot 2023-07-25 at 5 15 05 PM

- [x] Click the "Add section" button and add a section of type "Two column"
- [x] Add whatever administrative label you wish and click "Add section" at the bottom
- [x] Verify that a two column layout was added

Screenshot 2023-07-25 at 5 15 44 PM

- [x] Add some items to the "Content" region and to the "Sidebar" region of the two column layout.
- [x] Verify that the only item you can add to the sidebar is "Text"
## Events
- [x] View an existing event
- [x] Verify that the top "Event Meta" section shows up

Screenshot 2023-07-25 at 5 17 17 PM

- [x] Enter layout builder
- [x] Verify that the "Event Meta" section still shows, but is not editable
- [x] Edit the event (Manage settings toolbar link)
- [x] Change some information about the event like the dates, "in person/online", and call to action.
- [x] Save and verify that the new information shows up on the event meta section.
- [x] Verify that the "Add to calendar" link works correctly
## Posts
- [x] View an existing post
- [x] Verify that the top "Post Meta" section shows up with a title and date (and author if one is set)

Screenshot 2023-07-25 at 5 18 01 PM

- [x] Enter layout builder
- [x] Verify that the "Post Meta" section still shows, but is not editable
- [x] Edit the post (Manage settings toolbar link)
- [x] Add an author if one does not exist
- [x] Save and verify that the author shows up in the post meta section next to the date
## Profiles
- [x] Create a new profile
- [x] Enter in information for the profile like the department, position, subtitle, email, phone, address, and a photo in the media field.
- [x] Save and enter layout builder
- [x] Verify that the profile meta section shows up on top
- [x] Verify that there is a two column layout on the page already
- [x] Verify that the contact info section shows up in the sidebar

Screenshot 2023-07-25 at 5 20 54 PM

- [x] Verify that you can add a new section of either one column or two column
- [x] Verify that you can remove the contact block if you wish
- [x] Verify that the only blocks you can add to the sidebar are the contact info and text blocks.
- [ ] Save the layout and verify that the design matches the [Figma designs here](https://www.figma.com/proto/G4sJ0BLu4jCJpGzW82JHE8/YaleSites-Components?type=design&node-id=8239-26457&scaling=min-zoom&page-id=8239%3A26166)

### CODE REVIEW

**Review by dblanken-yale — CHANGES_REQUESTED** [review]
When I attempt to go into layout builder for [a previously made event](https://pr-363-yalesites-platform.pantheonsite.io/events/2025-05-31-event-series-promote-your-event), I'm getting an [unexpected error message](https://pr-363-yalesites-platform.pantheonsite.io/admin/reports/dblog/event/969).  ☹️

`TypeError: Drupal\layout_builder\Access\LayoutBuilderAccessCheck::access(): Argument #1 ($section_storage) must be of type Drupal\layout_builder\SectionStorageInterface, null given in Drupal\layout_builder\Access\LayoutBuilderAccessCheck->access() (line 35 of /code/web/core/modules/layout_builder/src/Access/LayoutBuilderAccessCheck.php)`

At first I thought it may be due to me being a platform admin and not a site admin, so I verified and changed myself, but it still is happening.  ☹️  I even did a remote cache clear.

**Comment by codechefmarc** [comment]
@dblanken-yale - Good catch. This is happening on some of the events, but not all of the events, how odd! I'll poke at it after standup and see what is happening there. I seem to recall there is a patch for core that may fix this.

**Comment by dblanken-yale** [comment]
I also noticed that the [contact info section](https://pr-363-yalesites-platform.pantheonsite.io/node/88) is throwing editora11y header issues since it's an h3.  That might be a component issue though.

Everything else is working as intended!  Nice job!

**Comment by joetower** [comment]
@codechefmarc This is looking great!

I pushed up a template for the profile-meta block to remove a wrapping `div`. 

I have one question: 
- For the profile nodes, can we add the profile-meta block to the `banner` region instead of the `content `region?
- This way, this block should inherit the spacing logic from the banner region on other content so it won't look like this:
Screenshot-20230726120951-2481x1349

**Comment by joetower** [comment]
@codechefmarc Also, a couple other notes, example Profile here https://pr-363-yalesites-platform.pantheonsite.io/node/89: 
- should we configure a pathauto pattern for Profiles? https://pr-363-yalesites-platform.pantheonsite.io/node/89 
- we should remove Quick Links from the primary column of allowed components
- I question the inclusion of the Custom Cards and the Media Grid/Gallery, they render okay but a bit squished. Thinking we can include them for now and follow up with a ticket to pass different attributes to each component so they better fit the narrower column. For example, use the same values used on Event or Post nodes.

**Review by joetower — CHANGES_REQUESTED** [review]
Added some feedback items to consider. 

I also pushed up some frontend updates here and in https://github.com/yalesites-org/atomic/pull/156. 

Wrapped the contact info block in a block-wrapper component and used its block-wrapper__label to get the correct block heading font. 

Please take a look and my additions and make sure they look good to you. Thanks!

**Comment by dblanken-yale** [comment]
@codechefmarc Unfortunately I'm still getting an error when attempting to edit some events.  I am able to proceed with the Event Link Testing event as it loads, but the Master Sculptor does not work for me.  :(

**Review by dblanken-yale — APPROVED** [review]
It works!!!!!  Nice job!!!!!

**Comment by miketullo95** [comment]
@joetower I would say probably no for quick links. I added one and it doesn't look like it could fit even with some changes. Looking at the rest of the list, I feel like the rest of the blocks should be good.

**Review by joetower — APPROVED** [review]
@codechefmarc I confirmed that the options for two-column layout primary region now include those outlined in the theming ticket. That looks great, thanks!

I pushed up a fix to the atomic branch for the profile breadcrumbs and left a note in that PR. Please give my change a look. Otherwise this is looking good to me!

**Comment by miketullo95** [comment]
Quick bug found: I added a second contact info block in the right side, then tried to remove that block (or even the original one) and they cannot be deleted.

**Comment by codechefmarc** [comment]
Great find @miketullo95! I've fixed that issue and it's on the multidev.

**Comment by joetower** [comment]
@codechefmarc @miketullo95 I pushed a fix to this branch (in Atomic) for the section visual borders. 

If you test on this multidev: https://pr-363-yalesites-platform.pantheonsite.io and login and edit this example Profile: https://pr-363-yalesites-platform.pantheonsite.io/node/98/layout, you should see the following: 

https://github.com/yalesites-org/yalesites-project/assets/366413/6370796a-9d89-4f45-939a-de8520390296


Please let me know what you think Mike. :+1:

**Comment by codechefmarc** [comment]
@joetower - That looks really nice!

**Comment by miketullo95** [comment]
@joetower agree with marc, this looks great! Quick question, the admin styles for the tabs in /edit on a profile needs updating. Is that suitable for this PR or your other open PR for admin fixes? 
Screen Shot 2023-08-11 at 9 17 27 AM

**Comment by joetower** [comment]
@miketullo95 I pushed a fix for that in a related branch here: https://github.com/yalesites-org/yalesites-project/pull/371#issuecomment-1672158207

Please take a look at that comment and let me know what your thoughts are. Thank you!

**Comment by miketullo95** [comment]
oooh, i see! apologies, both look great! 👍

**Pull request merged**
