### PR TITLE
fix(YSP-526): V1.3.0: Reference Card Label Change

### PR DESCRIPTION
**Pull request by dblanken-yale**
## [YSP-526: V1.3.0: Reference Card Label Change](https://yaleits.atlassian.net/browse/YSP-526)

After reviewing the naming of the fields of the reference card, it was determined that Content was not as informative than something like 'Reference source'.  This change renames 'Content' to 'Reference source', and adds help text to help the user know what the use of it is.

### Description of work
- Renames `Content` to `Reference source` for reference card block in Drupal
- Adds help text to the field for `Reference source`

### Functional testing steps:
- [ ] Attempt to add a reference card block
- [ ] Verify that the label of the field shown is not `Content`, but instead `Reference source`
- [ ] Verify that the help text is displayed
- [ ] Verify that you can successfully create a reference card block

### CODE REVIEW

**Review by miketullo95 — APPROVED** [review]
tested and looks good!

**Review by kara-franco — APPROVED** [review]
Looks great!

**Review by codechefmarc — APPROVED** [review]
Tested as well, approved!

**Review by nJim — APPROVED** [review]
Approved. In the future, please also update the [data model](https://yaleedu.sharepoint.com/:x:/r/sites/YaleSitesUpgradeProgram/_layouts/15/Doc.aspx?sourcedoc=%7B2B574C06-BAC3-41E2-924A-F4562054F849%7D&file=Proposed%20Content%20Model.xlsx&action=default&mobileredirect=true&wdOrigin=TEAMS-ELECTRON.teams.files&wdExp=TEAMS-CONTROL&wdhostclicktime=1644421397192) to keep our documents in sync. I got this one as it's an easy change.

**Pull request merged**
