### PR TITLE
YSP-427 - Hero Banner breadcrumb issue

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- If a `.page-title` is not visible on the page, add a body attribute `[page-title-hidden="true"]`
- If a `breadcrumbs__wrapper` appears inside of a `[page-title-hidden="true"]` attribute add bottom margin to it so content below doesn't render against it.
- This PR adds a new library for `page-title`

### Testing Link(s)
- [ ] Test here: https://pr-620-yalesites-platform.pantheonsite.io/generic-homepage/generic-about-page

#### Other repository PRs
- [ ] Atomic PR here: https://github.com/yalesites-org/atomic/pull/218
- [ ] Component Library PR here: https://github.com/yalesites-org/component-library-twig/pull/348

--- 

- [x] Navigate to https://pr-620-yalesites-platform.pantheonsite.io/generic-homepage/generic-about-page
- [x] Verify there is space between the `breadcrumbs__wrapper` and the element which comes below it. 
- [x] Inspect the `body` of the site, confirm you see an attribute for `[page-title-hidden='true']`

https://github.com/yalesites-org/yalesites-project/assets/366413/74040aa9-e156-4d7a-85e2-9c9801e30bc3

- [x] Edit the node and change the Page Title to `Visually Hide Title` instead of `Hide Title`
- [x] Save and test the node changes - confirm that the body attribute _is_ in place (`[page-title-hidden='true']`) if the Page Title is set to either `visually-hidden` or `hidden` 

https://github.com/yalesites-org/yalesites-project/assets/366413/251e489c-7586-41a0-9e14-6bc81ccd738a

- [x] Edit and change it again to `Display title`
- [x] Confirm that if the Page Title is set to `display` the body attribute _is not_ in place.

---

### Possible improvement
- [ ] @codechefmarc As you review please check if we can move the attribute addition from JS to a preprocess function.

### CODE REVIEW

**Review by dblanken-yale — APPROVED** [review]
Nice work.  I'll let @codechefmarc chime in on your request, but works as we wanted.

**Review by miketullo95 — APPROVED** [review]
looks good to me! 👍

**Review by kara-franco — APPROVED** [review]

**Review by codechefmarc — CHANGES_REQUESTED** [review]
Just a note to remove the `attach_library` in the templates if that `page-title.js` isn't going to be used anymore after I added the preprocess function. This applies to Drupal only, correct? Since there is no preprocess, that JS is still needed in the component library?

**Comment by joetower** [comment]
@codechefmarc Thank you, I removed those now 👍

**Pull request merged**
