### PR TITLE
Sync secrets for local use

### PR DESCRIPTION
**Pull request by vinmassaro**
### Description of work
- Syncs secrets from Pantheon for local use, using new `secret:site:local-generate` terminus secrets manager command
- Adds `CUSTOMER_SECRETS_FAKE_FILE` lando env var now supported by [customer-secrets-php-sdk](https://github.com/pantheon-systems/customer-secrets-php-sdk)

### Functional testing steps:
- [ ] Clone branch and run `npm run setup`, or delete `.lando.local.yml` and re-run `npm run setup` on an existing local setup
- [ ] Verify that `secrets.json` exists locally and is gitignore'd
- [ ] Log into generated site as user 1, visit `/admin/config/people/captcha/examples` and verify that the recaptcha v2 example loads. If it loads with no error, secrets are being loaded correctly.

### CODE REVIEW

**Comment by codechefmarc** [comment]
@vinmassaro - I'm getting some errors on local when loading pages that have the webform about `Undefined array key "Secrets"` I assume that will be fixed with this PR?

**Comment by vinmassaro** [comment]
@codechefmarc Yes, this PR is still in draft because it is dependent on this PR: https://github.com/pantheon-systems/customer-secrets-php-sdk/pull/13

**Comment by dpagini** [comment]
> I'm getting some errors on local when loading pages that have the webform about Undefined array key "Secrets" I assume that will be fixed with this PR?

@codechefmarc I'm getting this same error as well and I'm pulling my hair out trying to track down what's going on with this...  have you had any luck?

**Comment by dpagini** [comment]
Hi @vinmassaro - Sorry to comment on your repo here, I know it's a little unrelated, but it's where I found the `"Undefined array key 'Secrets'"` message in the comments above.
So I'm actually on a simple LAMP stack locally, and I manually placed a file at `/tmp/secrets.json`, and it has a structure like the below, but I **am still getting** this undefined error... and I actually can't get a breakpoint to fire when the error shows up, so I'm a bit puzzled.

My `/tmp/secrets.json`:
```
{"Secrets":{"secret1":{"Value":"abcdefg","Type":"web","Scopes":[]},"secret2":{"Value":"hijklmn","Type":"web","Scopes":[]}}}
```

So I guess I see why this PR helps for your site... and maybe @codechefmarc is hitting that error b/c he doesn't have the file at `/tmp/secrets.json`?

**Comment by dpagini** [comment]
j/w, is `$ terminus secret:site:local-generate` a locally defined command? Or where is that from?

**Comment by vinmassaro** [comment]
@dpagini the command comes from v1.2.2 of [Terminus Secrets Manager Plugin](https://github.com/pantheon-systems/terminus-secrets-manager-plugin/)

I believe your format of secrets.json is incorrect. That is the format used by the deprecated [Terminus Secrets plugin](https://github.com/pantheon-systems/terminus-secrets-plugin). Upgrade to the latest v.1.2.2 and generate a new copy using the command above.

For further support, you can try the `#secrets-management` Pantheon slack channel. Good luck!

**Comment by codechefmarc** [comment]
Yup, I think once this PR has been merged (no rush from me), I'll be solved with the error messages on my local.

**Comment by dpagini** [comment]
Sorry again, @vinmassaro... figured I would throw a comment here in case anyone else ends up here like I did b/c of the error message...
So the problem I just ran into is that PHP/Apache has a [setting for a PrivateTmp](https://www.google.com/search?q=apache+PrivateTmp&safe=active&sca_esv=566330112&rlz=1C1GCEB_enUS876US876&sxsrf=AM9HkKl4qLrHVlHTgf93Y5O_TtD7ogbLlw%3A1695071911257&ei=p74IZej-DrmxqtsPw6WyoAc&ved=0ahUKEwio7o35irWBAxW5mGoFHcOSDHQQ4dUDCBA&uact=5&oq=apache+PrivateTmp&gs_lp=Egxnd3Mtd2l6LXNlcnAiEWFwYWNoZSBQcml2YXRlVG1wMgQQABhHMgQQABhHMgQQABhHMgQQABhHMgQQABhHMgQQABhHMgQQABhHSN0HUJ4FWJ4FcAF4ApABAJgBAKABAKoBALgBA8gBAPgBAcICChAAGEcY1gQYsAPiAwQYACBBiAYBkAYH&sclient=gws-wiz-serp) which basically "sandboxes" calls to `/tmp` to point _somewhere other than_ the system's `/tmp`. So my site was trying to read `/tmp/secrets.json` from a sandbox.
This was such a pain, but glad I figured it out. Sorry again for posting in your project for something sort of unrelated.

I'll have to give Pantheon the feedback that it would be nice to configure where Drupal is looking for that local secrets file.

**Review by dblanken-yale — APPROVED** [review]
Locally, I had to revert the HTML element patch that @codechefmarc did to get it to complete; I believe this is due to his changes being accepted into the main repo.  I have a couple of PRs with that fix in there.

With that modified, it did work, although I am seeing that it couldn't apply the `add-php-c-format.patch`; I can't see where that would be related to this PR, but first time I ran into that so I thought I'd mention it.  I did have some lando/Docker build issues this afternoon, which took up quite a bit of time.  The solution was to reset the lando docker virtual network, so I doubt it would affect the patch.  I'll be curious if anyone else has this issue.

But as far as the changes in this are concerned, it all looks good and I was able to see the captchas without issue.

**Comment by dblanken-yale** [comment]
Just saw in a different PR that Marc's branch was used fine.  So it probably is a non-issue or something on my end.  Strange that it doesn't work for me.

**Comment by codechefmarc** [comment]
Just FYI, I removed the `add-php-c-format.patch` in the Drupal 10 branch as it wasn't needed. I think because we refactored how dates were being displayed / grabbed for the templates for events a while ago and that patch wasn't doing anything anymore.

**Comment by dblanken-yale** [comment]
Ah, gotcha!  I won't worry about that patch then.  Usually it patches just fine though.  haha

I merged a PR that included the revert on the HTML element filter, so updating the branch should help it build now.

**Pull request merged**
