### PR TITLE
YALB-1644 - Dial: Center-align callout with content-width content

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Adds alignment variable for `callout__alignment`
- Adds a default of `center` - existing callouts will render the same
- Adds a `field_style_alignment` field in Drupal, default is `center`
- Wires the `callout__alignment` variable to `field_style_alignment`
- You can choose between `center` and `left`. `center` uses the `site` width. `left` uses `content` width to restrict the callout inner wrapper width.

### Functional testing steps:
- [x] Review this page with two callouts: https://pr-495-yalesites-platform.pantheonsite.io/welcome/customize-with-confidence
- [x] Verify the callout container is left-aligned and the content area of the callouts is limited to the left-aligned content
Screenshot 2023-11-28 at 11 53 48 AM

- [x] Login and review another test page here - single callout: https://pr-495-yalesites-platform.pantheonsite.io/testing-all-of-the-things 
- [x] Verify it is set to `left` and toggle between `left` and `center` and verify the callout changes.

https://github.com/yalesites-org/yalesites-project/assets/366413/7ffa0d73-fc07-4d37-bb65-814f98585148

### CODE REVIEW

**Review by dblanken-yale — APPROVED** [review]
This looks much better!  Nice job!

**Review by codechefmarc — CHANGES_REQUESTED** [review]
There's a minor change that needs to be made to allow the default option to work as it's currently not selecting a default:

Screenshot 2023-11-29 at 12 04 30 PM

It's editing the config of `field.field.block_content.callout.field_style_alignment.yml` directly and added the `default_value_callback: ys_themes_default_value_function` 

Finally, in your `ys_themes.component_overrides.yml` I think the line should be:
`default: center`
instead of
`default: Center`

Happy to help if you need.

**Comment by joetower** [comment]
@codechefmarc Ah, great catch, thanks! 

I updated both of those. Please give it another look. Thanks!

**Review by codechefmarc — APPROVED** [review]
OK, tested new changes and all looks good to me, approved!

**Review by nJim — APPROVED** [review]

**Pull request merged**
