### PR TITLE
YALB-1141:  Apply alignment rules to layout builder + a color token change

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Fixes alignment for `post`, `event` and `page` content
- Pulls in the latest tokens release to update color names (changed yellow.light to green.light)
- The fixes in this branch contain PRs for the main project, the component library(https://github.com/yalesites-org/component-library-twig/pull/230), and atomic (https://github.com/yalesites-org/atomic/pull/114).

### Functional testing steps:
- [x] Review a post: https://pr-247-yalesites-platform.pantheonsite.io/posts/2023-04-18-longform-article
- [x] Verify it matches our Storybook story: https://deploy-preview-230--dev-component-library-twig.netlify.app/?path=/story/page-examples-post--post-article
- [x] Review an event: https://pr-247-yalesites-platform.pantheonsite.io/events/2023-05-31-event-number-one
- [x] Verify if matches our Storybook story: https://deploy-preview-230--dev-component-library-twig.netlify.app/?path=/story/page-examples-events--event-page
- [x] Review a page: https://pr-247-yalesites-platform.pantheonsite.io/top-goal-site
- [x] Verify if matches our Storybook story: https://deploy-preview-230--dev-component-library-twig.netlify.app/?path=/story/page-examples-standard-pages--with-banner
- [x] Verify that the `event` and `post` lists toward the bottom of the page are aligned properly. I changed the views template to use a component-wrapper and the `label` that is part of it, instead of passing a heading component which was misaligned. 
Screenshot-20230425111307-2192x1127

- [x] Edit the page referenced above and verify you can still move the `event` and `post` views lists around using the layout builder. 
---

#### Color change
- [x] Verify you see `green-light` on this page: https://deploy-preview-230--dev-component-library-twig.netlify.app/?path=/story/tokens-colors--colors
Screenshot-20230425110842-2304x268

### CODE REVIEW

**Review by codechefmarc — APPROVED** [review]
Tested these out and all looks good to me. Approved.

**Review by nJim — APPROVED** [review]
This is perfect. Thank you for your attention to detail and for all of the thought put into the PR testing instruction -- it made things easy to work through and approve.

**Comment by ahitson** [comment]
Longform article:
- The events are bumping outside of the article boundaries. 
- Is the first paragraph just bolded? It looks a step too heavy maybe?
- The menu left edge isn't aligning. 

Event:
- Not a lot there but think it might be ok?

Page:
- The quote spacing keeps getting me. Are we sure these are even (image below)? The attribution part also needs more top margin which I will mention again on the new quote style ticket.
- CTA banner needs more spacing when in the page's content section.
- Event and News lists views are using the wrong format (ALWAYS featured on lists). That non-featured format should not exist for list views. 
- The headings for the lists and cards are incorrect. Should be from Yale font family.
- The solo longform article card view is showing too much supporting text. Did we put a hard limit on that? Or is it pulling automatically from something?

Screen Shot 2023-04-25 at 3 07 17 PM

Screen Shot 2023-04-25 at 3 09 27 PM

**Comment by joetower** [comment]
@ahitson Thank you!

Here are some answers/comments:

- The events are bumping outside of the article boundaries.
  -  Previously these `views` lists weren't allowed on an `article` but with the layout builder work they now are. Are you wanting this instance to limit the width to `content` width? So, I don't think we accounted for this instance in Storybook, yet, so it's not in Drupal.
- Is the first paragraph just bolded? It looks a step too heavy maybe?
  - Yes, I added a text component to the layout build `intro` section and bolded the text.    
-  The menu left edge isn't aligning.
   - The menu is set to `mega` and I thought this is the alignment we agreed upon? So the drop-down border aligns with the site name? Is that wrong? If we align it, it won't be aligned when you click it, unless we want the top-level item to move in-and-out based on whether the link is active or inactive.  
- The quote spacing keeps getting me. Are we sure these are even (image below)? The attribution part also needs more top margin which I will mention again on the new quote style ticket.
  - The quote spacing is the same for `news` and `events`, but different for `pages` because the width of the content is different. 
- CTA banner needs more spacing when in the page's content section.
  - We'll want to discuss this further (how much spacing?) and figure out the logic that governs any extra spacing. 
- Event and News lists views are using the wrong format (ALWAYS featured on lists). That non-featured format should not exist for list views.
  - I'll need to get with @codechefmarc to figure out how to pass `featured: true` to our layout-builder templats. 
- The headings for the lists and cards are incorrect. Should be from Yale font family.
  - I'll look into this.  
-  The solo longform article card view is showing too much supporting text. Did we put a hard limit on that? Or is it pulling automatically from something?
   - I entered all of this sample content just for the sake of testing. Would you like a login link to test and edit the content?
-  Pager is doing some funky logic.
   - I may need @codechefmarc 's help to figure out what's happening there.

**Comment by joetower** [comment]
@ahitson I have pushed up some changes. 


- The events are bumping outside of the article boundaries.
  - Yes, if it is in the article itself, it should stay at content width (or that bumped-out image width). If it is in a space below the article, then it needs a full-width divider above it to separate it from the article content (like if they are related articles).
    - How does this look? (very bottom of the page): https://pr-247-yalesites-platform.pantheonsite.io/posts/2023-04-18-longform-article
    - Can the divider be added as content (divider paragraph), depending on where it's used? I'm trying to think through how we would apply logic to conditionally show a border.

- Is the first paragraph just bolded? It looks a step too heavy maybe?
  - What weight is it? We use Medium for bolded mallory.
    - It is using the `strong` html element, which we had not assigned a specific `font-weight` to, yet. I updated it to `font-weight: var(--font-weights-mallory-medium);` https://pr-247-yalesites-platform.pantheonsite.io/posts/2023-04-18-longform-article

- The menu left edge isn't aligning.
  - The words are supposed to align while the borders go outside of the page boundaries. So when you expand the menu the lines go outside but the words stay put. Could have sworn we already did that step.
    - You're correct, I looked into this more. Some weeks back there was an issue reported with the mega menu alignment. The negative margin on the left-aligned mega menu was removed. This should now be back in place. Please test the alignments and `mega`/ `basic` variations. https://pr-247-yalesites-platform.pantheonsite.io/top-goal-site 

- The quote spacing keeps getting me. Are we sure these are even (image below)? The attribution part also needs more top margin which I will mention again on the new quote style ticket.
  - A margin-top of .4em looks good on the attribution.
    - I have added this and you should see it here: https://pr-247-yalesites-platform.pantheonsite.io/posts/2023-04-18-longform-article | https://pr-247-yalesites-platform.pantheonsite.io/top-goal-site

- The solo longform article card view is showing too much supporting text. Did we put a hard limit on that? Or is it pulling automatically from something?
  - I entered all of this sample content just for the sake of testing. Would you like a login link to test and edit the content?
    - Sure
      - I sent you a link in Slack. Just let me know if you need another one generated.

**Comment by ahitson** [comment]
Events: I'm ok with no border logic at this time. The cards are looking funky, though. White space around the images, and cards too close together.  One hovered shown below.

Bold is good now.

Menu alignment is good now, but when you size down the mobile menu isn't appearing. Also, the closeness of the borders to the primary menu will need attention at some point. 

Name looks good on quote. 

Put in a question on Slack with Jim and Marc about the limits to the teaser text. Didn't see them on the backend. Don't know if we are setting hard or soft limits here and for events, but we 100% need them.

Screen Shot 2023-04-26 at 4 32 07 PM

Screen Shot 2023-04-26 at 4 36 44 PM

**Comment by joetower** [comment]
@ahitson This should be ready for another look, please. 

- The events grid responsiveness should be fixed. The images should fill 100% of the card width
  - https://pr-247-yalesites-platform.pantheonsite.io/posts/2023-04-18-longform-article
- The responsive hamburger icon is back. This was actually a color issue from our global theme work. It should render fine now.
- I'll defer to Jim/Marc on implementing the content limits on teasers.

**Review by ahitson — APPROVED** [review]

**Pull request merged**
