### PR TITLE
YALB-661: Fix duplicate accordion controls

### PR DESCRIPTION
**Pull request by marcb4k**
### Description of work
- Removes duplicate accordion controls
- Editing accordion from demo content is now corrected - accordion items are children of an accordion instead of accordions as children
- Simplified data for migration - less JSON files required

### Functional testing steps:
- [ ] Perform a site install to get the demo content
- [ ] Or, rollback an existing migration (```drush mr --all```), and perform a new migration (```drush mim ys_pages --execute-dependencies```)
- [ ] Verify that the FAQ page now has an accordion with only one control, not two
- [ ] Edit the FAQ page and verify that the children of an accordion paragraph are accordion items, not more accordions

### CODE REVIEW

**Review by nJim — APPROVED** [review]
Code looks great. I ran into a few problems trying to get it to work. The migrations kept failing but the error messages were not helpful. Then I remembered you need to run `cim --partial` to update existing configurations.. Now everything looks great. I can approve the code and it's functionality. You may want to bring this to Mike V as well since he submitted the bug. Good work.

**Comment by marcb4k** [comment]
FYI, Pantheon created multidev with changes: https://pr-77-yalesites-platform.pantheonsite.io/node/13

**Review by myvaughn — COMMENTED** [review]
I only reviewed the build, which looked good (both the published accordion and the authoring interface).

**Comment by myvaughn** [comment]
That review was meant to be an approval, but I clicked approve before adding the comment, and adding the comment changed the approval to comment. Sorry. But I approve!

**Pull request merged**
