### PR TITLE
YSP-532: Increase grand hero video size maximum

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Description of work
- Increases the max file size of a background video from 12 MB to 25 MB

### Functional testing steps:
- [ ] Attempt to upload a background video
- [ ] Verify that the max allowed says 25 MB
- [ ] Verify that you can upload a MP4 that is within that range

### CODE REVIEW

**Comment by miketullo95** [comment]
will look into this!  Did we find the preferred method of compressing video? would be nice to have maybe a tips and tricks with a recommended service to users if they have a larger file

**Comment by dblanken-yale** [comment]
@miketullo95 I posted some tests in the Jira ticket; all are great in order to get to below 25MB I think.  Adobe Media Encoder is in our license so maybe that should be it?  But they'd have to play with the presets which might not be ideal.

**Review by miketullo95 — APPROVED** [review]
added a 17MB video to grand hero here: https://pr-667-yalesites-platform.pantheonsite.io/

looks great!

**Review by codechefmarc — APPROVED** [review]
Tested with a 21 MB video, worked great. Approved!

**Review by nJim — APPROVED** [review]
Updates are as described.

**Pull request merged**
