### PR TITLE
IYY-267: Add Last Updated by to Content admin

### PR DESCRIPTION
**Pull request by codechefmarc**
### Description of work
- Adds Last Updated By field to Content, Manage Pages, and Manage Posts views listings

### Functional testing steps:
- [x] Login to the site
- [x] Visit the Content page, the Content -> Manage Pages, and the Content -> Manage Posts pages
- [x] Verify that there is a new "Last Updated By" field in the list

Screenshot 2024-11-15 at 5 58 13 PM

### CODE REVIEW

**Comment by dblanken-yale** [comment]
Looking great and works as intended.  I did have a few questions/requests about this in relation to Manage Events/Profiles.

1. Manage Events and Content views has a label of "Author", which I looks to be "Last Updated by".  Would it be ok to also rename Author to that label as well?  Actually, looking at it, Author in Content is different than Author in the Manage Events.  I wonder how useful original author is in this over just the last updated by?
2. For consistency, could we add it to Profiles also since it's then the lone wolf?
3. And I noticed you placed this at the end after "Updated"; could this be followed in all 5?  Just thinking we might want people to get in the habit of always seeing "Updated" and then "Last Updated By".

**Review by dblanken-yale — APPROVED** [review]
As far as the work that was stated, it all looks great.  Going to approve but hoping the other questions/requests might be able to be added to this.  :D

**Comment by dblanken-yale** [comment]
Looks great!  I'll let @miketullo95 and the rest chime in on it, but functions as I expected.  :D

**Review by miketullo95 — APPROVED** [review]
looks great! 😄

**Pull request merged**
