### PR TITLE
YALB-1206: Reorganize theme settings tools YALB-1430: Theme settings link jumps

### PR DESCRIPTION
**Pull request by nJim**
### Description of work
- Movies the 'Theme settings' link to the main toolbar
- Adds icons to the 'Settings' and 'Theme settings' items in the toolbar.
- Displays a message if users try to change theme settings while not viewing a node.
- Reorganize and clean up code
  - Move gin-overrides into a separate CSS file for clarity
  - Move ys_theme specific code to the ys_theme module (instead of the ys_toolbar module)

### Functional testing steps:
- [x] Login to the website as a site admin.
- [x] Confirm that the 'Settings' and 'Theme Settings' items have nice icons.
- [x] Confirm that the 'Theme settings' item appears in the top toolbar.
- [x] Navigate to an admin interface (admin/content/manage-pages)
- [x] Click on the 'Theme settings' link. Verify that a message displays since the users is not in a place where settings can be previewed. 
- [ ] Navigate to a content page. Click on the 'Theme settings' link and verify that the form continues to work.

### CODE REVIEW

**Comment by dblanken-yale** [comment]
@nJim I saw it bombed on a lint error, but now it's bombing on the html element filter.  I'm going to push through my PR that reverts that branch back to main since it's been incorporated so that it becomes successful.  We can rebase it tomorrow and I'll take a look.  :D

**Comment by dblanken-yale** [comment]
Screenshot 2023-10-18 at 9 08 55 AM

@nJim I see the message, but I also see the `Save configuration` button, which seems a bit strange.

**Comment by dblanken-yale** [comment]
Screenshot 2023-10-18 at 9 10 55 AM

I think I also broke it; I hit "Save configuration" and then went to visit a page and go to theme settings and it is showing the overall theme at the top item, but the rest are not colored.  :(

**Comment by dblanken-yale** [comment]
Screenshot 2023-10-18 at 9 12 16 AM

I went ahead and selected in the hope it would fix itself, but then saw this page on save.  Is this ok?

**Review by dblanken-yale — CHANGES_REQUESTED** [review]
I left some comments before; let me know once they are resolved or let me know if some of it is by design and I'll take another look.  :D

I also didn't notice an image next to the Theme Settings, although it looks as though in the PR that maybe it should be included?  Just checking.

**Comment by nJim** [comment]
Discussed this work with Kara. We plan to move 'Theme Settings' under the 'Settings' menu. She will confirm with Mike T.

**Comment by nJim** [comment]
Closing this PR. This work was replaced by https://github.com/yalesites-org/yalesites-project/pull/633

**Pull request closed without merging**
