### PR TITLE
YSP-641: Image banner block

### PR DESCRIPTION
**Pull request by dblanken-yale**
### Description of work
- Wires up Atomic/CL image banner component
- Enables reusable block for image banner
- Adds image banner image for block selection

### Functional testing steps:
- [ ] Add an image banner to a page
- [ ] Ensure you can add an image or a video
- [ ] Ensure that the image block picker shows a banner image image
- [ ] Ensure you can enable it as a reusable block

### CODE REVIEW

**Comment by chaohlu** [comment]
- [Y]  Add an image banner to a page
- [X] Ensure you can add an image or a video
- [Y ] Ensure that the image block picker shows a banner image image
- [Y ] Ensure you can enable it as a reusable block
Link to my test page](https://pr-748-yalesites-platform.pantheonsite.io/chaos-test-page)

I wasn't able to add image or video once I add Image banner block on the same section. But I was able to add them on new section page. Not sure if I test correct.

**Comment by dblanken-yale** [comment]
@chaohlu Ya I need to look again at that configuration--I had it working but now on the multidev it's not allowing it.  Thanks for looking.  I think you did it right, it's just that multidev didn't get that config.

**Review by kara-franco — APPROVED** [review]
Nice job, this is a great new block!

**Review by atiddei — APPROVED** [review]

**Pull request merged**
