### PR TITLE
YALB-1660 - Quality of profile page media image in responsive design | YALB-1661 - Profile media image being used for page and view block | YALB-1662 - Mobile view profile list 

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- 1660: Adds new responsive image style for `banner_profile` along with a media view mode of the same name to better size Profile-specific banner images
  - At a min-width of 991px and 1344px the banner image will be `640px` wide. 
  - Below 991px, the image will use whichever image style is closest to 100% of the viewport width because the image stacks and is 100%.
- 1661: Sets a default profile image to use if there is no teaser image or banner image
- 1662: Adjust the text content in the mobile display of Profile cards - list to be only as wide as the image

#### Testing:  [YALB-1660 - Quality of profile page media image in responsive design ](https://yaleits.atlassian.net/browse/YALB-1660)

- [x] Navigate to: https://pr-503-yalesites-platform.pantheonsite.io/profile/mrs-first-lastly
- [x] Inspect the image in the banner and verify it is an appropriate size at desktop resolutions and the image looks crisp (640px)

https://github.com/yalesites-org/yalesites-project/assets/366413/2bd3f830-cec8-4f93-baae-8e98357ecc85

---

#### Testing: [YALB-1661 - Profile media image being used for page and view block](https://yaleits.atlassian.net/browse/YALB-1661)

- [x] Navigate to: https://pr-503-yalesites-platform.pantheonsite.io/testing-profile-views
- [x] Verify the item with the image labeled "Fallback Image", when clicked and you navigate to the full profile page, there is no image on the profile page. 
- [x] Verify you can set a custom fallback here: https://pr-503-yalesites-platform.pantheonsite.io/admin/yalesites/settings

https://github.com/yalesites-org/yalesites-project/assets/366413/095ac5b8-35f0-46f0-9b44-2d3f1d310e8c

 
---

#### Testing: [YALB-1662 - Mobile view profile list](https://yaleits.atlassian.net/browse/YALB-1662)
- [x] Navigate to: https://pr-503-yalesites-platform.pantheonsite.io/testing-profile-views
- [x] Scroll down to the "Profile View - List" section
- [x] Verify the content width under the image is limited to the same width/space as the image

https://github.com/yalesites-org/yalesites-project/assets/366413/66c1663d-046c-47e7-84cd-d7281c0ce926

### CODE REVIEW

**Comment by dblanken-yale** [comment]
Just verifying, the fallback chain is: profile > teaser > custom fallback?  I think that's what I remembered.

**Review by dblanken-yale — APPROVED** [review]
These changes are so good.  I'm going to look at the other repos to see more, but this is great!  Nice job!  Even without a fallback it looks good.

**Comment by codechefmarc** [comment]
> Just verifying, the fallback chain is: teaser > profile > custom fallback? I think that's what I remembered.

Yup, that was what we went with. We can change it, of course, but this made the most sense.

**Review by codechefmarc — APPROVED** [review]
Looks great to me! Tested in Arc and Safari and all worked well. Approved!

**Review by nJim — APPROVED** [review]

**Pull request merged**
